"""Generate the wide-bkg16 demo: a WIDE horizontally-scrolling Atari Lynx level
rendered at native 16 colours by the 4bpp COLUMN-strip background engine.

This is the wide (`engine.scroll`) counterpart of `projects/bkg16-demo`: the Lynx
has no tilemap, so a wide level streams one column per 8 px of scroll into a ring
of per-column Suzy strips. With `[build] lynx_bkg16 = true` those strips are BPP_4
and `palette.load_bkg16` loads 16 authored colours into the Mikey pens, so a
scrolling rainbow shows all sixteen at once. A hand-written game supplies its own
4bpp tiles (no scenes module to auto-detect depth), so it opts in with the
`[build]` knob; the doubled column RAM is sized with `[build] bkg_max_tiles`.

    python projects/wide-bkg16/assets/gen_main.py

Lynx-only: hand-authored 4bpp tiles are a Lynx-native format (a portable
multi-console 16-colour background uses the scenes path -- see projects/vm-bkg16).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)

NTILES = 16
WCOLS = 64        # logical map width in tiles (512 px, past the 256 px wrap)
VROWS = 13        # visible rows on the 102 px Lynx screen (no vertical scroll)

# 16 vivid colours as 15-bit 5-5-5 RGB words (what palette.load_bkg16 consumes).
PAL = [
    (24, 20, 16), (230, 60, 60), (245, 140, 40), (245, 225, 60),
    (120, 220, 70), (60, 200, 90), (60, 210, 200), (60, 150, 240),
    (80, 90, 240), (150, 70, 230), (230, 80, 220), (245, 130, 180),
    (150, 90, 60), (200, 200, 210), (120, 125, 135), (250, 250, 250),
]


def rgb555(c):
    r, g, b = c
    return ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)


def tile4bpp(idx):
    # A solid tile of pen index `idx`: 8 rows x 4 bytes, two 4-bit pixels/byte.
    byte = (idx << 4) | idx
    return [byte] * 32


def _fmt(vals, per_line=16):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("        " + ", ".join(
            ("0x%02X" % v if v > 9 else str(v)) for v in vals[i:i + per_line]))
    return ",\n".join(out)


def main():
    tiles = []
    for k in range(NTILES):
        tiles += tile4bpp(k)
    pal = [rgb555(c) for c in PAL]
    # Wide map: column c shows tile (c % 16) -> a scrolling 16-colour rainbow.
    flat = [(c % NTILES) for _ in range(VROWS) for c in range(WCOLS)]

    src = '''-- main.mos -- GENERATED by projects/wide-bkg16/assets/gen_main.py
-- A WIDE horizontally-scrolling Atari Lynx level at native 16 colours: the 4bpp
-- COLUMN-strip background engine (engine.scroll) + palette.load_bkg16. Opt in with
-- [build] lynx_bkg16 = true; size the doubled column RAM with [build] bkg_max_tiles.
-- Lynx-only (hand-authored 4bpp tiles); the portable path is projects/vm-bkg16.

module "wide_bkg16" {
    import "platform.video"
    import "platform.input"
    import "graphics.bkg"
    import "graphics.palette"
    import "engine.scroll"

    const WCOLS: u16 = %d
    const VROWS: u8 = %d
    const SPEED: u16 = 1
    const MAX_X: u16 = %d          -- WCOLS*8 - 160 (right-edge clamp)

    -- 16 solid-colour tiles, packed-nibble 4bpp (32 B/tile = the Suzy literal).
    const TILES: array[u8, %d] = [
%s
    ]
    -- The 16 authored colours (5-5-5 RGB), loaded into the Mikey pens.
    const PAL16: array[u16, 16] = [
%s
    ]
    -- The wide logical map, ROW-MAJOR: MAP[r * WCOLS + c] = c %% 16.
    const MAP: array[u8, %d] = [
%s
    ]

    var camx: u16 = 0

    function gather(c: u16) {
        var idx: u16 = c
        var r: u8 = 0
        while r < VROWS {
            scroll.buf[r] = MAP[idx]
            idx = idx + WCOLS
            r = r + 1
        }
    }

    function main() {
        video.disable_lcd()
        bkg.set_data(0, %d, TILES)
        palette.load_bkg16(PAL16)          -- 16 colours -> the Mikey pens
        scroll.fill(WCOLS, VROWS, gather)  -- seed the first columns

        video.enable_lcd()
        video.show_background()

        loop {
            if camx < MAX_X { camx = camx + SPEED }
            if input.held(INPUT_LEFT) {
                if camx >= SPEED { camx = camx - SPEED }
            }
            if input.held(INPUT_RIGHT) {
                if camx + SPEED <= MAX_X { camx = camx + SPEED }
            }
            scroll.update(camx, gather)
            video.wait_vblank()
        }
    }

    export main
}
''' % (WCOLS, VROWS, WCOLS * 8 - 160, len(tiles), _fmt(tiles),
       ",\n".join("        0x%04X" % w for w in pal),
       len(flat), _fmt(flat), NTILES)

    with open(os.path.join(PROJ, "src", "main.mos"), "w", encoding="utf-8") as f:
        f.write(src)
    print("wrote wide-bkg16 main.mos (%d 4bpp tiles, %dx%d wide map)"
          % (NTILES, WCOLS, VROWS))


if __name__ == "__main__":
    main()
