#!/usr/bin/env python3
"""Generate vm-uiquest -- a VM8 PORT of the composed studio showcase `ui-quest`.
ui-quest is the UI-chrome showcase: a title
MENU, a field with a SIGN you read, and a pause OVERLAY -- every box wearing a frame
+ a custom font. It maps cleanly onto VM8: menus are the `menu` op, the sign is a
`vm.entity` On Interact dialogue, the pause overlay is a Start-attached `menu`, the
custom font is `text.set_font`, and the framed box is the opt-in `engine.box` pack.

(The one deviation from the composer: VM8's framed box is the built-in portable
`+--+` 9-slice, not ui-quest's custom 9-slice-PNG frame -- a custom-frame image is a
composer feature the VM does not have yet. The FONT is the same, and every box IS
framed. So this is the ui-quest GAME on the VM, ~1:1 minus the frame art.)

  python projects/vm-uiquest/assets/gen_world.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PROJ))
sys.path.insert(0, ROOT)

W, H = 12, 9


def room(floor=0):
    tiles, coll = [], []
    for y in range(H):
        trow, crow = [], []
        for x in range(W):
            wall = x == 0 or y == 0 or x == W - 1 or y == H - 1
            trow.append(1 if wall else floor)
            crow.append(1 if wall else 0)
        tiles.append(trow)
        coll.append(crow)
    return tiles, coll


def rows(g):
    return "[" + ", ".join("[" + ",".join(str(v) for v in r) + "]" for r in g) + "]"


def main():
    title_t, title_c = room(floor=2)     # a distinct backdrop for the title
    field_t, field_c = room(floor=0)

    from mosaik_assets import write_png_indexed
    pal = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    os.makedirs(os.path.join(PROJ, "assets"), exist_ok=True)
    write_png_indexed(os.path.join(PROJ, "assets", "tiles.png"), 8, 24,
                      [0] * 64 + [3] * 64 + [1] * 64, pal)

    world = [
        "# vm-uiquest -- GENERATED by assets/gen_world.py.",
        '[[scene]]', 'name = "title"',
        "map = %s" % rows(title_t), "collision = %s" % rows(title_c),
        'on_init = "title_init"',          # the title MENU (no player here)
        "",
        '[[scene]]', 'name = "field"',
        "map = %s" % rows(field_t), "collision = %s" % rows(field_c),
        'on_init = "field_init"',          # attach the pause overlay
        '[[scene.object]]\nkind = "player"\nid = 0\nx = 48\ny = 56',
        '[[scene.object]]\nkind = "sign"\nid = 1\nx = 40\ny = 24'
        '\non_interact = "sign_talk"',
        "",
        '[world]\nmodule = "scenes"\nmap_w = %d\nmap_h = %d\nvm = true'
        '\nstart_scene = "title"\nnext_object_id = 2' % (W, H),
        '[tileset]\npng = "assets/tiles.png"',
        '[kinds]\nplayer = 0\nsign = 1',
    ]
    with open(os.path.join(PROJ, "world.toml"), "w", encoding="utf-8") as f:
        f.write("\n".join(world) + "\n")

    events = '''# vm-uiquest -- the UI-chrome game as event scripts (menus + dialogue).
[[script]]
name = "main"
events = [ { event = "change_scene", room = 0, x = 0, y = 0 }, { event = "stop" } ]

# The TITLE menu (the title scene's On Init): START -> field, QUIT -> reload title.
[[script]]
name = "title_init"
events = [
  { event = "input_detach", button = "start" },
  { event = "menu", var = "choice", row = 6, options = ["START", "QUIT"] },
  { event = "if", cond = "choice == 0",
    then = [ { event = "change_scene", room = 1, x = 48, y = 56 } ],
    else = [ { event = "change_scene", room = 0, x = 0, y = 0 } ] },
  { event = "stop" },
]

# The field's On Init: bind Start to the pause overlay.
[[script]]
name = "field_init"
events = [
  { event = "input_attach", button = "start", script = "pause" },
  { event = "stop" },
]

# The SIGN (On Interact): a two-page framed dialogue in the custom font.
[[script]]
name = "sign_talk"
events = [
  { event = "text", string = "WELCOME TO\\nUI-QUEST!" },
  { event = "text", string = "EVERY BOX HAS\\nA FRAME." },
  { event = "stop" },
]

# The pause OVERLAY (Start): RESUME closes, TO TITLE returns to the title.
[[script]]
name = "pause"
events = [
  { event = "menu", var = "pchoice", row = 6, options = ["RESUME", "TO TITLE"] },
  { event = "if", cond = "pchoice == 1",
    then = [ { event = "change_scene", room = 0, x = 0, y = 0 } ] },
  { event = "stop" },
]
'''
    os.makedirs(os.path.join(PROJ, "scripts"), exist_ok=True)
    with open(os.path.join(PROJ, "scripts", "main.evt.toml"), "w",
              encoding="utf-8") as f:
        f.write(events)

    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_scenes.py"),
                    os.path.join(PROJ, "world.toml"),
                    "-o", os.path.join(PROJ, "src", "scenes.mos")], check=True, cwd=ROOT)
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_vm.py"),
                    os.path.join(PROJ, "scripts"),
                    "-o", os.path.join(PROJ, "src", "scripts.mos")], check=True, cwd=ROOT)
    print("vm-uiquest generated")


if __name__ == "__main__":
    main()
