#!/usr/bin/env python3
"""The OVERLAY CUT as a SOLE TENANT of `LYC_REG`, measured on a real ROM.

`projects/lyc-merge-lab` phase [D] is the GATE for the cut, and it drives the
MERGED form - three tenants in one program, on the flat cart and on a banked
copy. What it cannot reach is the other emitted form: with the cut as the only
tenant, `_lyc_used()` is false and `gbdk_text._emit_win_overlay_cut_solo`
arms `LYC_REG` itself through its own chained handler. That shape has no
sample: the parallax bands have `parallax-spike` and the box's sprite cut has
every VM8 project with dialogue, but nothing on disk uses the overlay cut
alone.

So this builds one - the CURTAIN shape, which is the feature's first real use:
the window raised with `window.move` + `video.show_window` and **no text on it
at all**, which is also what the verb's emission gate has to cover (it is gated
on the window LAYER existing, not on `text.to_window`).

The picture is the measurement. The window map is filled with tile 1 (solid)
and the background with tile 0 (blank), so one rendered frame says exactly
where the layer stops - no register read, no symbol lookup.

Measured 2026-09-19, cut armed at 96:

    rows 0..96   one colour, the window's
    rows 97..143 one colour, the background's

**The cut takes hold on the line AFTER the one it names, and that is PARITY**:
the handler spins for H-blank before writing LCDC, exactly as the reference VM's own
`simple_LCD_isr` does, so the named line is still whole.

Usage: overlay_cut_solo_probe.py        (builds a throwaway ROM and measures)
"""
import io
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PROJ = os.path.join(ROOT, ".scratch", "ocut-solo")
CUT = 96

TOML = '''[project]
name = "ocut-solo"
version = "1.0.0"
# GENERATED by tools/cutprobe/overlay_cut_solo_probe.py - not a sample.
target_platforms = [ "gameboy",]

[source]
folder = "src/"

[build]
output_dir = "build"
'''

MAIN = '''-- GENERATED by tools/cutprobe/overlay_cut_solo_probe.py.
--
-- The OVERLAY CUT as a SOLE tenant of LYC_REG, in the CURTAIN shape: the
-- window raised with window.move + video.show_window and no text on it, which
-- is the feature's first real use and what its emission gate has to cover.
-- Window tiles are solid, background tiles blank, so a rendered frame says
-- where the layer stops.
module "ocut_solo" {
    import "platform.video"
    import "graphics.text"
    import "graphics.window"
    import "graphics.bkg"

    const TILES: array[u8, 32] = [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
    ]

    var row: array[u8, 20]

    function main() {
        video.disable_lcd()
        bkg.set_data(0, 2, TILES)
        for i in 0..20 {
            row[i] = 1
        }
        for y in 0..18 {
            window.set_tiles(0, y, 20, 1, row)
        }
        window.move(7, 0)
        video.enable_lcd()
        video.show_window()
        text.win_overlay_cut(%d)
        loop { video.wait_vblank() }
    }
    export main
}
''' % CUT


def write():
    src = os.path.join(PROJ, "src")
    if not os.path.isdir(src):
        os.makedirs(src)
    # Build the whole text BEFORE opening the file (the generator rule): a
    # truncate-then-raise leaves a zero-byte module that fails layers later.
    for path, text in ((os.path.join(PROJ, "mosaik.toml"), TOML),
                       (os.path.join(src, "main.mos"), MAIN)):
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)


def build():
    r = subprocess.run([sys.executable, os.path.join(ROOT, "mosaik8.py"),
                        "build", "--platform", "gameboy", PROJ],
                       capture_output=True, text=True, cwd=ROOT,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or "ROM created" not in r.stdout:
        print(r.stdout[-2000:])
        print(r.stderr[-2000:])
        return None
    return os.path.join(PROJ, "build", "gameboy", "ocut-solo.gb")


def colours(px, y0, y1):
    out = set()
    for y in range(y0, y1):
        for p in px[y]:
            out.add(tuple(int(v) for v in p[:3]))
    return out


def main():
    write()
    rom = build()
    if rom is None:
        print("FAILED: the solo-cut probe did not build")
        return 1
    try:
        from pyboy import PyBoy
    except ImportError:
        print("SKIP: PyBoy is not installed (the ROM built, which is half of it)")
        return 0
    pb = PyBoy(rom, window="null")
    for _ in range(120):
        pb.tick()
    px = pb.screen.ndarray
    above = colours(px, 0, CUT + 1)
    below = colours(px, CUT + 1, 144)
    pb.stop(save=False)
    print("cut armed at %d" % CUT)
    print("  rows 0..%-3d %s" % (CUT, sorted(above)))
    print("  rows %d..143 %s" % (CUT + 1, sorted(below)))
    ok = len(above) == 1 and len(below) == 1 and above != below
    print("\n%s" % ("the overlay stops at the cut and the room draws below it"
                    if ok else
                    "FAILED: the layer did not stop at the cut"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
