#!/usr/bin/env python3
"""Generate vm-rpg -- the VM8 COMPOSITION proof (the Stage-4 flagship). It
reproduces studio-demo's CORE loop by COMPOSING every VM8
kit into one small RPG:

  * field -- talk to the ELDER (a per-instance On Interact dialogue) for the vault
    KEY (a heap flag), then a flag-GATED door (a scriptable trigger + change_scene);
  * cave  -- fight two GUARDIAN enemies (vm.combat: chase / sword / contact) under a
    heart HUD (engine.hud); a death reloads the field with full hearts.

So one shell drives vm.entity (the elder) + vm.trigger (the gate) + vm.combat + the
HUD together -- the "do the kits compose into a real game?" proof. Author it as DATA:
world.toml (placements + the gate) + scripts/*.evt.toml (dialogue + the gate check),
then the transpilers emit src/scenes.mos + src/scripts.mos.

  python projects/vm-rpg/assets/gen_world.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PROJ))
sys.path.insert(0, ROOT)

W, H = 12, 9


def room(floor=0):
    tiles, coll = [], []
    for y in range(H):
        trow, crow = [], []
        for x in range(W):
            wall = x == 0 or y == 0 or x == W - 1 or y == H - 1
            trow.append(1 if wall else floor)
            crow.append(1 if wall else 0)
        tiles.append(trow)
        coll.append(crow)
    return tiles, coll


def rows(g):
    return "[" + ", ".join("[" + ",".join(str(v) for v in r) + "]" for r in g) + "]"


def main():
    field_t, field_c = room(floor=0)
    cave_t, cave_c = room(floor=2)        # a distinct floor -> the cave reads differently

    from mosaik_assets import write_png_indexed
    pal = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    os.makedirs(os.path.join(PROJ, "assets"), exist_ok=True)
    # bkg tiles: 0 field floor, 1 wall, 2 cave floor
    write_png_indexed(os.path.join(PROJ, "assets", "tiles.png"), 8, 24,
                      [0] * 64 + [3] * 64 + [1] * 64, pal)

    world = [
        "# vm-rpg -- GENERATED by assets/gen_world.py (edit that + rerun).",
        '[[scene]]', 'name = "field"',
        "map = %s" % rows(field_t), "collision = %s" % rows(field_c),
        '[[scene.object]]\nkind = "player"\nid = 0\nx = 48\ny = 56',
        '[[scene.object]]\nkind = "elder"\nid = 1\nx = 24\ny = 24'
        '\non_interact = "elder_talk"',
        "",
        '[[scene]]', 'name = "cave"',
        "map = %s" % rows(cave_t), "collision = %s" % rows(cave_c),
        'on_init = "cave_init"',
        '[[scene.object]]\nkind = "enemy"\nid = 2\nx = 24\ny = 24',
        '[[scene.object]]\nkind = "enemy"\nid = 3\nx = 72\ny = 24',
        "",
        # the flag-gated door: a 1x2 trigger over the top-centre field doorway
        '[[trigger]]',
        'id = 1\nfrom = "field"\ntx = 5\nty = 1\ntw = 1\nth = 2\non_enter = "gate"',
        "",
        '[world]\nmodule = "scenes"\nmap_w = %d\nmap_h = %d\nvm = true'
        '\nnext_object_id = 4\nnext_trigger_id = 2' % (W, H),
        '[tileset]\npng = "assets/tiles.png"',
        '[kinds]\nplayer = 0\nelder = 1\nenemy = 2',
    ]
    with open(os.path.join(PROJ, "world.toml"), "w", encoding="utf-8") as f:
        f.write("\n".join(world) + "\n")

    events = '''# vm-rpg logic. elder_talk grants the key (say-once); gate checks it.
[[script]]
name = "main"
events = [ { event = "stop" } ]

[[script]]
name = "elder_talk"
events = [
  { event = "if", cond = "has_key == 0",
    then = [
      { event = "set_var", var = "has_key", value = 1 },
      { event = "text", string = "TAKE THE KEY!" },
    ],
    else = [
      { event = "text", string = "THE CAVE AWAITS." },
    ] },
  { event = "stop" },
]

[[script]]
name = "gate"
events = [
  { event = "if", cond = "has_key == 1",
    then = [
      { event = "change_scene", room = 1, x = 48, y = 60 },
    ],
    else = [
      { event = "text", string = "CAVE IS LOCKED." },
    ] },
  { event = "stop" },
]

[[script]]
name = "cave_init"
events = [
  { event = "text", string = "FIGHT!" },
  { event = "stop" },
]
'''
    os.makedirs(os.path.join(PROJ, "scripts"), exist_ok=True)
    with open(os.path.join(PROJ, "scripts", "main.evt.toml"), "w",
              encoding="utf-8") as f:
        f.write(events)

    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_scenes.py"),
                    os.path.join(PROJ, "world.toml"),
                    "-o", os.path.join(PROJ, "src", "scenes.mos")], check=True, cwd=ROOT)
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_vm.py"),
                    os.path.join(PROJ, "scripts"),
                    "-o", os.path.join(PROJ, "src", "scripts.mos")], check=True, cwd=ROOT)
    print("vm-rpg generated")


if __name__ == "__main__":
    main()
