#!/usr/bin/env python3
"""vm-palettes: does every Palettes-dock option reach a GBC ROM?

Read off the SCREEN by hue (PyBoy's OCPD/BCPD reads are raw, not indexed), on
the meadow the game boots into:

1. per-TILE slots under the world DEFAULT row: grass green, water blue, brick
   red;
2. the SPLIT: the mossy south-wall cells draw the brick tile through the grass
   palette while the rest of the wall stays red;
3. per-CELL sprite slots: the hero's head is skin-coloured and its body blue;
4. the gem's FRAME palette alternates a warm and a cool set;
5. the runtime writes: walking east over the path trigger turns the grass to
   night blue, walking back west restores it.

The world is generated by the studio's tools/gen_samples/vm_palettes_world.py.

    python projects/vm-palettes/verify.py [rom]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(HERE, "build", "gameboy_color", "vm-palettes.gbc")

ok = True


def check(label, cond):
    global ok
    print("  [%s] %s" % ("PASS" if cond else "FAIL", label))
    ok &= bool(cond)


def px(pb, x, y):
    return tuple(int(v) for v in pb.screen.ndarray[y, x, :3])


def green(c):
    return c[1] > c[0] + 20 and c[1] > c[2] + 20


def blue(c):
    return c[2] > c[0] + 30 and c[2] >= c[1]


def red(c):
    return c[0] > c[1] + 40 and c[0] > c[2] + 40


def region(pb, x0, y0, x1, y1):
    a = pb.screen.ndarray[y0:y1, x0:x1, :3].reshape(-1, 3)
    return {tuple(int(v) for v in c) for c in a}


def main():
    rom = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    if not os.path.isfile(rom):
        print("build it first: python mosaik8.py build --platform gameboy_color "
              "projects/vm-palettes")
        return 0
    from pyboy import PyBoy
    pb = PyBoy(rom, window="null", sound_emulated=False, cgb=True)
    for _ in range(150):
        pb.tick()
    print("[vm-palettes on the Game Boy Color]")
    check("grass (tile slot 1) is green: %r" % (px(pb, 20, 120),),
          green(px(pb, 20, 120)))
    check("water (tile slot 2) is blue: %r" % (px(pb, 100, 36),),
          blue(px(pb, 100, 36)))
    check("brick (tile slot 3) is red: %r" % (px(pb, 84, 140),),
          red(px(pb, 84, 140)))
    check("the SPLIT brick cells are moss green: %r" % (px(pb, 36, 140),),
          green(px(pb, 36, 140)))
    hero = region(pb, 24, 48, 64, 96)
    check("the hero wears two palettes (a blue body and a skin head)",
          any(blue(c) for c in hero)
          and any(c[0] > c[1] > c[2] and c[0] > 200 for c in hero))
    warm = cool = False
    for _ in range(80):
        pb.tick()
        gem = region(pb, 112, 96, 144, 128)
        warm |= any(c[0] > c[2] + 80 and c[1] > 60 for c in gem)
        cool |= any(c[2] > c[0] + 80 for c in gem)
    check("the gem's frame palette alternates warm and cool", warm and cool)
    before = px(pb, 20, 120)
    pb.button_press("right")
    night = None
    for f in range(150):
        pb.tick()
        if blue(px(pb, 20, 120)):
            night = f
            break
    pb.button_release("right")
    check("walking east writes the night palette into slot 1 (frame %s)" % night,
          night is not None)
    pb.button_press("left")
    day = None
    for f in range(200):
        pb.tick()
        if px(pb, 20, 120) == before:
            day = f
            break
    pb.button_release("left")
    check("walking west restores the grass (frame %s)" % day, day is not None)
    pb.stop(save=False)
    print("All checks passed" if ok else "FAILURES")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
