[[scene]]
name = "field"
map = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
collision = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
on_init = "field_init"
[[scene.object]]
kind = "player"
x = 48
y = 56
id = 0

[[scene.object]]
kind = "elder"
x = 24
y = 24
id = 1
on_interact = "dlg_obj_1"

[[scene.object]]
kind = "merchant"
x = 72
y = 24
id = 2
on_interact = "merchant_talk"


[[scene]]
name = "shrine"
map = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
object = []
collision = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
on_init = "shrine_init"

[[trigger]]
from = "field"
tx = 5
ty = 1
tw = 2
on_enter = "to_shrine"
id = 1

[[trigger]]
from = "field"
tx = 4
ty = 5
tw = 4
on_enter = "play_gather"
id = 2

[[trigger]]
from = "field"
tx = 4
ty = 1
id = 3

[world]
module = "scenes"
map_w = 12
map_h = 9
vm = true
next_door_id = 0
next_object_id = 3
next_trigger_id = 4

[tileset]
png = "assets/tiles.png"

[kinds]
player = 0
elder = 1
merchant = 2
