"""mosaik_vm.emotes - generate `src/emotes.mos`, the EMOTE ART uploader.

An emote bubble (the reference engine's EVENT_ACTOR_EMOTE) is a 2x2 sprite that pops up
over an actor's head. `lib/vm/emote.mos` owns the timing, the bounce and the
OAM fan; what it cannot own is the ART, because a project's emote set is
project data. This module is the bridge: a `switch` over emote id that uploads
that emote's four tiles into the reserved VRAM window.

The art rides the ORDINARY named-sheet pipeline - one small PNG per emote in
`[assets] sprites` - so there is no new asset format and no new converter. That
is also why the uploader is a generated dispatch rather than one indexed table:
each sheet is its own C symbol, and mosaik has no pointer arithmetic to offset
into a combined one.

Uploading ON DEMAND (4 tiles at a time) rather than keeping the whole set
resident is the reference engine's own choice and for its reason: eight emotes would be 32
of the Game Boy's 128 exclusive OBJ tiles, a quarter of the room's sprite art
budget, to show one bubble at a time.

Opt-in: no `[emotes] sheets` in studio.toml -> no module, byte-identical.
"""
import os


def emote_sheets(studio):
    """The project's emote asset stems, in id order (studio.toml `[emotes]
    sheets`). Empty when the project has none."""
    return list((studio.get("emotes", {}) or {}).get("sheets", []) or [])


def emote_expand_events(events, names):
    """Resolve every `actor_emote` whose `emote` is a NAME to its index
    (recursing into if/switch bodies). A missing name -> 0. An int is left
    as-is.

    Same shape and the same reason as `songs.song_expand_events`: the op
    carries an INDEX (the position in `[emotes] sheets`, which is what
    `emotes.upload` dispatches on), but an index is not something a human can
    read or re-order safely, so an authored file may name the emote instead.
    Both spellings stay valid, which is what keeps every existing conversion -
    all of which emit indices - byte-identical.
    """
    out = []
    for ev in (events or []):
        if not isinstance(ev, dict):
            out.append(ev)
            continue
        ev = dict(ev)
        if ev.get("event") == "actor_emote" and isinstance(ev.get("emote"), str):
            nm = ev["emote"].strip()
            ev["emote"] = names.index(nm) if nm in names else 0
        for key in ("then", "else", "default"):
            if isinstance(ev.get(key), list):
                ev[key] = emote_expand_events(ev[key], names)
        if isinstance(ev.get("cases"), list):
            ev["cases"] = [dict(c, then=emote_expand_events(c.get("then", []), names))
                           if isinstance(c, dict) else c for c in ev["cases"]]
        out.append(ev)
    return out


def emote_expand_scripts(scripts, names):
    """Apply :func:`emote_expand_events` to every script (a copy)."""
    if not names:
        return scripts
    return [dict(s, events=emote_expand_events(s.get("events", []), names))
            for s in (scripts or [])]


def emit_emotes_mos(stems):
    """The `emotes` module text for `stems` (asset stems, id = list position)."""
    L = ["-- GENERATED by MosaiK8 Studio (mosaik_vm) -- the emote-bubble art uploader.",
         "-- One 2x2 emote is on screen at a time (vm.emote owns the timing and the",
         "-- bounce), so its four tiles are uploaded into a reserved VRAM window when",
         "-- the bubble pops rather than kept resident. Regenerated from the project's",
         "-- [emotes] sheets; edit the art, not this file.",
         "",
         'module "emotes" {',
         '    import "graphics.sprite"',
         "",
         "    const COUNT: u8 = %d" % len(stems),
         "",
         "    -- Upload emote `id`'s tiles at VRAM tile `base`. An unknown id",
         "    -- uploads nothing, so a stale index leaves the previous bubble's",
         "    -- art rather than writing garbage over the room's sprites.",
         "    function upload(id: u8, base: u8) {"]
    for i, stem in enumerate(stems):
        head = "        if" if i == 0 else "        } else if"
        L.append("%s id == %d {" % (head, i))
        L.append("            sprite.set_data(base, %s_tile_count, %s_tiles)"
                 % (stem, stem))
    if stems:
        L.append("        }")
    L += ["    }",
          "",
          "    export COUNT, upload",
          "}",
          ""]
    return "\n".join(L)


def generate_emotes(root, studio=None):
    """Write `src/emotes.mos` for the project at `root`, or remove nothing and
    return None when it has no emote art."""
    if studio is None:
        from .rooms import _load_studio
        studio = _load_studio(root)
    stems = emote_sheets(studio)
    if not stems:
        return None
    path = os.path.join(root, "src", "emotes.mos")
    text = emit_emotes_mos(stems)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return path
