#!/usr/bin/env python3
"""Generate projects/parallax-spike/src/main.mos.

A hand-written proof of SCANLINE PARALLAX: one wide map streamed through
`engine.scrollpx` in three bands, each at its own speed, with a MARKER column
that lets a test read each band's scroll straight off the rendered frame.

The map is 64 tiles wide. Every cell is tile 1 except a marker column of tile 2
at logical column MARKER, repeated in all three bands' rows. At camera `camx`
band i's world x is `camx >> shift[i]`, so the marker draws at screen x
`MARKER*8 - (camx >> shift[i])` - three different places at the same instant,
which is exactly what parallax is and what a single-scroll background cannot do.
"""
import os

WCOLS = 64
ROWS = 18
#: (first row, rows, shift, marker column). The marker columns DIFFER per band
#: on purpose: a band at 1/16 speed barely moves, so a shared marker would sit
#: at the right screen edge for it while the full-speed band's had long gone
#: off the left. Picked so that at a mid camera all three are on screen at
#: once - which is the whole point of the picture.
BANDS = [(0, 6, 4, 5), (6, 6, 1, 20), (12, 6, 0, 30)]

HDR = '''-- main.mos -- GENERATED by projects/parallax-spike/assets/gen_main.py
-- SCANLINE PARALLAX proof: one wide map, three bands, three scroll rates.
--
-- `engine.scrollpx` keeps a column cursor PER BAND and fills only that band's
-- rows of the 32-column hardware ring at the band's own shifted offset, while
-- graphics.bkg's parallax verbs drive an LYC/STAT interrupt that writes each
-- band's SCX as the beam reaches it. Both halves are needed: the interrupt
-- alone repeats the same columns at a different offset, which is only right
-- while a band's whole range fits the 256 px tilemap.
--
-- Each band carries a MARKER column of tile 2 (%(markers)s), so at camera `camx`
-- band i draws its marker at screen x `col*8 - (camx >> shift)`. `verify.py`
-- reads those three positions off a real frame: three different scrolls in one
-- frame is something a single scroll register cannot produce.

module "parallax_spike" {
    import "platform.video"
    import "graphics.bkg"
    import "engine.scrollpx"

    const WCOLS: u16 = %(wcols)d
    const SPEED: u16 = 2
    const MAX_X: u16 = %(maxx)d        -- WCOLS*8 - 160, the right-edge clamp

    -- 3 tiles: 0 blank, 1 the field, 2 the marker column.
    const TILES: array[u8, 48] = [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
    ]

'''


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "main.mos")
    rows = [[1] * WCOLS for _ in range(ROWS)]
    for row0, n, _shift, mcol in BANDS:
        for r in range(row0, row0 + n):
            rows[r][mcol] = 2
    flat = [v for row in rows for v in row]

    L = [HDR % {"wcols": WCOLS, "maxx": WCOLS * 8 - 160,
                "markers": ", ".join("band %d at col %d" % (i, b[3])
                                     for i, b in enumerate(BANDS))}]
    L.append("    -- The wide map, ROW-MAJOR: MAP[r * WCOLS + c].")
    L.append("    const MAP: array[u8, %d] = [" % len(flat))
    for r in range(ROWS):
        line = ", ".join("0x%02X" % v for v in rows[r])
        L.append("        %s%s" % (line, "," if r < ROWS - 1 else ""))
    L.append("    ]")
    L.append("")
    L.append("    var camx: u16 = 0")
    L.append("")
    L.append("    -- engine.scrollpx's column source: fill buf[0..rows-1] with the")
    L.append("    -- band's rows of logical column `c`. The buffer always starts at 0")
    L.append("    -- (mosaik has no array slicing), so the band's first ROW is what")
    L.append("    -- selects the map cells, not where they land in the buffer.")
    L.append("    function gather(c: u16, row: u8, rows: u8) {")
    L.append("        var idx: u16 = row")
    L.append("        idx = idx * WCOLS")
    L.append("        idx = idx + c")
    L.append("        var r: u8 = 0")
    L.append("        while r < rows {")
    L.append("            scrollpx.buf[r] = MAP[idx]")
    L.append("            idx = idx + WCOLS")
    L.append("            r = r + 1")
    L.append("        }")
    L.append("    }")
    L.append("")
    L.append("    function main() {")
    L.append("        video.disable_lcd()")
    L.append("        bkg.set_data(0, 3, TILES)")
    for i, (row, rows_n, shift, _m) in enumerate(BANDS):
        L.append("        scrollpx.band(%d, %d, %d, %d)" % (i, row, rows_n, shift))
    L.append("        scrollpx.arm(%d)" % len(BANDS))
    L.append("        scrollpx.fill(WCOLS, gather)")
    L.append("        video.enable_lcd()")
    L.append("        loop {")
    L.append("            if camx < MAX_X {")
    L.append("                camx = camx + SPEED")
    L.append("            }")
    L.append("            scrollpx.update(camx, gather)")
    L.append("            video.wait_vblank()")
    L.append("        }")
    L.append("    }")
    L.append("")
    L.append("    export main")
    L.append("}")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", os.path.normpath(out))


if __name__ == "__main__":
    main()
