"""mosaik_vm.rooms.emit_prelude - the module header, imports, tuning consts, the
per-room residency tables and the collision probes.

One section of the generated `rooms` module. `emit(c, L)` appends its
lines to `L`, reading the derived world shape off the RoomsCtx `c`
(see rooms.context)."""
from .config import HOT_PIN, _SHMUP_DEFAULT_PACE, _dim_h, _dim_w, _meta_h, _meta_w, _wants_boxes


def emit(c, L):
    """Header, imports, consts, residency tables, probes, per-type ticks."""
    info = c.info
    use_player, playerless, has_objs, has_ent = c.use_player, c.playerless, c.has_objs, c.has_ent
    wide, parallax, roam, has_trig = c.wide, c.parallax, c.roam, c.has_trig
    has_doors, clips, dyn_oam, fade = c.has_doors, c.clips, c.dyn_oam, c.fade
    cgb_fade, res, PAL_FADE_GUARD, p = c.cgb_fade, c.res, c.PAL_FADE_GUARD, c.p
    ticks, uniform, has_col, pkinds = c.ticks, c.uniform, c.has_col, c.pkinds
    pboxes, _pk_box, cfocus, _cf_var = c.pboxes, c._pk_box, c.cfocus, c._cf_var
    _cf_x1, boffs, _bo_var, _bo_x0 = c._cf_x1, c.boffs, c._bo_var, c._bo_x0
    PARALLAX_GUARD, UI_REDRAW_GUARD, OBJ_TILE_CAP, SMSGG_OBJ_TILES = c.PARALLAX_GUARD, c.UI_REDRAW_GUARD, c.OBJ_TILE_CAP, c.SMSGG_OBJ_TILES
    SMSGG_TILE_CAP, emote = c.SMSGG_TILE_CAP, c.emote
    obj_top_fork = c.obj_top_fork

    L += ["-- GENERATED by MosaiK8 Studio (mosaik_vm) -- the WORLD wiring: room load,",
         "-- doors/triggers/entity slots, and the scene-type player dispatch. Only the",
         "-- scene types + packs this world USES are emitted/imported, so an unused",
         "-- handler is never referenced (and [build] shake_exports drops it). Player",
         "-- tuning comes from studio.toml [player] (edit in the studio, not here).",
         "",
         'module "rooms" {',
         '    import "scenes"',
         '    import "vm.core"']
    if use_player or playerless:
        L.append('    import "vm.player"')
    if has_objs:
        L.append('    import "vm.actor"')
    if has_ent:
        L.append('    import "vm.entity"')
    if wide:
        L.append('    import "engine.scroll"')
    if parallax:
        L.append('    import "engine.scrollpx"')
    if roam:
        L.append('    import "engine.scroll2d"')
    if has_trig:
        L.append('    import "vm.trigger"')
    if has_doors:
        L.append('    import "vm.door"')
    if info.get("uses_projectile"):
        L.append('    import "vm.projectile"')
    if info.get("uses_atan2"):
        L.append('    import "vm.trig"')      # the atan2() expression's pack
    if info.get("uses_save"):
        # the OPT-IN persistent-save pack; wired to vm.core below (set_save).
        # On a console with no battery it is a stub, so this same shell builds
        # everywhere and `save` is simply a no-op there.
        L.append('    import "vm.sram"')
    if emote:
        L += ['    import "vm.emote"', '    import "emotes"']
    if clips:
        L += ['    import "vm.canim"', '    import "clips"']
    if dyn_oam or info.get("kind_pal"):
        L.append('    import "graphics.sprite"')     # the room-load OAM sweep
    if info.get("has_menu"):
        L.append('    import "scripts"')
    # The COLOUR fade (see pal_fade below) needs the palette verbs too. A
    # coloured world already pulls the palette prelude in through scenes.mos,
    # so this import costs nothing beyond the one wrapper it enables.
    if (info.get("bkg4") or cgb_fade
            or (res and any((res.get("kslot") or {}).values()))):
        # ... or for the SMS/GG per-kind sprite palette, which rides the 2bpp
        # nibble map at sheet upload (see upload_kind). `any` because a map
        # of all-zero slots emits no call: slot 0 IS the default map.
        L.append('    import "graphics.palette"')
    if info.get("tile_pal"):
        L.append('    import "graphics.bkg"')     # bkg.set_attrs on the streamed path
    if fade:
        # the auto-fade rides vm.fx (the same 0..3 darkness LEVEL the FADE
        # opcode steps), so a scripted fade and this one cannot disagree
        L += ['    import "vm.fx"', '    import "platform.video"']
    elif info.get("uses_curtain") or info.get("dmg_palette") or c.fade_style:
        # ... and the OVERLAY CURTAIN, the authored DMG palette and the fade
        # DIRECTION live in the same pack, so a world with no auto-fade still
        # needs the import when a script raises one, the project authors its
        # own BGP/OBP, or it declares which way its scripted fades go.
        L.append('    import "vm.fx"')
    if info.get("letterbox") and not fade:
        # the letterbox view's video.set_view (an auto-fade imports it above)
        L.append('    import "platform.video"')
    if (info.get("glyph_text") or info.get("clear_outside")
            or c.overlay_cut):
        # ... or to blank the cells a small scene does not cover
        # (clear_outside), or to place the project's own OVERLAY CUT
        # (`[scenes] overlay_cut`): the scanline the window overlay stops at
        # is a text-layer verb, because the window IS the text layer's on the
        # GB family.
        L.append('    import "graphics.text"')
    if info.get("has_text") and not info.get("has_menu"):
        L.append('    import "scripts"')   # for the text_lines box-geometry seam
    L.append("")
    if fade:
        L += ["    -- auto-fade on room load (studio.toml [scenes] fade):",
              "    -- LCD frames held per darkness step, 3 steps black -> normal.",
              "    const FADE_HOLD: u8 = %d" % fade,
              ""]
    if cgb_fade:
        # THE COLOUR HALF OF THE FADE. vm.fx darkens BGP/OBP0/OBP1, and the
        # hardware IGNORES those three registers in CGB mode -- so on a Game
        # Boy Color the fade had never done anything in either direction, and
        # every transition was a hard cut. graphics.palette scales the LOADED
        # palettes instead (the reference engine's CGBFadeToBlackStep); a graceful no-op
        # on every console whose palettes are not scaled at runtime, which is
        # what keeps this target-neutral.
        #
        # It goes through vm.fx rather than being called from the ramps here,
        # so a SCRIPTED fade (the FADE opcode) drives the same path -- the two
        # cannot disagree about the level. vm.fx cannot import
        # graphics.palette itself: it is linked into EVERY VM8 game, and the
        # palette prelude is resident on every console that would then carry
        # it.
        #
        # Scoped to the CGB class by a MODULE-level fork (the same shape the
        # SMS/GG `redraw` uses): the DMG registers are real on every other GBDK
        # console, and emitting the wrapper anyway cost the SMS/Game Gear a
        # measured ~225 B of resident image -- an address-taken banked callback
        # plus its forwarding stub, spent on a verb that is a no-op there.
        L += ["    " + PAL_FADE_GUARD,
              "        -- the COLOUR fade vm.fx drives (see start): scale the",
              "        -- loaded palettes, since CGB mode IGNORES the DMG",
              "        -- palette registers vm.fx otherwise ramps.",
              "        function pal_fade(l: u8) {",
              "            palette.fade(l)",
              "        }",
              "    }",
              ""]

    if use_player:
        L += ["    -- player tuning (studio.toml [player])",
              "    const WALK: u8 = %d" % p["walk"],
              "    const RUN: u8 = %d" % p["run"],
              "    const JUMP: u8 = %d" % p["jump"],
              "    const GRAV: u8 = %d" % p["gravity"],
              "    const MAXFALL: u8 = %d" % p["max_fall"]]
        # The climb speed rides the same [player] block, emitted only for a
        # world that has a ladder to climb.
        if info.get("has_ladder_cells"):
            L.append("    const CLIMB: u8 = %d" % p["climb"])
        # The player's collision box IS the drawn rectangle (vm.player renders
        # the metasprite from the box's top-left), so with a PER-SCENE player
        # sprite the box has to follow it: a 16x32 platformer sprite over a
        # 16x16 box rests the BOX on the floor and hangs the sprite 16 px
        # THROUGH it - the character stands buried to the waist. load_room
        # sets these from the room's own player kind.
        if _pk_box:
            L += ["    var PW: u8 = %d" % p["width"],
                  "    var PH: u8 = %d" % p["height"]]
        else:
            L += ["    const PW: u8 = %d" % p["width"],
                  "    const PH: u8 = %d" % p["height"]]
        if boffs:
            # Where the collision box sits inside the sprite. The reference engine's
            # topdown player collides with the 16x8 FEET ROW of a 16x16
            # character, so the box starts 8 px down. Per scene TYPE.
            kind = "var" if _bo_var else "const"
            cols = [(1, "BOY", "PBOY")]
            if not _bo_x0:
                cols.insert(0, (0, "BOX", "PBOX"))
            for col, nm, _tbl in cols:
                L.append("    %s %s: u8 = %d" % (kind, nm, boffs[0][col]))
            if _bo_var:
                for col, _nm, tbl in cols:
                    L.append("    const %s: array[u8, %d] = [ %s ]"
                             % (tbl, len(boffs),
                                ", ".join(str(o[col]) for o in boffs)))
        if cfocus:
            # The camera FOCUS, the reference engine's fixed `pos + 8` rather than the
            # box centre. Per scene TYPE, since it is measured from the
            # sprite's top-left and the art differs.
            kind = "var" if _cf_var else "const"
            L.append("    %s CFX: u8 = %d"
                     % ("const" if _cf_x1 else kind, cfocus[0][0]))
            L.append("    %s CFY: u8 = %d" % (kind, cfocus[0][1]))
            if _cf_var:
                cols = [(1, "PCFY")]
                if not _cf_x1:
                    cols.insert(0, (0, "PCFX"))
                for col, tbl in cols:
                    L.append("    const %s: array[u8, %d] = [ %s ]"
                             % (tbl, len(cfocus),
                                ", ".join(str(f[col]) for f in cfocus)))
        kboxes = info.get("kind_boxes") or {}
        if _wants_boxes(info) and kboxes:
            # The per-KIND block box (studio.toml [hitbox.<kind>]): the reference engine's
            # authored sprite `bounds`, which is what it actually collides
            # against, not the drawn rectangle. Four u8 columns indexed by kind
            # id; an all-zero row is a kind that does not block (its `solid =
            # false`), so opting scenery out costs a table row instead of an
            # opcode in every one of its scripts.
            nk = max(1, int(info.get("nkinds") or 0))
            for col, tbl in ((0, "KBW"), (1, "KBH"), (2, "KBX"), (3, "KBY")):
                L.append("    const %s: array[u8, %d] = [ %s ]"
                         % (tbl, nk,
                            ", ".join(str(kboxes.get(k, (0, 0, 0, 0))[col])
                                      for k in range(nk))))
        L += ["    const PTILE: u8 = %d" % p["tile"],
              "    const SH_SPEED: u8 = %d" % p["shmup_speed"],
              # the shmup's DEFAULT scroll pace is a genre default, not a [player]
              # field; a scene retimes / pauses it with the shmup_scroll event.
              "    const SH_PACE: u8 = %d" % _SHMUP_DEFAULT_PACE,
              ""]

    if c.tsnap and not c._ts_all:
        # Which rooms snap the trigger hit test to the reference engine's 8 px topdown
        # grid (0 = pixel-exact). Per SCENE, because the reference engine's ADVENTURE
        # state runs the same test at pixel positions and both convert to our
        # `topdown`. When every scene agrees, load_room passes the one literal
        # and this table is not emitted at all.
        L.append("    const TSNAP: array[u8, %d] = [ %s ]"
                 % (len(c.tsnap), ", ".join(str(v) for v in c.tsnap)))
    if c.tforce and not c._tf_all:
        # Which rooms re-fire the standing trigger on a button's rising edge
        # (the reference engine's PLATFORM INPUT_PLATFORM_FORCE_TRIGGER scan; the value
        # is the portable BTN_* id, 255 = off). When every scene agrees,
        # load_room passes the one literal and this table is not emitted.
        L.append("    const TFORCE: array[u8, %d] = [ %s ]"
                 % (len(c.tforce), ", ".join(str(v) for v in c.tforce)))
    L += ["    -- the boot scene ([world] start_scene, resolved to its index)",
          "    const START: u8 = %d" % int(info.get("start", 0)),
          "",
          # No `= 0`: a module-level initializer rides the boot INITIALIZER,
          # which is RESIDENT (bank 0) even when this module banks. BSS is
          # zeroed by the C runtime, so this is the same semantics for free.
          "    var room: u8",
          ""]

    if info.get("on_load_hook"):
        # A shell callback run at the END of every room load. The room-load
        # path itself writes hardware the shell may care about (measured: the
        # GB text/font init resets OBP0/OBP1 to the identity palette during
        # the first load, one time, AFTER main() has run), so a shell that
        # owns such state needs the last word and cannot get it from main().
        # Opt-in (`studio.toml [sprites] on_load_hook`), byte-identical off.
        L += ["    -- Shell hook run at the end of every room load.",
              "    var g_on_load: function()",
              "    var g_has_on_load: u8",
              "    function set_on_load(cb: function()) {",
              "        g_on_load = cb",
              "        g_has_on_load = 1",
              "    }",
              ""]
    if res:
        # Per-room sprite residency: KT[kind] = the kind's sheet size in
        # tiles, kvb[kind] = the VRAM base its sheet was uploaded at THIS room
        # (255 = not resident). upload_kind is a per-kind set_data dispatch;
        # its reads are what co-locate every sheet into this module's ROM
        # bank under [build] code_banks.
        nk = res["nk"]
        L += ["    -- per-room sprite residency: only the kinds THIS room",
              "    -- places are uploaded (the world's art is unbounded; a",
              "    -- single room must fit the 128 exclusive GB OBJ tiles).",
              "    const NKIND: u8 = %d" % nk]
        kt_line = "const KT: array[u8, %d] = [ %s ]"
        if res.get("kt_smsgg"):
            # SMS/GG: a flip_left kind's sheet also carries its soft-flip
            # MIRROR tiles, which the build appends to the sheet's own data
            # there (mosaik8_build._bake_soft_flip), so the kind is bigger.
            L += ["    -- SMS/GG: + each flip_left kind's mirror tiles (no",
                  "    -- hardware sprite flip there; the build appends them",
                  "    -- to the kind's own sheet)",
                  "    " + UI_REDRAW_GUARD,
                  "        " + kt_line % (nk, ", ".join(
                      str(t) for t in res["kt_smsgg"])),
                  "    } else {",
                  "        " + kt_line % (nk, ", ".join(str(t) for t in res["kt"])),
                  "    }"]
        else:
            L.append("    " + kt_line % (nk, ", ".join(str(t) for t in res["kt"])))
        L.append("    var kvb: array[u8, %d]" % nk)
        if res.get("spr_need"):
            # Read by the compiler's cc65 sprite budget (gen_budgets) to size
            # the Lynx / PC Engine tile table + slot pool for the busiest room.
            L += ["    -- the busiest room's sprite need (Lynx / PC Engine",
                  "    -- tile table + slot pool, read by the build)",
                  "    const SPR_TILE_NEED: u16 = %d" % res["spr_need"][0],
                  "    const SPR_SLOT_NEED: u8 = %d" % res["spr_need"][1]]
        if pkinds:
            L += ["    -- the player's SPRITE kind per scene (the reference engine keys",
                  "    -- its default player sprite by scene TYPE: a platform",
                  "    -- room's player is taller art with its own clips). The",
                  "    -- spawn MARKER stays scenes.KIND_PLAYER.",
                  "    const PKIND: array[u8, %d] = [ %s ]"
                  % (len(pkinds), ", ".join(str(k) for k in pkinds))]
            if pboxes:
                L += ["    -- ... and its COLLISION box, which is the drawn",
                      "    -- rect down to the FEET (a frame pads up to whole",
                      "    -- 8 px tiles; counting that padding floats the",
                      "    -- character above the floor).",
                      "    const PBW: array[u8, %d] = [ %s ]"
                      % (len(pboxes), ", ".join(str(b[0]) for b in pboxes)),
                      "    const PBH: array[u8, %d] = [ %s ]"
                      % (len(pboxes), ", ".join(str(b[1]) for b in pboxes))]
        L += ["",
              "    function upload_kind(k: u8, vb: u8) {"]
        first = True
        # [kind_palettes] on SMS/GG: those consoles have no per-sprite palette
        # select, so a kind's sprite palette SLOT has to ride its sheet
        # UPLOAD. `palette.set_2bpp` is the port's own nibble map - which four
        # CRAM entries a 2bpp tile's pixel values expand onto - so the
        # ORDINARY sprite.set_data below lands the sheet on slot*4.., and the
        # map is restored afterwards so a later plain upload is unaffected.
        # Pixel 0 keeps mapping to 0 (the VDP's transparent), which is the
        # same rule the GB model already follows. An inline no-op on every
        # other console, and a world with no kind palettes emits the plain
        # upload it always did (byte-identical).
        kslot = res.get("kslot") or {}
        _MAP2BPP = (0x3210, 0x7650, 0xBA90, 0xFED0)
        for kid in sorted(res["stems"]):
            stem = res["stems"][kid]
            kw = "if" if first else "} else if"
            L.append("        %s k == %d {" % (kw, kid))
            slot = kslot.get(kid, 0) & 3
            if kslot and slot:
                L.append("            " + UI_REDRAW_GUARD)
                L.append("                palette.set_2bpp(0x%04X)"
                         % _MAP2BPP[slot])
                L.append("                sprite.set_data(vb, %s_tile_count, "
                         "%s_tiles)" % (stem, stem))
                L.append("                palette.set_2bpp(0x%04X)"
                         % _MAP2BPP[0])
                L.append("            } else {")
                L.append("                sprite.set_data(vb, %s_tile_count, "
                         "%s_tiles)" % (stem, stem))
                L.append("            }")
            else:
                L.append("            sprite.set_data(vb, %s_tile_count, %s_tiles)"
                         % (stem, stem))
            first = False
        if not first:
            L.append("        }")
        L += ["    }", ""]
        variants = info.get("variants")
        if variants:
            # world.toml [kind_variants]: a placed placeholder kind becomes
            # kinds[heap var] at load (one room serves every variant; only
            # the chosen sheet is uploaded). Out of range keeps the kind.
            L += ["    -- [kind_variants]: the kind a placed PLACEHOLDER",
                  "    -- becomes, picked by a heap variable at room load."]
            for ph, (_var, kids) in sorted(variants.items()):
                L.append("    const VK%d: array[u8, %d] = [ %s ]"
                         % (ph, len(kids), ", ".join(str(k) for k in kids)))
            L.append("    function variant_kind(k: u8) -> u8 {")
            for ph, (var, kids) in sorted(variants.items()):
                L += ["        if k == %d {" % ph,
                      "            var v: i16 = core.var_get(%d)" % var,
                      "            if v >= 0 and v < %d {" % len(kids),
                      "                var vi: u8 = v",
                      "                return VK%d[vi]" % ph,
                      "            }",
                      "        }"]
            L += ["        return k",
                  "    }", ""]

    # solid_at: report whether world pixel (x,y) collides in the CURRENT room.
    # Two collision models (a world uses one): a PAINTED per-cell layer
    # (scenes.collision_at, has_col) OR a TILE-BASED solid set ([collision]
    # solid, has_solid -> scenes.is_solid(map_tile)). A world with neither gets a
    # constant false (the player setters still take the callback).
    has_solid = info.get("has_solid_tiles", False)
    # `cell_at` is shared by every probe that needs the cell's TYPE rather than
    # a yes/no - the one-way platform and the ladder both do.
    _typed = info.get("has_platform_cells") or info.get("has_ladder_cells")
    if has_col and _typed:
        # TWO probes read the same cell (solid + one-way platform). Reading a
        # STREAMED asset pins a function resident (its seam read lowers to
        # SWITCH_ROM, which cannot execute from a switchable bank) and each one
        # costs a bank-neutrality wrapper - so read the cell ONCE here and let
        # both probes be plain comparisons that bank with the rest of `rooms`.
        L += ["    -- The painted collision CELL at world pixel (x,y). The one",
              "    -- seam read, so it is the only probe pinned resident.",
              "    -- OUTSIDE the scene is SOLID (reference-engine parity: its",
              "    -- collision.c returns COLLISION_ALL out of bounds). Without",
              "    -- the guard the unbounded idx read past the room's window -",
              "    -- under paint_table that is ANOTHER room's bytes, so a",
              "    -- player falling into an open-bottom pit landed on phantom",
              "    -- collision below the screen and was stranded for good; on",
              "    -- solid-OOB it lands on the invisible floor one row under",
              "    -- the scene, grounded, and can jump back into a pit shaft",
              "    -- whose bottom-row trigger respawns it - the reference",
              "    -- ROM's own recovery route.",
              "    " + HOT_PIN + "function cell_at(x: u16, y: u16) -> u8 {",
              "        var cx: u16 = x / 8",
              "        var cy: u16 = y / 8"]
        if uniform:
            L += ["        if cx >= scenes.MAP_W or cy >= scenes.MAP_H {",
                  "            return scenes.COLLIDE_SOLID",
                  "        }",
                  "        var idx: u16 = cy * scenes.MAP_W + cx"]
        else:
            L += ["        var w16: u16 = scenes.SCENE_W[room]",
                  "        if cx >= w16 or cy >= scenes.SCENE_H[room] {",
                  "            return scenes.COLLIDE_SOLID",
                  "        }",
                  "        var idx: u16 = cy * w16 + cx"]
        L += ["        return scenes.collision_at(room, idx)",
              "    }",
              "",
              "    -- Is world pixel (x,y) solid in the current room?",
              "    " + HOT_PIN + "function solid_at(x: u16, y: u16) -> bool {",
              "        return cell_at(x, y) == scenes.COLLIDE_SOLID",
              "    }",
              ""]
    else:
        L += ["    -- Is world pixel (x,y) solid in the current room?",
              "    -- OUTSIDE the scene is SOLID (reference-engine parity - see the",
              "    -- cell_at note; the unbounded read was phantom collision).",
              "    " + HOT_PIN + "function solid_at(x: u16, y: u16) -> bool {"]
        if has_col or has_solid:
            L += ["        var cx: u16 = x / 8",
                  "        var cy: u16 = y / 8"]
            if uniform:
                L += ["        if cx >= scenes.MAP_W or cy >= scenes.MAP_H {",
                      "            return true",
                      "        }",
                      "        var idx: u16 = cy * scenes.MAP_W + cx"]
            else:
                L += ["        var w16: u16 = scenes.SCENE_W[room]",
                      "        if cx >= w16 or cy >= scenes.SCENE_H[room] {",
                      "            return true",
                      "        }",
                      "        var idx: u16 = cy * w16 + cx"]
            if has_col:
                L.append("        return scenes.collision_at(room, idx) == scenes.COLLIDE_SOLID")
            else:
                L.append("        return scenes.is_solid(scenes.map_tile(room, idx))")
        else:
            L.append("        return false")
        L += ["    }", ""]

    # platform_at: the ONE-WAY platform probe. A painted collision layer can
    # hold cell type 2, which is NOT solid (you walk and jump through it) but
    # DOES stop a fall - so it cannot ride solid_at, whose answer is the same
    # in all four directions. Without this the player fell straight through
    # every one-way platform: solid_at tests `== COLLIDE_SOLID`, so a type-2
    # cell simply was not there. Emitted only when a scene paints one.
    if info.get("has_platform_cells"):
        L += ["    -- Is world pixel (x,y) a ONE-WAY platform cell?",
              "    " + HOT_PIN + "function platform_at(x: u16, y: u16) -> bool {",
              "        return cell_at(x, y) == scenes.COLLIDE_PLATFORM",
              "    }", ""]
    # ...and the LADDER probe, the same shape again. A ladder is not solid and
    # does not stop a fall, so like the platform cell it cannot ride solid_at
    # (which tests `== COLLIDE_SOLID`): a type-3 cell simply is not there as
    # far as walls and gravity are concerned, which is exactly right - it is
    # the climb that reads it.
    if info.get("has_ladder_cells"):
        L += ["    -- Is world pixel (x,y) a climbable LADDER cell?",
              "    " + HOT_PIN + "function ladder_at(x: u16, y: u16) -> bool {",
              "        return cell_at(x, y) == scenes.COLLIDE_LADDER",
              "    }", ""]

    # PER-SCENE background tile animation: `scenes.anim_tick_at` needs the room,
    # and this shell is the only thing that knows it. `core.set_bkg_anim` takes
    # a no-argument callback (widening that seam would cost vm.core, which is
    # resident on the GB family), so the room is supplied here.
    if info.get("has_scene_bkg_anim") and not info.get("has_bkg_anim"):
        L += ["    -- The room's animated background tiles, ticked once a frame.",
              "    function bkg_anim() {",
              "        scenes.anim_tick_at(room)",
              "    }", ""]

    # per-frame tick per used player type: native move + the pack updates.
    post = []
    # ONE box answers triggers, doors and walls, because that is the reference engine's
    # model: an actor has a single `bounds` and everything tests it. An import
    # brings those bounds in AS the collision box (with the art offset above
    # it), so nothing here needs to know about the difference.
    _bpos = ("player.box_x(), player.box_y()" if boffs
             else "player.pos_x(), player.pos_y()")
    if has_doors:
        post.append("door.update(%s, PW, PH)" % _bpos)
    if has_trig:
        post.append("trigger.update(%s, PW, PH)" % _bpos)
    if has_ent:
        post.append("entity.update()")
    upd = {"topdown": "player.update()",
           "platform": "player.update_platform()",
           "shmup": "player.update_shmup()"}
    for t in ticks:
        if t == "pointnclick":
            L += _pnc_tick(has_trig, has_ent, has_doors, _bpos)
            continue
        L.append("    function tick_%s() {" % t)
        L.append("        " + upd[t])
        L += ["        " + s for s in post]
        L += ["    }", ""]

    if wide or roam:
        L += ["    const BKG_PX: u16 = 256      -- the 32-tile hardware background",
              ""]
    if info.get("smsgg_rows"):
        # HEIGHT is not 256 px everywhere: the SMS/Game Gear name table is
        # 32x28 (224 px) and their vertical scroll register wraps there, so a
        # room of 29..32 rows must stream through engine.scroll2d instead of
        # being painted resident. Emitted only for a project that targets one
        # of those consoles, so every other rooms.mos is byte-identical.
        L += ["    if platform == \"sms\" or platform == \"gamegear\" {",
              "        const BKG_ROWS: u8 = 28",
              "        const BKG_PY: u16 = 224",
              "    } else {",
              "        const BKG_ROWS: u8 = 32",
              "        const BKG_PY: u16 = 256",
              "    }",
              ""]
    # ...and whenever anything NAMES it. The per-room OAM packing is the main
    # reader (dyn_oam), but `projectile.set_top` takes the same ceiling and is
    # emitted for ANY project with a projectile pool - vm-combat has shots
    # without per-kind sizes, so it named a constant that was never declared
    # and failed to compile the moment its stale rooms.mos was regenerated.
    # Emit the declaration wherever a reference can be emitted.
    if dyn_oam or info.get("uses_projectile"):
        # The console's HARDWARE SPRITE COUNT, which bounds both the per-room
        # OAM packing and the room-load sweep. It is 40 on the Game Boy family
        # and the cc65 consoles but **64 on the SMS, Game Gear and NES** - the
        # engine's own `GBS_META_SLOTS` already says so, and hardcoding the GB
        # number here silently parked the tail of a crowded room at NO_OAM on a
        # console with room to spare: a small house room of the reference-engine sample needs
        # 48 objects, so both its signs simply did not draw on the SMS
        # while the same room was complete on the GB. Keep the two in lockstep.
        L += ["    if platform == \"sms\" or platform == \"gamegear\" or platform == \"nes\" {",
              "        const OAM_SLOTS: u8 = 64"]
        need = (res or {}).get("spr_need")
        if need and need[1] > 40:
            # The PC Engine sizes its slot pool from the busiest room
            # (SPR_SLOT_NEED, the engine's own formula: up to the SATB's 64),
            # so the packing must count to the same number or it parks a big
            # fan (a 56-tile battle foe) at NO_OAM.
            L += ["    } else if platform == \"pce\" {",
                  "        const OAM_SLOTS: u8 = %d" % min(64, need[1])]
        L += ["    } else {",
              "        const OAM_SLOTS: u8 = 40",
              "    }",
              ""]
    if emote:
        # The emote bubble's reserved corner of both tables - and the two
        # halves point OPPOSITE ways, which is the whole subtlety.
        #
        # TILES come off the TOP (EMOTE_TILE, below): a tile index carries no
        # priority, so the only thing that matters is that the per-room VRAM
        # allocator, which packs upward from 0, never reaches it.
        #
        # OBJECTS come off the BOTTOM, because on the GB family an object's
        # OAM INDEX *is* its priority - lower draws on top. The bubble used to
        # take the last four objects, which put it BEHIND every actor: talking
        # to the RPG check conversion's Missing Cat drew the player's bubble at the cat's
        # own position (the player stands directly below it) and the cat, at a
        # much lower index, covered it (RPG check bug 6; measured emote 36/37
        # against cat 6/7). The reference engine draws the emote FIRST in `actors_render`
        # - before the player, before the actor walk, into an
        # `allocated_hardware_sprites` that restarts at 0 each frame - so its
        # bubble owns the lowest indices and covers everything. Ours reserves
        # them statically for the same effect: the bubble at 0, the player at
        # EMOTE_FAN, actors above that, and the ceiling is the whole table.
        #
        # EMOTE_FAN is always FOUR, even in 8x16 OBJ mode where the fan is
        # two: rooms.mos is target-neutral and obj_8x16 is a GB-family fork,
        # so a project built for both would need two different numbers here.
        # Two spare OAM objects is the cheap way out.
        L += ["    -- The emote bubble's reserved OAM fan + VRAM tiles (vm.emote",
              "    -- draws ONE 2x2 bubble at a time, as the reference engine does).",
              "    -- OBJECTS from the BOTTOM: an OAM index IS the draw priority on",
              "    -- the GB family (lower = on top), and the reference engine renders the",
              "    -- emote FIRST, so the bubble has to own the lowest objects or",
              "    -- it hides behind the very actor it belongs to. TILES still",
              "    -- come off the TOP (EMOTE_TILE) - a tile index has no",
              "    -- priority, it just has to stay clear of the upward packer.",
              "    -- Always FOUR objects, even in 8x16 OBJ mode where the fan is",
              "    -- two: rooms.mos is target-neutral and obj_8x16 is a GB-family",
              "    -- fork, so a project built for both would need two different",
              "    -- numbers here. Two spare OAM objects is the cheap way out.",
              "    const EMOTE_OAM: u8 = 0",
              "    const EMOTE_FAN: u8 = 4"]
    if obj_top_fork:
        # THE SPRITE-TILE CEILING IS PER CONSOLE, and that is not cosmetic:
        # a room past it has its last kinds refused, and a refused kind is
        # HIDDEN (a_vis) - which is what made a long walk-in room's four
        # health hearts vanish on the SMS. The GB is capped at 128 because
        # tile 128+ collides with background data in 0x8800 mode; SMS/GG
        # sprite patterns are a SEPARATE 192-slot VDP area (tile ids
        # 256..447), so they get all of it, less the emote's four at the top.
        L += ["    -- The sprite-tile ceiling the per-room VRAM allocator packs",
              "    -- up to, per console. The GB family stops at its 128",
              "    -- EXCLUSIVE OBJ tiles (128+ collides with background data in",
              "    -- 0x8800 mode); SMS/GG sprite patterns are a separate",
              "    -- 192-slot VDP area (tile ids 256..447), so they get all of",
              "    -- it. An emote's four come off the TOP of whichever table,",
              "    -- so the allocators - which pack upward from 0 - never reach",
              "    -- them.",
              '    if platform == "sms" or platform == "gamegear" {']
        if emote:
            L.append("        const EMOTE_TILE: u8 = %d" % (SMSGG_OBJ_TILES - 4))
        L += ["        const OBJ_TILE_TOP: u16 = %d" % SMSGG_TILE_CAP,
              "    } else {"]
        if emote:
            L.append("        const EMOTE_TILE: u8 = %d" % OBJ_TILE_CAP)
        L += ["        const OBJ_TILE_TOP: u16 = %d" % OBJ_TILE_CAP,
              "    }"]
    if emote or obj_top_fork:
        L.append("")
    if wide:
        # The column-stream seam for WIDE rooms. `gather(c)` fills one map
        # column into engine.scroll's buffer, `stream(camx)` is what
        # vm.player calls each frame once registered with set_scroll. Both
        # read the CURRENT room, so one pair serves every wide room.
        L += ["    -- Column streaming for rooms wider than the hardware",
              "    -- background: gather() fills one map column, stream() is",
              "    -- the per-frame seam vm.player calls (set_scroll).",
              "    -- A wide room's rows must fit the 32-row tilemap (only",
              "    -- COLUMNS stream); generate_rooms refuses taller rooms.",
              "    function srows(rm: u8) -> u8 {",
              "        var r: u16 = %s" % _dim_h("rm", uniform),
              "        var r8: u8 = r",
              "        return r8",
              "    }",
              "",
              "    -- The map index WALKS down the column (`idx += w`) instead",
              "    -- of being recomputed as `r * w + c` per row: that product",
              "    -- is a 16x16 SOFTWARE MULTIPLY on sm83/6502, ~512 cycles,",
              "    -- and a column is 18-32 of them. Measured on the reference-engine sample conversion",
              "    -- (GBC, walking a wide room): 5.3 map reads a frame, and",
              "    -- __mulint went from 16.4 calls a frame to 11.1.",
              "    function gather(c: u16) {",
              "        var rows: u16 = %s" % _dim_h("room", uniform),
              "        var w: u16 = %s" % _dim_w("room", uniform),
              "        var idx: u16 = c",
              "        var r: u16 = 0",
              "        while r < rows {"]
        # One shape for every world: read the map through the (pinned) seam
        # accessor directly. A roam world also has `tile_at`, but calling it
        # here would re-do the multiply AND route the palette through
        # scroll2d.apen as a side effect; tile_at stays for scroll2d's own
        # per-tile callback, which has no column to walk.
        if info.get("tile_pal"):
            L += ["            var t: u8 = scenes.map_tile(room, idx)",
                  "            scroll.buf[r] = t",
                  "            scroll.abuf[r] = scenes.tile_pal(room, t)"]
        else:
            L += ["            scroll.buf[r] = scenes.map_tile(room, idx)"]
        L += ["            idx += w",
              "            r += 1",
              "        }",
              "    }",
              "",
              "    function stream(camx: u16) {",
              "        scroll.update(camx, gather)",
              "    }",
              ""]
    if parallax:
        # The PARALLAX twin of the pair above. Two differences, both forced:
        # the callback takes the band's ROW RANGE (each band fills only its own
        # rows, from buf[0] - mosaik has no array slicing), and the vertical
        # scroll is PUBLISHED rather than written, because the scanline
        # interrupt owns SCX/SCY once bands are armed and a direct bkg.move
        # would be overwritten on the next line.
        #
        # The whole block is inside a MODULE-LEVEL platform fork, and it has to
        # be a `platform` fork rather than a runtime test: a per-console const
        # would leave the REFERENCES to these functions in the C, tree-shaking
        # reads a reference as live, and nothing dead-strips inside a TU - so
        # the bodies (and engine.scrollpx with them) would be resident image on
        # a console that can never run them.
        PX = []
        PX += ["    -- Column streaming for a wide room with PARALLAX BANDS.",
              "    -- Each band keeps its own cursor and fills its own rows at",
              "    -- its own shifted offset (engine.scrollpx), while an",
              "    -- LYC/STAT interrupt writes each band's SCX as the beam",
              "    -- reaches it. gatherpx() is the per-BAND column source.",
              "    function gatherpx(c: u16, row: u8, rows: u8) {",
              "        var w: u16 = %s" % _dim_w("room", uniform),
              "        var idx: u16 = row",
              "        idx = idx * w",
              "        idx = idx + c",
              "        var r: u8 = 0",
              "        while r < rows {"]
        if info.get("tile_pal"):
            PX += ["            var t: u8 = scenes.map_tile(room, idx)",
                  "            scrollpx.buf[r] = t",
                  "            scrollpx.abuf[r] = scenes.tile_pal(room, t)"]
        else:
            PX += ["            scrollpx.buf[r] = scenes.map_tile(room, idx)"]
        PX += ["            idx += w",
              "            r += 1",
              "        }",
              "    }",
              "",
              "    -- Declare room `rm`'s bands to engine.scrollpx and arm the",
              "    -- interrupt. Called from the room load; a room with no",
              "    -- bands calls arm(0) instead, which is what stops the",
              "    -- PREVIOUS room's bands carrying into it.",
              "    function arm_parallax(rm: u8) {",
              "        var n: u8 = scenes.px_count(rm)",
              "        var i: u8 = 0",
              "        while i < n {",
              "            scrollpx.band(i, scenes.px_row(rm, i), "
              "scenes.px_rows(rm, i), scenes.px_shift(rm, i))",
              "            i = i + 1",
              "        }",
              "        scrollpx.arm(n)",
              "    }",
              "",
              "    function streampx(camx: u16) {",
              "        -- The LAST band carries the vertical scroll (the upper",
              "        -- ones are pinned to 0, as the reference engine pins them), and the",
              "        -- interrupt reads it from here. vm.player publishes the",
              "        -- wide camera's y BEFORE calling this seam, so it is",
              "        -- this frame's value, not last frame's.",
              "        var cy: u16 = player.cam_y()",
              "        var cy8: u8 = cy",
              "        scrollpx.voff = cy8",
              "        -- The screen shake is an OFFSET on the publish, not a",
              "        -- scroll write: while bands are armed they own SCX/SCY",
              "        -- and a bkg.move from the game loop stands down. This",
              "        -- is the seam that carries vm.player's offset into the",
              "        -- band shadow (engine.scrollpx cannot read a player).",
              "        scrollpx.sox = player.shake_ox()",
              "        scrollpx.soy = player.shake_oy()",
              "        scrollpx.update(camx, gatherpx)",
              "    }",
              ""]
        if roam:
            # The ROAM seam takes the camera's y as an argument, so this twin
            # needs no cam_y() read at all. Both exist because vm.player calls
            # exactly one of them, decided by the handler the room set up.
            PX += ["    -- The ROAM counterpart: same bands, and the camera y",
                  "    -- arrives as an argument. Bands stream COLUMNS only,",
                  "    -- so the room-load fork takes this path only for a",
                  "    -- room no taller than the background.",
                  "    function stream2px(camx: u16, camy: u16) {",
                  "        var cy8: u8 = camy",
                  "        scrollpx.voff = cy8",
                  "        scrollpx.sox = player.shake_ox()",
                  "        scrollpx.soy = player.shake_oy()",
                  "        scrollpx.update(camx, gatherpx)",
                  "    }",
                  ""]
        L.append("    " + PARALLAX_GUARD)
        L += [("    " + ln) if ln else "" for ln in PX]
        L += ["    }", ""]

    if roam:
        # ROAM (a wide AND/OR tall TOPDOWN room): the 32x32 tilemap is a
        # sliding window over the whole level and engine.scroll2d writes only
        # the column/row the camera just crossed - the reference engine's own model. The
        # source is a per-TILE callback so the streamer needs no map layout
        # knowledge; it reads the CURRENT room, so one pair serves every roam
        # room in the world.
        L += ["    -- 2D streaming for a room past the hardware background on",
              "    -- either axis: tile_at() is the streamer's per-tile source,",
              "    -- stream2() the per-frame seam vm.player calls.",
              "    function tile_at(c: u16, r: u16) -> u8 {",
              "        var w: u16 = %s" % _dim_w("room", uniform),
              "        var idx: u16 = r * w + c"]
        if info.get("tile_pal"):
            # The COLOUR side channel: scroll2d writes apen[0] beside the tile
            # (a callback returns one value), so the streamed room is coloured
            # by the same pass that streams it.
            L += ["        var t: u8 = scenes.map_tile(room, idx)",
                  "        scroll2d.apen[0] = scenes.tile_pal(room, t)",
                  "        return t"]
        else:
            L += ["        return scenes.map_tile(room, idx)"]
        L += ["    }",
              "",
              "    function stream2(camx: u16, camy: u16) {",
              "        scroll2d.update2d(camx, camy, tile_at)",
              "    }",
              ""]

    if c.oam_wake and (info.get("kind_tpal") or info.get("kind_pal")):
        # SPRITE SLOTS ON WAKE + a coloured kind: the range an actor wakes
        # into is coloured THEN (a static layout paints it once at load), so
        # vm.actor calls back here with the new base and the slot, and the
        # slot's kind is remembered from the room load.
        L += ["    var okind: array[u8, VM_ACTOR_POOL]",
              "",
              "    function paint_slot(b: u8, i: u8) {"]
        if info.get("kind_tpal"):
            L += ["        scenes.paint_actor(b, okind[i], %s, %s)"
                  % (_meta_w(info, "okind[i]"), _meta_h(info, "okind[i]"))]
        else:
            L += ["        sprite.set_palette(b, scenes.kind_pal_at(okind[i]))"]
        L += ["    }", ""]

    # load_room -- the ONE room-load path (also the core.set_change callback).


def _pnc_tick(has_trig, has_ent, has_doors, bpos):
    """The POINT-AND-CLICK per-frame tick (W7j), which is NOT the topdown one
    with another move in it.

    The reference VM's `src/states/pointnclick.c`'s update, composed here because the two
    things it does beyond moving - pick the hover pose, and run what the cursor
    is over on A - read the trigger table and the actor list, which vm.player
    cannot see. Three differences from tick_topdown, each from the reference:

    * NO AUTOMATIC TRIGGER SCAN. It calls `trigger_at_intersection` (a pure
      query) and never `trigger_activate_at_intersection`, so a rect fires only
      when A is pressed over it. `trigger.update(...)` is deliberately absent.
    * THE HOVER POSE. `ANIM_CURSOR` / `ANIM_CURSOR_HOVER` are engine animations
      0 and 1, which our clip tables reach as FACINGS 0 (down) and 3 (right) -
      that is what `animationMapBySpriteType` + `toEngineOrder` map them to for
      BOTH a `cursor` sprite (authored animations 0 and 1) and an ordinary
      multi-direction one (idle down and idle right). vm.canim pins the clip
      STATE, so only the facing is published here.
    * A INTERACTS WITH THE OVERLAP, actor first and then trigger, never with a
      facing probe. The actor half is `entity.update()` itself, in the cursor
      mode the dispatch arm switched on; the trigger half is below it, and it
      is skipped when an actor took the press (the reference's `else if`).

    A DOOR still runs its contact scan: `[[door]]` is our own verb and has no
    counterpart in the reference's model (the reference engine spells a door as a trigger
    whose script changes scene, which here fires on the click). A hand-authored
    point-and-click room that places one means it.
    """
    L = ["    function tick_pointnclick() {",
         "        player.update_pointnclick()"]
    L.append("        var ah: u8 = 0          -- an actor is under the cursor")
    L.append("        var ct: u8 = 255        -- ...and which trigger is")
    if has_ent:
        L.append("        ah = entity.probe()")
    if has_trig:
        L.append("        ct = trigger.hit_script(%s, PW, PH)" % bpos)
    L += ["        if ah == 1 or ct != 255 {",
          "            player.set_face(3)     -- ANIM_CURSOR_HOVER",
          "        } else {",
          "            player.set_face(0)     -- ANIM_CURSOR",
          "        }"]
    if has_doors:
        L.append("        door.update(%s, PW, PH)" % bpos)
    if has_ent:
        L.append("        entity.update()")
    if has_trig:
        L += ["        if ah == 0 and ct != 255 {",
              "            if core.interact_pressed() == 1 {",
              "                trigger.interact(ct)",
              "            }",
              "        }"]
    L += ["    }", ""]
    return L
