#!/usr/bin/env python3
"""Generate the wide-scroll spike's main.mos (Stage 0 of the large-levels-u16 plan).

Bakes a 64-tile-wide logical map + the column-streaming loop into one self-contained
mosaik program. The map is mostly "ground" (tile 1) with two distinctive MARKER
columns well past the 256 px / 32-tile wrap -- column 40 (tile 2) and column 55
(tile 3) -- so a headless run can prove the far columns reach the hardware tilemap by
reading the BG map at the recycled hardware columns (40 % 32 = 8, 55 % 32 = 23).

Run:  python projects/wide-scroll-spike/assets/gen_main.py
"""
import os

WCOLS = 64      # logical map width in tiles (512 px -- past the 256 px wrap)
VROWS = 18      # visible rows (144 px = the GB screen height; no vertical scroll)
HW = 32         # hardware tilemap width in tiles
MARKER_A_COL = 40   # a marker column past the wrap -> hardware col 40 % 32 = 8
MARKER_B_COL = 55   # a second marker -> hardware col 55 % 32 = 23

# 4 tiles, GB 2bpp (16 bytes each): 0 blank, 1 ground (colour 1), 2 marker-A
# (colour 3, solid), 3 marker-B (colour 2). Distinct tile INDICES are what the proof
# reads from the BG map; the pixels just make it legible on screen.
TILES = (
    [0x00] * 16 +                      # 0 blank
    [0xFF, 0x00] * 8 +                 # 1 ground  -> colour 1
    [0xFF, 0xFF] * 8 +                 # 2 marker-A -> colour 3
    [0x00, 0xFF] * 8                   # 3 marker-B -> colour 2
)


def cell(r, c):
    if c == MARKER_A_COL:
        return 2
    if c == MARKER_B_COL:
        return 3
    return 1


def _fmt(vals, per_line=16):
    out, n = [], len(vals)
    for i in range(0, n, per_line):
        out.append("        " + ", ".join("0x%02X" % v for v in vals[i:i + per_line]))
    return ",\n".join(out)


def main():
    flat = [cell(r, c) for r in range(VROWS) for c in range(WCOLS)]
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "..", "src", "main.mos")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    src = '''-- main.mos -- GENERATED by projects/wide-scroll-spike/assets/gen_main.py
-- Stage 1 of the large-levels-u16 plan: drive COLUMN-STREAMING of a wide logical map
-- through the reusable `engine.scroll` primitive (proven across consoles). A u16
-- camera pans past the 256 px wrap; engine.scroll writes each revealed column into
-- the recycled hardware column and sets the hardware scroll.

module "wide_scroll" {
    import "platform.video"
    import "platform.input"
    import "graphics.bkg"
    import "graphics.palette"
    import "engine.scroll"

    const WCOLS: u16 = %(wcols)d        -- logical map width in tiles (512 px)
    const VROWS: u8 = %(vrows)d         -- visible rows (no vertical scroll)
    const SPEED: u16 = 2
    const STOP_X: u16 = 320             -- auto-scroll target (col 40 on-screen)
    const MAX_X: u16 = %(maxx)d         -- right edge clamp (WCOLS*8 - 160)

    -- 4 tiles, GB 2bpp.
    const TILES: array[u8, 64] = [
%(tiles)s
    ]

    -- The wide logical map, ROW-MAJOR: MAP[r * WCOLS + c]. Mostly ground (1) with
    -- two MARKER columns past the wrap (col 40 -> tile 2, col 55 -> tile 3).
    const MAP: array[u8, %(maplen)d] = [
%(map)s
    ]

    var camx: u16 = 0

    -- The column-source CALLBACK engine.scroll calls: copy logical column `c` of the
    -- wide map into engine.scroll's shared `buf`. Walk the column by ADDING WCOLS per
    -- row (sm83 has no hardware multiply, so `r * WCOLS` per cell is dear).
    function gather(c: u16) {
        var idx: u16 = c
        var r: u8 = 0
        while r < VROWS {
            scroll.buf[r] = MAP[idx]
            idx = idx + WCOLS
            r = r + 1
        }
    }

    function main() {
        -- Fill VRAM with the LCD OFF so the 32-column boot fill isn't throttled to
        -- vblank/hblank windows (GBDK's crt0 powers the LCD on before main).
        video.disable_lcd()
        bkg.set_data(0, 4, TILES)
        scroll.fill(WCOLS, VROWS, gather)        -- seed the first 32 columns

        palette.set_bkg(0, palette.rgb(248, 248, 248), palette.rgb(168, 168, 168), palette.rgb(96, 96, 96), palette.rgb(16, 16, 16))

        video.enable_lcd()
        video.show_background()

        loop {
            -- Auto-scroll right to STOP_X (the headless proof needs no input); D-pad
            -- LEFT rewinds, RIGHT nudges -- engine.scroll re-streams either way.
            if camx < STOP_X {
                camx = camx + SPEED
            }
            if input.held(INPUT_RIGHT) {
                if camx + SPEED <= MAX_X { camx = camx + SPEED }
            }
            if input.held(INPUT_LEFT) {
                if camx >= SPEED { camx = camx - SPEED }
            }

            scroll.update(camx, gather)          -- stream crossed columns + scroll
            video.wait_vblank()
        }
    }

    export main
}
''' % {
        "wcols": WCOLS, "vrows": VROWS, "maxx": WCOLS * 8 - 160,
        "tiles": _fmt(TILES), "maplen": len(flat), "map": _fmt(flat, WCOLS),
    }

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(src)
    print("wrote", os.path.normpath(out_path), "(%d map cells)" % len(flat))


if __name__ == "__main__":
    main()
