#!/usr/bin/env python3
"""Generate `projects/lyc-merge-lab/src/main.mos`.

The map is the only bulky part (a 64-column field with one MARKER column per
band, exactly as `parallax-spike` does it), so it is generated rather than
typed. Everything else is written out below as it reads.

Run: python projects/lyc-merge-lab/assets/gen_main.py
"""
import os

WCOLS = 64
ROWS = 18
BANDS = ((0, 6, 4), (6, 6, 1), (12, 6, 0))    # (first row, rows, shift)
MARKER_COL = (5, 20, 30)                      # one per band, at different x
#: Where the OVERLAY CUT stops the window (W7d phase 2). INSIDE the open box,
#: which is 4 rows tall and bottom-anchored (WY = 112), so the box's own paper
#: ends here and the room shows below it - a cut ABOVE the box would simply
#: take the whole box away and prove nothing about the scanline.
CUT_LINE = 128

HEAD = '''-- main.mos -- GENERATED by projects/lyc-merge-lab/assets/gen_main.py
-- THE W7d GATE: all THREE tenants of LYC_REG alive in one program.
--
-- `LYC_REG` can hold one scanline, and THREE features want one: the scanline
-- PARALLAX bands (each band's SCX written as the beam reaches it), the
-- dialogue box's SPRITE CUT (OBJ off one line above the window, because OBJ
-- draws ABOVE the window on this hardware) and the OVERLAY CUT (the window
-- layer put away partway down the screen, the reference engine's overlay_cut_scanline).
-- The first two used to stand down for each other, and each guard was added
-- after a whole-screen defect found by playing a ROM:
--
--   1. a box OPENING in a parallax room cut sprites at EVERY band boundary,
--      line 0 included, so nothing drew at all;
--   2. a box CLOSING there cleared STATF_LYC, which disables the interrupt
--      for the whole machine, and the band chain never came back.
--
-- Since W7d one emitted handler owns the register and every armed feature
-- contributes STOPS to one list it walks. This program is the smallest thing
-- that can exercise that: three bands at three rates, one sprite low on the
-- screen where the box will cover it, A opens the box, B closes it, and
-- START / SELECT arm and disarm the overlay cut at line %d - which is INSIDE
-- the open box, so the box's own paper stops there and the room (and the
-- sprite) come back below it. The measurement is `verify.py`.
--
-- Each band carries a MARKER column of tile 2 (band 0 at col %d, band 1 at
-- col %d, band 2 at col %d), so at camera `camx` band i draws its marker at
-- screen x `col*8 - (camx >> shift)`. Three different marker positions on one
-- frame is something a single scroll register cannot produce.

module "lyc_merge_lab" {
    import "platform.video"
    import "platform.input"
    import "graphics.bkg"
    import "graphics.text"
    import "graphics.sprite"
    import "engine.scrollpx"

    const WCOLS: u16 = %d
    const SPEED: u16 = 2
    const MAX_X: u16 = 352        -- WCOLS*8 - 160, the right-edge clamp
    const BOX_ROWS: u8 = 4

    -- 3 background tiles: 0 blank, 1 the field, 2 the marker column.
    const TILES: array[u8, 48] = [
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
    ]

    -- One solid sprite tile, parked LOW on the screen inside the band the box
    -- will cover, so the cut has something to take away. Its pixels are
    -- colour 1 and NOTHING else on screen is: the field is 2, a band marker
    -- is 3 and the box's paper is 0. That is what lets verify.py read "the
    -- sprite came back below the overlay cut" off the rendered frame instead
    -- of off a register - an OBJ enable sampled at v-blank cannot see a cut
    -- that is taken away and given back within one frame.
    const SPR: array[u8, 16] = [
        0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00,
        0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00
    ]
'''

TAIL = '''
    const CUT_LINE: u8 = %d
    -- 150 is the reference engine's own default for overlay_cut_scanline and is off the
    -- bottom of a 144-line screen, so writing it is how the cut is DISARMED.
    const CUT_OFF: u8 = 150

    var camx: u16 = 0
    var box_up: u8 = 0
    var prev_a: u8 = 0
    var prev_b: u8 = 0
    var prev_st: u8 = 0
    var prev_se: u8 = 0

    -- engine.scrollpx's column source: fill buf[0..rows-1] with the band's
    -- rows of logical column `c`. The buffer always starts at 0 (mosaik has
    -- no array slicing), so the band's first ROW selects the map cells, not
    -- where they land in the buffer.
    function gather(c: u16, row: u8, rows: u8) {
        var idx: u16 = row
        idx = idx * WCOLS
        idx = idx + c
        var r: u8 = 0
        while r < rows {
            scrollpx.buf[r] = MAP[idx]
            idx = idx + WCOLS
            r = r + 1
        }
    }

    -- Open the box on the WINDOW layer and arm the sprite cut, in that order:
    -- the cut reads WY, which `to_window` is what sets.
    function open_box() {
        text.to_window(18 - BOX_ROWS, BOX_ROWS)
        text.print_string(1, 18 - BOX_ROWS + 1, "LYC")
        text.win_sprite_cut(1)
        box_up = 1
    }

    -- Close it the way a game does: release the cut, then put the window away.
    function close_box() {
        text.win_sprite_cut(0)
        text.to_bkg()
        box_up = 0
    }

    -- THE THIRD TENANT. At CUT_LINE the window layer goes off and the sprites
    -- come back, so the box covers only its top half and the room plays under
    -- it - the reference engine's overlay_cut_scanline. Armed and disarmed on their own
    -- buttons rather than toggled, so the probe can HOLD a button until the
    -- ROM's own gbs_ocut_on says it saw the press.
    function cut_on() {
        text.win_overlay_cut(CUT_LINE)
    }

    function cut_off() {
        text.win_overlay_cut(CUT_OFF)
    }

    function main() {
        video.disable_lcd()
        bkg.set_data(0, 3, TILES)
        sprite.set_data(0, 1, SPR)
        sprite.set_tile(0, 0)
        sprite.move(0, 80, 128)      -- low on the screen, under the box band
        scrollpx.band(0, %d, %d, %d)
        scrollpx.band(1, %d, %d, %d)
        scrollpx.band(2, %d, %d, %d)
        scrollpx.arm(3)
        scrollpx.fill(WCOLS, gather)
        video.enable_lcd()
        video.show_sprites()
        loop {
            if camx < MAX_X {
                camx = camx + SPEED
            }
            scrollpx.update(camx, gather)
            var a: u8 = input.pressed(INPUT_A)
            if a != 0 {
                if prev_a == 0 {
                    if box_up == 0 {
                        open_box()
                    }
                }
                prev_a = 1
            } else {
                prev_a = 0
            }
            var b: u8 = input.pressed(INPUT_B)
            if b != 0 {
                if prev_b == 0 {
                    if box_up == 1 {
                        close_box()
                    }
                }
                prev_b = 1
            } else {
                prev_b = 0
            }
            var st: u8 = input.pressed(INPUT_START)
            if st != 0 {
                if prev_st == 0 {
                    cut_on()
                }
                prev_st = 1
            } else {
                prev_st = 0
            }
            var se: u8 = input.pressed(INPUT_SELECT)
            if se != 0 {
                if prev_se == 0 {
                    cut_off()
                }
                prev_se = 1
            } else {
                prev_se = 0
            }
            video.wait_vblank()
        }
    }

    export main
}
'''


def main():
    rows = []
    for r in range(ROWS):
        band = 0
        for i, (first, n, _s) in enumerate(BANDS):
            if first <= r < first + n:
                band = i
        cells = []
        for c in range(WCOLS):
            cells.append(0x02 if c == MARKER_COL[band] else 0x01)
        rows.append("        " + ", ".join("0x%02X" % v for v in cells))
    body = ("\n    -- The wide map, ROW-MAJOR: MAP[r * WCOLS + c].\n"
            "    const MAP: array[u8, %d] = [\n%s\n    ]\n"
            % (WCOLS * ROWS, ",\n".join(rows)))
    flat = [n for b in BANDS for n in b]
    text = (HEAD % (CUT_LINE, MARKER_COL[0], MARKER_COL[1], MARKER_COL[2],
                    WCOLS)
            + body + TAIL % tuple([CUT_LINE] + flat))
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "src", "main.mos")
    # Build the whole text BEFORE opening the file: a truncate-then-raise
    # leaves a zero-byte module that fails layers later.
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d bytes)" % (out, len(text)))


if __name__ == "__main__":
    main()
