#!/usr/bin/env python3
"""Generate the wide-tall (2D) spike's main.mos (Stage 4 of the large-levels-u16 plan).

A 64x64-tile (512x512 px) logical map -- wide AND tall, past the 256 px wrap on BOTH
axes -- streamed into the 32x32 hardware tilemap via engine.scroll2d.fill2d/update2d as a
u16 camera auto-scrolls DIAGONALLY. Two MARKER tiles sit at far cells (40,40) and
(50,30); after scrolling to camx=camy=320 they must land at their wrapped hardware cells
(40%32, 40%32) = (8,8) and (50%32, 30%32) = (18,30), proving 2D streaming.

    python projects/wide-tall-spike/assets/gen_main.py
"""
import os

W = H = 64                       # 512 x 512 px -- wide AND tall
MARKERS = {(40, 40): 2, (50, 50): 3}   # (col, row): tile id, far past both wraps

TILES = (
    [0x00] * 16 +                # 0 blank
    [0xFF, 0x00] * 8 +           # 1 ground  (colour 1)
    [0xFF, 0xFF] * 8 +           # 2 marker-A (colour 3)
    [0x00, 0xFF] * 8             # 3 marker-B (colour 2)
)


def _fmt(vals, per_line=16):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("        " + ", ".join("0x%02X" % v for v in vals[i:i + per_line]))
    return ",\n".join(out)


def main():
    flat = []
    for r in range(H):
        for c in range(W):
            flat.append(MARKERS.get((c, r), 1))
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "..", "src", "main.mos")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    src = '''-- main.mos -- GENERATED by projects/wide-tall-spike/assets/gen_main.py
-- Stage 4 of the large-levels-u16 plan: prove BOTH-AXES column+row streaming of a wide
-- AND tall map past the 256 px wrap on each axis, via engine.scroll's 2D primitive.

module "wide_tall" {
    import "platform.video"
    import "platform.input"
    import "graphics.bkg"
    import "graphics.palette"
    import "engine.scroll2d"

    const WCOLS: u16 = %(w)d
    const WROWS: u16 = %(h)d
    const SPEED: u16 = 2
    const STOP: u16 = 320            -- diagonal auto-scroll target (both axes)
    const MAXX: u16 = %(maxx)d       -- WCOLS*8 - 160
    const MAXY: u16 = %(maxy)d       -- WROWS*8 - 144

    const TILES: array[u8, 64] = [
%(tiles)s
    ]

    -- 64x64 logical map, ROW-MAJOR: MAP[r * WCOLS + c]. Ground (1) + two far markers.
    const MAP: array[u8, %(maplen)d] = [
%(map)s
    ]

    var camx: u16 = 0
    var camy: u16 = 0

    -- engine.scroll's 2D column/row source: the logical tile at absolute (c, r).
    function tile_at(c: u16, r: u16) -> u8 {
        var idx: u16 = r
        idx = idx * WCOLS
        idx = idx + c
        return MAP[idx]
    }

    function main() {
        video.disable_lcd()
        bkg.set_data(0, 4, TILES)
        scroll2d.fill2d(WCOLS, WROWS, tile_at)
        palette.set_bkg(0, palette.rgb(248, 248, 248), palette.rgb(168, 168, 168), palette.rgb(96, 96, 96), palette.rgb(16, 16, 16))
        video.enable_lcd()
        video.show_background()

        loop {
            if camx < STOP { camx = camx + SPEED }
            if camy < STOP { camy = camy + SPEED }
            if input.held(INPUT_RIGHT) { if camx + SPEED <= MAXX { camx = camx + SPEED } }
            if input.held(INPUT_LEFT)  { if camx >= SPEED { camx = camx - SPEED } }
            if input.held(INPUT_DOWN)  { if camy + SPEED <= MAXY { camy = camy + SPEED } }
            if input.held(INPUT_UP)    { if camy >= SPEED { camy = camy - SPEED } }
            scroll2d.update2d(camx, camy, tile_at)
            video.wait_vblank()
        }
    }

    export main
}
''' % {"w": W, "h": H, "maxx": W * 8 - 160, "maxy": H * 8 - 144,
       "tiles": _fmt(TILES), "maplen": len(flat), "map": _fmt(flat, W)}

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(src)
    print("wrote", os.path.normpath(out_path), "(%d cells)" % len(flat))


if __name__ == "__main__":
    main()
