"""mosaik_scenes.transpile.emit_head - the module header, the world consts, the scene
type/parallax tables, the kind ids and the tileset data.

One section of the generated `scenes` module. `emit(c, L)` appends its
lines to `L`, reading the analysed world off the SceneCtx `c`
(see transpile.context)."""
from .shared import _TS_CHUNK
from ..base import _emit_array, _emit_reader, _ident
from ..filtering import _SCENE_FORK_MARK


def emit(c, L):
    """Header, imports, consts, kind ids, tileset tables + the upload helpers."""
    module, _mark, tile_count, map_w = c.module, c._mark, c.tile_count, c.map_w
    map_h, scenes, uniform, scene_w = c.map_h, c.scenes, c.uniform, c.scene_w
    scene_h, is_vm, scene_type_ids, SCENE_TYPES = c.scene_h, c.is_vm, c.scene_type_ids, c.SCENE_TYPES
    has_parallax, px_bands, px_fixed, PX_MAX = c.has_parallax, c.px_bands, c.px_fixed, c.PX_MAX
    kinds, bkg4_tiles, bkg_pal16, tiles = c.kinds, c.bkg4_tiles, c.bkg_pal16, c.tiles
    has_palettes, kind_tpal, stream, slots_used = c.has_palettes, c.kind_tpal, c.stream, c.slots_used
    per_scene_ts, scene_tiles, paint_table = c.per_scene_ts, c.scene_tiles, c.paint_table
    scene_ts_rel, _dim_type, _check_u8_count = c.scene_ts_rel, c._dim_type, c._check_u8_count
    warm_fn, warm_ranges, wide_world, metatiles = c.warm_fn, c.warm_ranges, c.wide_world, c.metatiles
    has_collision, n_trig, trig_present = c.has_collision, c.n_trig, c.trig_present
    bkg4_engines, has_tile_pal = c.bkg4_engines, c.has_tile_pal

    L.append("-- %s.mos -- GENERATED by mosaik_scenes.py; do not edit by hand." % module)
    L.append("-- Edit the world TOML and re-run the transpiler (game-framework")
    L.append("-- Layer 3 / Phase 4). The game imports this module and composes the")
    L.append("-- framework (engine.pad / engine.camera / engine.collision) around it.")
    L.append("")
    # Table-driven per-scene tilesets ride paint_table's O(1) mode (below); they
    # index the concatenated TILESETS through the range seam, so the module needs
    # `platform.assets` even when nothing streams (there the seam is the
    # byte-identical `(SYM + off)` passthrough).
    ts_table = per_scene_ts and paint_table
    L.append('module "%s" {' % module)
    L.append('    import "graphics.bkg"')
    if has_palettes:
        L.append('    import "graphics.palette"')
    if kind_tpal:
        L.append('    import "graphics.sprite"')
    if stream or ts_table:
        L.append('    import "platform.assets"')
    # PER-SCENE tile animation steps by elapsed DISPLAY frames (see
    # `_emit_scene_animated`), so it needs the free-running frame counter.
    # Gated, so a world with no animation is byte-identical.
    if any(sc.get("animated_tile") for sc in scenes):
        L.append('    import "platform.system"')
    if slots_used:
        # Slot selectors reference scripts.ENTRY_<name> (the compiled event script
        # entry offsets); the C linker resolves the name. Only pulled in when a
        # slot is actually bound, so a VM world with no scripts stays byte-identical.
        L.append('    import "scripts"')
    if _mark:
        L.append(_SCENE_FORK_MARK)           # start of the per-console forkable body
    L.append("    const TILE_COUNT: u8 = %d" % tile_count)
    L.append("    const MAP_W: %s = %d" % (_dim_type(map_w), map_w))
    L.append("    const MAP_H: %s = %d" % (_dim_type(map_h), map_h))
    _check_u8_count("scenes", len(scenes), "split into more worlds")
    L.append("    const SCENE_COUNT: u8 = %d" % len(scenes))
    # Per-scene sizes only when the world is non-uniform (item 20): MAP_W/MAP_H
    # are the world default; SCENE_W/SCENE_H give each scene's own tile dims, so
    # a game indexes a scene's map with SCENE_W[room] instead of MAP_W.
    if not uniform:
        _emit_array(L, _dim_type(*scene_w), "SCENE_W", len(scenes), scene_w)
        _emit_array(L, _dim_type(*scene_h), "SCENE_H", len(scenes), scene_h)
    L.append("")
    # VM8 scene-type table (VM worlds only -- byte-identical elsewhere). The
    # native per-scene player handler dispatches on SCENE_TYPE[room] (Stage 2).
    if is_vm:
        for k, nm in enumerate(SCENE_TYPES):
            L.append("    const SCTYPE_%s: u8 = %d" % (nm.upper(), k))
        _emit_array(L, "u8", "SCENE_TYPE", len(scenes), scene_type_ids)
        _emit_reader(L, "scene_type_at", "SCENE_TYPE", "u8")
        L.append("")
    # PARALLAX BANDS, flattened to fixed-stride tables (3 slots a scene, the
    # scanline runtime's limit) so a room load is four indexed reads and no
    # per-scene code. Emitted only when a scene HAS bands.
    if has_parallax:
        L.append("    -- Parallax bands: up to %d per scene, %d slots each in"
                 % (PX_MAX, PX_MAX))
        L.append("    -- these fixed-stride tables (index scene * %d + band)."
                 % PX_MAX)
        L.append("    -- PX_SHIFT is the speed divisor: 0 = full, n = 1/2^n,")
        L.append("    -- %d = FIXED (the band never scrolls)." % px_fixed)
        L.append("    const PX_MAX: u8 = %d" % PX_MAX)
        L.append("    const PX_FIXED: u8 = %d" % px_fixed)
        _emit_array(L, "u8", "PX_COUNT", len(scenes),
                    [len(b) for b in px_bands])
        for nm, k in (("PX_ROW", 0), ("PX_ROWS", 1), ("PX_SHIFT", 2)):
            flat = []
            for bands in px_bands:
                for s in range(PX_MAX):
                    flat.append(bands[s][k] if s < len(bands) else 0)
            _emit_array(L, "u8", nm, len(flat), flat)
        _emit_reader(L, "px_count", "PX_COUNT", "u8")
        for nm, fn in (("PX_ROW", "px_row"), ("PX_ROWS", "px_rows"),
                       ("PX_SHIFT", "px_shift")):
            L.append("    function %s(scene: u8, i: u8) -> u8 {" % fn)
            L.append("        var k: u16 = scene")
            L.append("        k = k * PX_MAX + i")
            L.append("        return %s[k]" % nm)
            L.append("    }")
        L.append("")
    # Object-kind ids as named constants, so games compare OBJ_KIND[i] == KIND_*.
    for name, kid in kinds.items():
        L.append("    const KIND_%s: u8 = %d" % (_ident(name), int(kid) & 0xFF))
    if kinds:
        L.append("")
    if bkg4_tiles is not None:
        # 4bpp fork: conditional compilation keeps exactly one TILESET per build
        # (the non-matching branch is dropped before codegen), so a 4bpp console
        # links the 32 B/tile packed-nibble tiles and every other console the
        # 16 B/tile 2bpp tiles. TILE_COUNT is the tile count (not bytes), so it is
        # the same in both branches and stays emitted once above.
        cond = " or ".join('platform == "%s"' % p for p in sorted(bkg4_engines))
        L.append("    if %s {" % cond)
        _emit_array(L, "u8", "TILESET", len(bkg4_tiles), list(bkg4_tiles))
        L.append("    } else {")
        _emit_array(L, "u8", "TILESET", tile_count * 16, list(tiles))
        L.append("    }")
        # The tileset's authored 16-colour palette (5-5-5 RGB words), loaded by
        # palette.load_bkg16 on a 4bpp console (a no-op on a 2bpp console, where
        # the tileset luma-quantized to greys). Unconditional so it always resolves.
        _emit_array(L, "u16", "BKG_PALETTE16", len(bkg_pal16), list(bkg_pal16))
    else:
        _emit_array(L, "u8", "TILESET", tile_count * 16, list(tiles))
    L.append("")
    # Per-scene tileset arrays (Gap 3): one <SCENE>_TS/<SCENE>_TC per OVERRIDE scene;
    # shared-tileset scenes reference TILESET, so nothing is duplicated. paint()
    # uploads the resolved tileset on room load (below). Only emitted for an override
    # world -- byte-identical otherwise.
    scene_ts_name = [None] * len(scenes)
    ts_off = [0] * len(scenes)
    ts_tc = [0] * len(scenes)          # 0 = this scene uses the SHARED tileset
    ts_maxlen = 0
    if ts_table:
        # TABLE-DRIVEN tilesets (item 33's code lever applied to the tileset).
        # The per-scene chain above costs one `if scene == N` link per room in
        # paint(), so a many-room world pays code for rooms it is not painting.
        # Here the DISTINCT tilesets concatenate into ONE array and each scene
        # keeps an (offset, count) row, so the upload is O(1) and adding a room
        # adds table rows, not code. Identical tilesets share a block.
        # CHUNKED: a const array is read in place while its ONE ROM bank is
        # mapped, so no single symbol may exceed a bank (16 KB on the GB, the
        # tightest per-symbol ceiling of any target). A 17-room world's
        # tileset art reaches that on its own - measured 15,488 B before
        # colour and 16,624 B after - so the concatenation is packed into
        # CHUNKS instead: each scene's block lives whole inside one chunk,
        # TS_BLK says which, and TS_OFF is the offset WITHIN it. A world whose
        # art fits one chunk (every world before this) emits exactly the one
        # TILESETS symbol and no TS_BLK, byte-identical.
        chunks = [[]]
        seen = {}
        ts_blk = [0] * len(scenes)
        for i, st in enumerate(scene_tiles):
            if st is None:
                continue                # this scene uses the shared TILESET
            tiles_i, tc_i = st
            key = bytes(bytearray(tiles_i))
            if key not in seen:
                if chunks[-1] and len(chunks[-1]) + len(tiles_i) > _TS_CHUNK:
                    chunks.append([])
                seen[key] = (len(chunks) - 1, len(chunks[-1]))
                chunks[-1].extend(tiles_i)
            ts_blk[i], ts_off[i] = seen[key]
            ts_tc[i] = tc_i
            ts_maxlen = max(ts_maxlen, tc_i * 16)
        ts_names = ["TILESETS" if k == 0 else "TILESETS%d" % (k + 1)
                    for k in range(len(chunks))]
        L.append("    -- Per-scene tilesets, CONCATENATED + indexed (item 33 applied")
        L.append("    -- to the tileset): TS_OFF/TS_TC give each room's block, so")
        L.append("    -- paint() uploads in O(1) instead of an `if scene ==` chain")
        L.append("    -- that grows with the room count. TS_TC 0 = the shared TILESET.")
        L.append("    -- TS_MAX_TC bounds the background tile table (read by the Lynx")
        L.append("    -- budget pass, which cannot see through the indexed upload).")
        L.append("    const TS_MAX_TC: u8 = %d" % max(ts_tc))
        for k, chunk in enumerate(chunks):
            if k:
                L.append("    -- Chunk %d: no const array may cross a ROM bank, so the"
                         % (k + 1))
                L.append("    -- concatenation continues in its own symbol.")
            _emit_array(L, "u8", ts_names[k], len(chunk), chunk, per_line=16)
            L.append("")
        _emit_array(L, _dim_type(*ts_off), "TS_OFF", len(ts_off), ts_off)
        L.append("")
        _emit_array(L, "u8", "TS_TC", len(ts_tc), ts_tc)
        L.append("")
        if len(chunks) > 1:
            _emit_array(L, "u8", "TS_BLK", len(ts_blk), ts_blk)
            L.append("")
    elif per_scene_ts:
        for i, st in enumerate(scene_tiles):
            if st is None:
                continue
            tiles_i, tc_i = st
            nm = _ident(scenes[i].get("name", "scene%d" % i))
            scene_ts_name[i] = nm
            L.append("    const %s_TC: u8 = %d" % (nm, tc_i))
            _emit_array(L, "u8", "%s_TS" % nm, tc_i * 16, tiles_i)
            L.append("")

    def _emit_tileset_upload(indent="        "):
        """Per-scene tileset (Gap 3): upload the scene's resolved tileset on room load
        -- an OVERRIDE scene swaps in its own image, a shared scene restores TILESET --
        so a scene change swaps the tileset. A no-op for a shared-tileset world (this
        emits nothing, so paint() is byte-identical there). Under [world] stream the
        per-scene TS rides the residency seam like the maps (assets.use + assets.ptr:
        the Lynx loads it from the cart at room load, the banking consoles bank it;
        set_data copies it out, so it may be evicted right after) -- a many-scene
        world's tileset art would otherwise dominate the resident image. The SHARED
        `TILESET` stays resident (every scene references it).

        This COMBINES with `paint_table`, where the maps window through the RANGE
        seam while the tileset loads whole: the Lynx runtime emits each cache on
        its own seam (`gen_streaming._emit_stream_runtime`), and the whole cache's
        slots are sized over whole-LOADED assets only, so the concatenated MAPS
        array does not size a RAM slot.

        Under `paint_table` the upload is TABLE-DRIVEN (one indexed read, no
        per-scene chain) and the concatenated TILESETS rides the SAME range seam
        as the maps: `range_base` registers it, `use_range` warms the room's
        window, `ptr_range` hands the setter its pointer (a plain `(SYM + off)`
        on every directly-mapped console). Uploading FIRST is deliberate: the
        Lynx range cache has 2 slots, so the tileset window is loaded, copied
        out by set_data, and then evicted by the map + collision windows that
        `map_tile`/`collision_at` read every frame.

        COLOUR on SMS/GG rides THIS upload (a coloured world only): those
        consoles have no per-tile attribute layer, but their VDP stores every
        tile at 4bpp, so each tile is uploaded rendered through its palette
        SLOT (bkg.set_data_pal -> CRAM entries slot*4..) -- the per-tile
        colour the GBC gets from paint_attrs, off the same 2bpp art. The two
        arms fork on `if platform`, so every other console's generated C is
        the plain upload it always was (the fork folds at compile)."""
        if not per_scene_ts:
            if has_tile_pal and c.bkg4_tiles is None:
                # A SHARED 2bpp tileset in a coloured world: the same slotted
                # re-upload, per scene, on SMS/GG only (their per-tile colour
                # IS the upload - there is no attribute layer). It used to be
                # emitted for per-scene tilesets alone, so every hand-made
                # world drew all of its tiles through slot 0 there. The empty
                # else keeps every other console's paint() unchanged.
                L.append('%sif platform == "sms" or platform == "gamegear" {'
                         % indent)
                L.append("%s    ts_upload(scene)" % indent)
                L.append("%s} else {" % indent)
                L.append("%s}" % indent)
            return
        if has_tile_pal:
            # The slotted arm is ONE shared `ts_upload(scene)` (emitted with
            # the colour tables below) rather than an inline copy in each of
            # paint() and warm(): it contains a residency-seam read, so it is
            # pinned RESIDENT, and a second copy is bank-0 image this console
            # counts in tens of bytes. Scoped to the fork, so every other
            # console keeps its inline upload byte-identical.
            L.append('%sif platform == "sms" or platform == "gamegear" {'
                     % indent)
            L.append("%s    ts_upload(scene)" % indent)
            L.append("%s} else {" % indent)
            _ts_arm(indent + "    ", False)
            L.append("%s}" % indent)
        else:
            _ts_arm(indent, False)

    def _ts_arm(ind, slotted):
            def up_plain(ind2, cnt, ptr):
                L.append("%sbkg.set_data(0, %s, %s)" % (ind2, cnt, ptr))

            def up_slotted(ind2, cnt, ptr):
                # ts_slots (BANKED scenes code) copies the scene's TILE_PAL
                # row into the small RAM buffer FIRST, then ONE helper call
                # uploads every tile through its slot -- the buffer is what
                # lets the C helper read slots while the tileset's own bank
                # is mapped (two banked const arrays in one call would leave
                # the bank mapping to argument evaluation order), and it
                # keeps this resident, seam-pinned function at one call
                # instead of a per-tile loop.
                L.append("%sts_slots(scene, %s)" % (ind2, cnt))
                L.append("%sbkg.set_data_pal(0, %s, %s, TS_PAL_BUF)"
                         % (ind2, cnt, ptr))

            up = up_slotted if slotted else up_plain
            if ts_table:
                # The shared-TILESET branch is provably dead when every scene
                # brought its own image (TS_TC is never 0), so it is not
                # emitted at all. That is what leaves `TILESET` unreferenced,
                # and tree-shaking then drops the array with it.
                #
                # It used to be scoped to the SLOTTED (SMS/GG) arm, where
                # bank-0 headroom is counted in tens of bytes, on the grounds
                # that the plain arm should stay byte-identical. Measured on
                # the GB family that was the wrong trade: the plain arm is
                # pinned RESIDENT by the same seam read, so a reference-engine
                # conversion - where EVERY scene carries its own tileset by
                # construction - was paying bank 0 for a tileset no scene can
                # ever draw. A world where any scene falls back to the shared
                # image still emits the branch and is unchanged.
                shared = (0 in ts_tc)
                L.append("%svar tsc: u8 = TS_TC[scene]" % ind)
                if shared:
                    L.append("%sif tsc == 0 {" % ind)
                    up(ind + "    ", "TILE_COUNT", "TILESET")
                    L.append("%s} else {" % ind)
                else:
                    L.append("%sif tsc > 0 {" % ind)
                L.append("%s    var tso: u16 = TS_OFF[scene]" % ind)
                L.append("%s    var tsn: u16 = tsc" % ind)
                L.append("%s    tsn = tsn * 16" % ind)
                # One arm per CHUNK. A single-chunk world (every world before
                # the concatenation outgrew a ROM bank) emits exactly the one
                # arm it always did, with no TS_BLK read -- byte-identical.
                for k, nm in enumerate(ts_names):
                    ind2 = ind + "    "
                    if len(ts_names) > 1:
                        if k == 0:
                            L.append("%s    if TS_BLK[scene] == 0 {" % ind)
                        elif k == len(ts_names) - 1:
                            L.append("%s    } else {" % ind)
                        else:
                            L.append("%s    } else if TS_BLK[scene] == %d {"
                                     % (ind, k))
                        ind2 = ind + "        "
                    if stream:
                        L.append("%sassets.range_base(%s, %d)"
                                 % (ind2, nm, ts_maxlen))
                        L.append("%sassets.use_range(%s, tso, tsn)" % (ind2, nm))
                    up(ind2, "tsc", "assets.ptr_range(%s, tso, tsn)" % nm)
                if len(ts_names) > 1:
                    L.append("%s    }" % ind)
                L.append("%s}" % ind)
                return
            for i in range(len(scenes)):
                if scene_ts_name[i]:
                    nm = scene_ts_name[i]
                    cnt = "%s_TC" % nm
                    ptr = ("assets.ptr(%s_TS)" % nm) if stream \
                        else ("%s_TS" % nm)
                else:
                    nm, cnt, ptr = None, "TILE_COUNT", "TILESET"
                if not slotted:
                    pre = ("assets.use(%s_TS) " % nm) \
                        if (stream and nm) else ""
                    L.append("%sif scene == %d { %sbkg.set_data(0, %s, %s) }"
                             % (ind, i, pre, cnt, ptr))
                    continue
                L.append("%sif scene == %d {" % (ind, i))
                if stream and nm:
                    L.append("%s    assets.use(%s_TS)" % (ind, nm))
                up(ind + "    ", cnt, ptr)
                L.append("%s}" % ind)

    # The type widths the paint_table loop / offset table use (mirroring the
    # dimension consts): the map width/height dims + the offset table.
    # PUBLISHED for the later sections: `ts_table` and the per-scene
    # tileset tables are decided here, and paint() / the palette loaders
    # call these two helpers to upload a scene's own tileset.
    c.ts_table = ts_table
    c.scene_ts_name, c.ts_off = scene_ts_name, ts_off
    c.ts_tc, c.ts_maxlen = ts_tc, ts_maxlen
    c._emit_tileset_upload = _emit_tileset_upload
    c._ts_arm = _ts_arm

