#!/usr/bin/env python3
"""palettes-lab: does the hand-written game load every Palettes-dock option?

Read off the SCREEN by hue on a GBC ROM (PyBoy's palette reads are raw):

1. the meadow under the world DEFAULT rows: grass green, water blue, brick red,
   and the SPLIT brick cells moss green;
2. per-CELL sprite slots on the hero (a blue body, a skin head) and the gem's
   frame palette alternating warm and cool;
3. B writes the night palette into background slot 1 at run time, B again
   reloads the room's palettes;
4. A loads the cave, whose OWN rows put lava red and the pool blue.

The world is generated by the studio's tools/gen_samples/palettes_lab_world.py;
`src/palettes_lab.mos` is the code that loads it.

    python projects/palettes-lab/verify.py [rom]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(HERE, "build", "gameboy_color", "palettes-lab.gbc")

ok = True


def check(label, cond):
    global ok
    print("  [%s] %s" % ("PASS" if cond else "FAIL", label))
    ok &= bool(cond)


def px(pb, x, y):
    return tuple(int(v) for v in pb.screen.ndarray[y, x, :3])


def green(c):
    return c[1] > c[0] + 20 and c[1] > c[2] + 20


def blue(c):
    return c[2] > c[0] + 30 and c[2] >= c[1]


def red(c):
    return c[0] > c[1] + 40 and c[0] > c[2] + 40


def region(pb, x0, y0, x1, y1):
    a = pb.screen.ndarray[y0:y1, x0:x1, :3].reshape(-1, 3)
    return {tuple(int(v) for v in c) for c in a}


def tap(pb, button, frames=30):
    pb.button_press(button)
    for _ in range(6):
        pb.tick()
    pb.button_release(button)
    for _ in range(frames):
        pb.tick()


def main():
    rom = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    if not os.path.isfile(rom):
        print("build it first: python mosaik8.py build --platform gameboy_color "
              "projects/palettes-lab")
        return 0
    from pyboy import PyBoy
    pb = PyBoy(rom, window="null", sound_emulated=False, cgb=True)
    for _ in range(90):
        pb.tick()
    print("[palettes-lab on the Game Boy Color]")
    check("grass is green: %r" % (px(pb, 20, 120),), green(px(pb, 20, 120)))
    check("water is blue: %r" % (px(pb, 100, 36),), blue(px(pb, 100, 36)))
    check("brick is red: %r" % (px(pb, 84, 140),), red(px(pb, 84, 140)))
    check("the SPLIT brick cells are moss green: %r" % (px(pb, 36, 140),),
          green(px(pb, 36, 140)))
    hero = region(pb, 16, 48, 64, 96)
    check("the hero wears two palettes (a blue body and a skin head)",
          any(blue(c) for c in hero)
          and any(c[0] > c[1] > c[2] and c[0] > 200 for c in hero))
    warm = cool = False
    for _ in range(60):
        pb.tick()
        gem = region(pb, 112, 88, 144, 128)
        warm |= any(c[0] > c[2] + 80 and c[1] > 60 for c in gem)
        cool |= any(c[2] > c[0] + 80 for c in gem)
    check("the gem's frame palette alternates warm and cool", warm and cool)
    day = px(pb, 20, 120)
    tap(pb, "b")
    check("B writes the night palette into slot 1: %r" % (px(pb, 20, 120),),
          blue(px(pb, 20, 120)))
    tap(pb, "b")
    check("B again reloads the room's palettes", px(pb, 20, 120) == day)
    tap(pb, "a", 60)
    check("A loads the cave, whose own row puts lava red: %r"
          % (px(pb, 108, 100),), red(px(pb, 108, 100)))
    check("... and the cave pool blue: %r" % (px(pb, 36, 36),),
          blue(px(pb, 36, 36)))
    pb.stop(save=False)
    print("All checks passed" if ok else "FAILURES")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
