[[script]]
name = "main"
[[script.events]]
event = "stop"


[[script]]
name = "scene_init"
[[script.events]]
event = "set_var"
var = "php"
value = 6

[[script.events]]
event = "set_var"
var = "phpmax"
value = 6

[[script.events]]
event = "set_var"
var = "pihurt"
value = 0

[[script.events]]
event = "set_var"
var = "score"
value = 0

[[script.events]]
event = "set_var"
var = "spawnx"
value = 40

[[script.events]]
event = "shmup_scroll"
pace = 2
dir = 3

[[script.events]]
event = "input_attach"
button = "b"
script = "shoot"

[[script.events]]
event = "start_thread"
script = "player_tick"

[[script.events]]
event = "stop"


[[script]]
name = "shoot"
[[script.events]]
event = "projectile"
x = "player_x() + 2"
y = "player_y() - 6"
vx = 0
vy = "0 - 6"
tile = 2
life = 60

[[script.events]]
event = "stop"


[[script]]
name = "enemy_fly"
loop = true
[[script.events]]
event = "if"
cond = "actor_y(self) > 146"
[[script.events.then]]
event = "set_var"
var = "spawnx"
expr = "(spawnx * 37 + 11) % 148"

[[script.events.then]]
event = "actor_set_pos"
actor = "self"
x = "spawnx + 4"
y = 0

[[script.events.then]]
event = "actor_set_hp"
actor = "self"
hp = 3

[[script.events.else]]
event = "actor_set_pos"
actor = "self"
x = "actor_x(self)"
y = "actor_y(self) + 1"

[[script.events.else]]
event = "if"
cond = "pihurt == 0 and abs(player_x() - actor_x(self)) < 10 and abs(player_y() - actor_y(self)) < 10"
[[script.events.else.then]]
event = "set_var"
var = "php"
expr = "php - 1"

[[script.events.else.then]]
event = "set_var"
var = "pihurt"
value = 30



[[script.events]]
event = "wait"
frames = 2


[[script]]
name = "enemy_init"
[[script.events]]
event = "actor_set_hp"
actor = "self"
hp = 3

[[script.events]]
event = "stop"


[[script]]
name = "enemy_hit"
[[script.events]]
event = "projectile"
x = "actor_x(self)"
y = "actor_y(self)"
vx = 0
vy = 0
tile = 4
life = 10
mask = 0

[[script.events]]
event = "actor_damage"
actor = "self"
amount = 1

[[script.events]]
event = "if"
cond = "actor_hp(self) == 0"
[[script.events.then]]
event = "set_var"
var = "score"
expr = "score + 1"

[[script.events.then]]
event = "set_var"
var = "spawnx"
expr = "(spawnx * 37 + 11) % 148"

[[script.events.then]]
event = "actor_set_pos"
actor = "self"
x = "spawnx + 4"
y = 0

[[script.events.then]]
event = "actor_set_hp"
actor = "self"
hp = 3


[[script.events]]
event = "stop"


[[script]]
name = "player_tick"
loop = true
[[script.events]]
event = "if"
cond = "pihurt > 0"
[[script.events.then]]
event = "set_var"
var = "pihurt"
expr = "pihurt - 1"


[[script.events]]
event = "if"
cond = "php <= 0"
[[script.events.then]]
event = "set_var"
var = "php"
expr = "phpmax"

[[script.events.then]]
event = "set_var"
var = "pihurt"
value = 60

[[script.events.then]]
event = "set_var"
var = "score"
value = 0


[[script.events]]
event = "idle"


