/* Generated by mosaik -> cc65 C backend */
/* Target console: lynx (cc65 tgi-text profile) */
#include <tgi.h>
#include <lynx.h>
#include <joystick.h>
#include <6502.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Text is addressed in character cells (as on Game Boy);
   TGI profiles scale cell coords to pixels. */
#define GBS_CELL_W 8
#define GBS_CELL_H 8

/* Screen geometry for the build target. */
#define SCREEN_WIDTH  160
#define SCREEN_HEIGHT 102
#define SCREEN_COLS   20
#define SCREEN_ROWS   12

/* Input button constants mapped to this console's joypad bits. */
#define INPUT_A      JOY_BTN_1_MASK
#define INPUT_B      JOY_BTN_2_MASK
#define INPUT_SELECT 0
#define INPUT_START  0
#define INPUT_RIGHT  JOY_RIGHT_MASK
#define INPUT_LEFT   JOY_LEFT_MASK
#define INPUT_UP     JOY_UP_MASK
#define INPUT_DOWN   JOY_DOWN_MASK

/* Sprite flip flags -> Suzy SPRCTL0 bits (graphics.sprite). */
#define FLIP_X HFLIP
#define FLIP_Y VFLIP

/* mosaik standard library helpers (cc65) */
static uint8_t gbs_video_ready = 0;
void gbs_video_init(void) {
    if (gbs_video_ready) return;
    tgi_install(tgi_static_stddrv);
    tgi_init();
    CLI();
    joy_install(joy_static_stddrv);
    tgi_setpalette(tgi_getdefpalette());
    tgi_setframerate(60);
    tgi_setviewpage(0);
    tgi_setdrawpage(0);
    tgi_setcolor(COLOR_WHITE);
    tgi_clear();
    gbs_video_ready = 1;
}
void gbs_video_done(void) { joy_uninstall(); tgi_uninstall(); }
/* --- Suzy hardware sprite engine (Atari Lynx) --- */
#define GBS_MAX_TILES   32
#define GBS_MAX_SPRITES 40
#define GBS_TILE_BYTES  33  /* literal-encoded 8x8 2bpp tile */
static uint8_t gbs_tiles[GBS_MAX_TILES][GBS_TILE_BYTES];
static SCB_REHV_PAL gbs_scb[GBS_MAX_SPRITES];
static uint8_t gbs_spr_tile[GBS_MAX_SPRITES];
static uint8_t gbs_spr_max = 0;     /* highest slot touched + 1 */
static uint8_t gbs_spr_used = 0;    /* engine active this program */
static uint8_t gbs_spr_visible = 1;
static uint8_t gbs_spr_db = 0;      /* double-buffering engaged */
static uint8_t gbs_spr_inited = 0;
/* GB 2bpp pixel value 1..3 -> Lynx pens; value 0 -> pen 0 = transparent.
   Packed two pens per byte, lower pixel value in the high nibble. */
static const uint8_t gbs_spr_penpal[8] = {
    (COLOR_TRANSPARENT << 4) | COLOR_LIGHTGREY,   /* pixels 0,1 */
    (COLOR_GREY << 4) | COLOR_WHITE,              /* pixels 2,3 */
    0, 0, 0, 0, 0, 0
};
static void gbs_spr_init(void) {
    uint8_t s, i;
    if (gbs_spr_inited) return;
    for (s = 0; s < GBS_MAX_SPRITES; ++s) {
        gbs_scb[s].sprctl0 = BPP_2 | TYPE_NORMAL;
        gbs_scb[s].sprctl1 = LITERAL | REHV;  /* literal data, reload h/v size */
        gbs_scb[s].sprcoll = 0;
        gbs_scb[s].next = (char *)0;
        gbs_scb[s].data = gbs_tiles[0];       /* default to tile 0 (as on GB) */
        gbs_scb[s].hpos = -16; gbs_scb[s].vpos = -16;
        gbs_scb[s].hsize = 0x100; gbs_scb[s].vsize = 0x100;  /* 1:1 scale */
        for (i = 0; i < 8; ++i) gbs_scb[s].penpal[i] = gbs_spr_penpal[i];
    }
    gbs_spr_inited = 1;
}
/* Convert one 8x8 GB 2bpp tile (16 bytes) into a literal Lynx sprite. */
static void gbs_conv_tile(uint8_t tile, const uint8_t *gb) {
    uint8_t *o = gbs_tiles[tile];
    uint8_t row, col, lo, hi, bit, ci, a, b;
    for (row = 0; row < 8; ++row) {
        lo = gb[row * 2]; hi = gb[row * 2 + 1];
        a = 0; b = 0;
        for (col = 0; col < 8; ++col) {
            bit = 7 - col;
            ci = (uint8_t)((((hi >> bit) & 1) << 1) | ((lo >> bit) & 1));
            if (col < 4) a = (uint8_t)(a | (ci << ((3 - col) * 2)));
            else         b = (uint8_t)(b | (ci << ((3 - (col - 4)) * 2)));
        }
        *o++ = 0x04; *o++ = a; *o++ = b; *o++ = 0x00;
    }
    *o = 0x00;  /* end of sprite data */
}
void gbs_present(void) {
    uint8_t s;
    /* No sprites in use: stay single-buffered so immediate
       (text) drawing persists and does not flicker -- but still
       wait out the frame so wait_vblank paces the main loop.
       The Lynx clock() ticks once per display frame (Mikey
       timer 2, the VBL timer), so CLOCKS_PER_SEC == framerate. */
    if (!gbs_spr_used) {
        clock_t t = clock();
        while (clock() == t) { }
        return;
    }
    /* First sprite frame: switch to true double-buffering so the
       per-frame clear+redraw happens off-screen. */
    if (!gbs_spr_db) { tgi_setdrawpage(1); gbs_spr_db = 1; }
    tgi_setcolor(COLOR_BLACK);
    tgi_bar(0, 0, 159, 101);
    if (gbs_spr_visible)
        for (s = 0; s < gbs_spr_max; ++s) tgi_sprite(&gbs_scb[s]);
    while (tgi_busy()) { }  /* let Suzy finish before the flip */
    tgi_updatedisplay();    /* VBL-synced flip (draw <-> view) */
}
void gbs_set_sprite_data(uint8_t first, uint8_t count, const uint8_t *data) {
    uint8_t i;
    gbs_spr_init();
    for (i = 0; i < count; ++i)
        if ((uint8_t)(first + i) < GBS_MAX_TILES)
            gbs_conv_tile((uint8_t)(first + i), data + (uint16_t)i * 16);
    gbs_spr_used = 1;
}
void gbs_set_sprite_tile(uint8_t nb, uint8_t tile) {
    gbs_spr_init();
    if (nb < GBS_MAX_SPRITES && tile < GBS_MAX_TILES) {
        gbs_spr_tile[nb] = tile;
        gbs_scb[nb].data = gbs_tiles[tile];
        if (nb >= gbs_spr_max) gbs_spr_max = nb + 1;
    }
    gbs_spr_used = 1;
}
uint8_t gbs_get_sprite_tile(uint8_t nb) {
    return nb < GBS_MAX_SPRITES ? gbs_spr_tile[nb] : 0;
}
/* prop carries FLIP_X (HFLIP) / FLIP_Y (VFLIP) for SPRCTL0. */
void gbs_set_sprite_prop(uint8_t nb, uint8_t prop) {
    gbs_spr_init();
    if (nb < GBS_MAX_SPRITES)
        gbs_scb[nb].sprctl0 = (uint8_t)((BPP_2 | TYPE_NORMAL) |
            (prop & (HFLIP | VFLIP)));
}
/* sprite.move takes screen-pixel coordinates (top-left origin). */
void gbs_move_sprite(uint8_t nb, uint8_t x, uint8_t y) {
    gbs_spr_init();
    if (nb < GBS_MAX_SPRITES) {
        gbs_scb[nb].hpos = x;
        gbs_scb[nb].vpos = y;
        if (nb >= gbs_spr_max) gbs_spr_max = nb + 1;
    }
    gbs_spr_used = 1;
}
void gbs_show_sprites(void) { gbs_spr_used = 1; gbs_spr_visible = 1; }
void gbs_hide_sprites(void) { gbs_spr_visible = 0; }
void gbs_show_bkg(void) { }
uint8_t gbs_input_pressed(uint8_t button) {
    gbs_video_init();
    return (uint8_t)(joy_read(0) & button);
}
/* TGI text draws transparently (pixels OR onto the screen), but the
   Game Boy's tile text *replaces* the cell -- so clear the covered
   cells first to keep reprinting (counters, scores) portable. */
void gbs_print_string(uint8_t x, uint8_t y, const char *s) {
    int px = (int)x * GBS_CELL_W, py = (int)y * GBS_CELL_H;
    gbs_video_init();
    tgi_setcolor(COLOR_BLACK);
    tgi_bar(px, py, px + (int)strlen(s) * GBS_CELL_W - 1, py + GBS_CELL_H - 1);
    tgi_setcolor(COLOR_WHITE);
    tgi_outtextxy(px, py, s);
}
void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) {
    char buf[7];
    utoa(n, buf, 10);
    gbs_print_string(x, y, buf);
}
void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {
    gbs_video_init();
    tgi_setcolor(COLOR_BLACK);
    tgi_bar((int)x * GBS_CELL_W, (int)y * GBS_CELL_H,
            (int)(x + w) * GBS_CELL_W - 1, (int)(y + h) * GBS_CELL_H - 1);
    tgi_setcolor(COLOR_WHITE);
}
/* delay(ms) busy-waits using the system clock (CLOCKS_PER_SEC ticks/s). */
void gbs_delay(uint16_t ms) {
    clock_t target = clock() + (clock_t)ms * CLOCKS_PER_SEC / 1000;
    while (clock() < target) { }
}
void gbs_seed_random(uint16_t seed) { srand(seed); }
/* Raw hardware register access (addresses are console-specific). */
void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }
uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }

/* Module: bounce_sprite */

const uint8_t BALL_TILE[16] = {60, 60, 126, 126, 255, 255, 255, 255, 255, 255, 255, 255, 126, 126, 60, 60};
#define MIN_X (4)
#define MAX_X ((SCREEN_WIDTH - 12))
#define MIN_Y (4)
#define MAX_Y ((SCREEN_HEIGHT - 12))

typedef struct {
    uint8_t x;
    uint8_t y;
    int8_t dx;
    int8_t dy;
    uint8_t active;
} Sprite;

Sprite player;
uint8_t frame_counter = 0;

void init_sprite(void);
void update_sprite(void);
void handle_input(void);
void main(void);

void init_sprite(void) {
    player.x = (SCREEN_WIDTH / 2);
    player.y = (SCREEN_HEIGHT / 2);
    player.dx = 2;
    player.dy = 1;
    player.active = 1;
}

void update_sprite(void) {
    if ((!player.active)) {
        return;
    }
    player.x += player.dx;
    player.y += player.dy;
    if ((player.x <= MIN_X)) {
        player.x = MIN_X;
        player.dx = (-player.dx);
    }
    if ((player.x >= MAX_X)) {
        player.x = MAX_X;
        player.dx = (-player.dx);
    }
    if ((player.y <= MIN_Y)) {
        player.y = MIN_Y;
        player.dy = (-player.dy);
    }
    if ((player.y >= MAX_Y)) {
        player.y = MAX_Y;
        player.dy = (-player.dy);
    }
}

void handle_input(void) {
    if ((gbs_input_pressed(INPUT_A) && ((frame_counter % 8) == 0))) {
        if (((player.dx > 0) && (player.dx < 4))) {
            player.dx += 1;
        }
        if (((player.dx < 0) && (player.dx > (-4)))) {
            player.dx -= 1;
        }
        if (((player.dy > 0) && (player.dy < 4))) {
            player.dy += 1;
        }
        if (((player.dy < 0) && (player.dy > (-4)))) {
            player.dy -= 1;
        }
    }
    if (gbs_input_pressed(INPUT_B)) {
        init_sprite();
    }
    if ((gbs_input_pressed(INPUT_SELECT) && ((frame_counter % 16) == 0))) {
        player.active = (!player.active);
    }
}

void main(void) {
    gbs_set_sprite_data(0, 1, BALL_TILE);
    gbs_set_sprite_tile(0, 0);
    init_sprite();
    gbs_move_sprite(0, player.x, player.y);
    gbs_video_init();
    gbs_show_sprites();
    while (1) {
        frame_counter += 1;
        handle_input();
        update_sprite();
        if (player.active) {
            gbs_move_sprite(0, player.x, player.y);
        } else {
            gbs_move_sprite(0, 0, SCREEN_HEIGHT);
        }
        gbs_present();
    }
}
