/* Generated by mosaik -> cc65 C backend */
/* Target console: lynx (cc65 tgi-text profile) */
#include <tgi.h>
#include <lynx.h>
#include <joystick.h>
#include <6502.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Text is addressed in character cells (as on Game Boy);
   TGI profiles scale cell coords to pixels. */
#define GBS_CELL_W 8
#define GBS_CELL_H 8

/* Screen geometry for the build target. */
#define SCREEN_WIDTH  160
#define SCREEN_HEIGHT 102
#define SCREEN_COLS   20
#define SCREEN_ROWS   12

/* Input button constants mapped to this console's joypad bits. */
#define INPUT_A      JOY_BTN_1_MASK
#define INPUT_B      JOY_BTN_2_MASK
#define INPUT_SELECT 0
#define INPUT_START  0
#define INPUT_RIGHT  JOY_RIGHT_MASK
#define INPUT_LEFT   JOY_LEFT_MASK
#define INPUT_UP     JOY_UP_MASK
#define INPUT_DOWN   JOY_DOWN_MASK

/* Sprite flip flags -> Suzy SPRCTL0 bits (graphics.sprite). */
#define FLIP_X HFLIP
#define FLIP_Y VFLIP

/* mosaik standard library helpers (cc65) */
static uint8_t gbs_video_ready = 0;
void gbs_video_init(void) {
    if (gbs_video_ready) return;
    tgi_install(tgi_static_stddrv);
    tgi_init();
    CLI();
    joy_install(joy_static_stddrv);
    tgi_setpalette(tgi_getdefpalette());
    tgi_setframerate(60);
    tgi_setviewpage(0);
    tgi_setdrawpage(0);
    tgi_setcolor(COLOR_WHITE);
    tgi_clear();
    gbs_video_ready = 1;
}
void gbs_video_done(void) { joy_uninstall(); tgi_uninstall(); }
/* platform.sound: one square-wave beep channel (counted down
   in gbs_present, 60 ticks/s). */
static uint16_t gbs_snd_frames = 0;
/* Mikey audio channel A. Feedback tap 0 through the inverting XOR
   makes the shift register alternate on every timer underflow ->
   a square wave at clock / (2 * (backup + 1)). */
void gbs_sound_stop(void) {
    MIKEY.channel_a.control = 0;
    MIKEY.channel_a.volume = 0;
    gbs_snd_frames = 0;
}
void gbs_sound_beep(uint16_t freq, uint16_t frames) {
    uint32_t half;       /* half-period in 1 MHz base-clock ticks */
    uint8_t sel = AUD_1;
    if (freq == 0) freq = 1;
    half = 500000UL / freq;
    while (half > 256 && sel < AUD_64) { half >>= 1; ++sel; }
    if (half) --half;    /* timer counts backup+1 ticks */
    MIKEY.channel_a.volume = 0x7F;
    MIKEY.channel_a.feedback = 0x01;  /* tap 0 only */
    MIKEY.channel_a.dac = 0;
    MIKEY.channel_a.shiftlo = 0x01;   /* seed the shift register */
    MIKEY.channel_a.other = 0;
    MIKEY.channel_a.reload = (uint8_t)half;
    MIKEY.channel_a.count = (uint8_t)half;
    MIKEY.channel_a.control = (uint8_t)(ENABLE_RELOAD | ENABLE_COUNT | sel);
    MIKEY.mstereo = 0;   /* Lynx II: all channels to both ears */
    gbs_snd_frames = frames;
}
static uint8_t gbs_force = 1;   /* force the next present (init: first frame) */
static uint8_t gbs_redraw = 0;  /* full re-blits still owed (2 after a change) */

/* --- Suzy hardware sprite engine (Atari Lynx) --- */
#define GBS_MAX_TILES   40
#define GBS_MAX_SPRITES 40
#define GBS_TILE_BYTES  33  /* literal-encoded 8x8 2bpp tile */
static uint8_t gbs_tiles[GBS_MAX_TILES][GBS_TILE_BYTES];
typedef struct { SCB_REHV_PAL s; uint8_t pad_[9]; } gbs_scb_t;
static gbs_scb_t gbs_scb[GBS_MAX_SPRITES];
static uint8_t gbs_spr_tile[GBS_MAX_SPRITES];
static uint8_t gbs_spr_max = 0;     /* highest slot touched + 1 */
static uint8_t gbs_spr_used = 0;    /* engine active this program */
static uint8_t gbs_spr_visible = 1;
static uint8_t gbs_spr_db = 0;      /* double-buffering engaged */
uint8_t gbs_draw_page = 0;    /* page tgi_sprite/text draw to now (tracks the flip) */
static uint8_t gbs_spr_inited = 0;
/* GB 2bpp pixel value 1..3 -> Lynx pens; value 0 -> pen 0 = transparent.
   Packed two pens per byte, lower pixel value in the high nibble. */
static const uint8_t gbs_spr_penpal[8] = {
    (COLOR_TRANSPARENT << 4) | COLOR_LIGHTGREY,   /* pixels 0,1 */
    (COLOR_GREY << 4) | COLOR_WHITE,              /* pixels 2,3 */
    0, 0, 0, 0, 0, 0
};
static void gbs_spr_init(void) {
    uint8_t s, i;
    if (gbs_spr_inited) return;
    for (s = 0; s < GBS_MAX_SPRITES; ++s) {
        gbs_scb[s].s.sprctl0 = BPP_2 | TYPE_NORMAL;
        gbs_scb[s].s.sprctl1 = LITERAL | REHV;  /* literal data, reload h/v size */
        gbs_scb[s].s.sprcoll = 0;
        gbs_scb[s].s.next = (char *)0;
        gbs_scb[s].s.data = gbs_tiles[0];       /* default to tile 0 (as on GB) */
        gbs_scb[s].s.hpos = -16; gbs_scb[s].s.vpos = -16;
        gbs_scb[s].s.hsize = 0x100; gbs_scb[s].s.vsize = 0x100;  /* 1:1 scale */
        for (i = 0; i < 8; ++i) gbs_scb[s].s.penpal[i] = gbs_spr_penpal[i];
    }
    gbs_spr_inited = 1;
    gbs_force = 1;   /* every slot was just laid down */
}
/* Convert one 8x8 GB 2bpp tile (16 bytes) into a literal Lynx sprite. */
static void gbs_conv_tile(uint8_t tile, const uint8_t *gb) {
    uint8_t *o = gbs_tiles[tile];
    uint8_t row, col, lo, hi, bit, ci, a, b;
    for (row = 0; row < 8; ++row) {
        lo = gb[row * 2]; hi = gb[row * 2 + 1];
        a = 0; b = 0;
        for (col = 0; col < 8; ++col) {
            bit = 7 - col;
            ci = (uint8_t)((((hi >> bit) & 1) << 1) | ((lo >> bit) & 1));
            if (col < 4) a = (uint8_t)(a | (ci << ((3 - col) * 2)));
            else         b = (uint8_t)(b | (ci << ((3 - (col - 4)) * 2)));
        }
        *o++ = 0x04; *o++ = a; *o++ = b; *o++ = 0x00;
    }
    *o = 0x00;  /* end of sprite data */
}
void gbs_present(void) {
    uint8_t s;
    if (gbs_snd_frames && --gbs_snd_frames == 0) gbs_sound_stop();
    /* No sprites in use: stay single-buffered so immediate
       (text) drawing persists and does not flicker -- but still
       wait out the frame so wait_vblank paces the main loop.
       The Lynx clock() ticks once per display frame (Mikey
       timer 2, the VBL timer), so CLOCKS_PER_SEC == framerate. */
    if (!gbs_spr_used) {
        clock_t t = clock();
        while (clock() == t) { }
        return;
    }
    /* First sprite frame: switch to true double-buffering so the
       per-frame clear + redraw happens off-screen and the displayed
       page is always a complete frame -- no tearing, and sprites that
       do not move (a fixed HUD, a static-camera scene) stay visible.
       With graphics.bkg this also repositions the row-strip ring each
       frame; moving SCBs is cheap enough to do so every frame. */
    if (!gbs_spr_db) { tgi_setdrawpage(1); gbs_draw_page = 1; gbs_spr_db = 1; }
    {   /* Re-blit until BOTH buffers are current (2 frames after a
       change); a static frame then just flips between the two
       identical buffers. tgi_updatedisplay() still runs EVERY frame
       (the Lynx display needs it -- skipping it blanks the screen),
       but dropping the per-frame recomposite frees the Suzy load that
       intermittently flickered a foreground sprite on Beetle. The
       writers raise gbs_force on a real change (see gbs_move_sprite). */
        if (gbs_force) gbs_redraw = 2;
        gbs_force = 0;
    }
    if (gbs_redraw) {
        --gbs_redraw;
    tgi_setcolor(COLOR_BLACK);
    tgi_bar(0, 0, 159, 101);
    if (gbs_spr_visible) {
        SCB_REHV_PAL *h = 0, *pv = 0;
        gbs_scb_t *q = gbs_scb;   /* walk by pointer (see the sum loop) */
        for (s = 0; s < gbs_spr_max; ++s, ++q) {
            /* Skip fully-offscreen slots: hidden/unused sprites parked
               at the init (-16,-16) or the hide (y=SCREEN_HEIGHT) spot
               would otherwise feed Suzy off-window literal blits, which
               corrupt the frame (the rest of the chain drops out). */
            if (q->s.vpos >= 102 || q->s.hpos >= 160 ||
                q->s.vpos <= -8 || q->s.hpos <= -8) continue;
            if (pv) pv->next = (char *)&q->s; else h = &q->s;
            pv = &q->s;
        }
        /* One Suzy walk for all visible sprites (chained after the bkg). */
        if (pv) { pv->next = (char *)0; tgi_sprite(h); }
    }
        while (tgi_busy()) { }  /* let Suzy finish before the flip */
    }
    tgi_updatedisplay();    /* queue the VBL flip -- ALWAYS (keeps the display alive) */
    /* Wait until the flip actually HAPPENED. tgi_updatedisplay() ==
       tgi_ioctl(4, 1) only QUEUES the swap (sets the driver's
       SWAPREQUEST; the display IRQ consumes it at the next VBL, and the
       driver's draw-buffer pointer moves only then). Returning while it
       is still pending is the double-buffer KILLER: the next frame's
       Suzy blits land in the page just queued for DISPLAY, and that
       frame's own updatedisplay COALESCES into the pending request --
       two logical flips collapse into one physical flip, the page
       parity inverts, and one page goes permanently stale, shown every
       other flip (the whole-screen flicker platform-quest had; a clock()
       tick is NOT a safe wait -- the C-library jiffy and the display
       timer are different IRQ sources at different phases). Polling
       tgi_ioctl(4, 0) reads SWAPREQUEST back, so this waits precisely
       for the swap: page parity holds AND wait_vblank paces the loop at
       the display rate (one flip per display frame), like the GB. */
    while (tgi_ioctl(4, (void*)0)) { }
    gbs_draw_page ^= 1;     /* the flip swapped draw <-> view */
}
void gbs_set_sprite_data(uint8_t first, uint8_t count, const uint8_t *data) {
    uint8_t i;
    gbs_spr_init();
    for (i = 0; i < count; ++i)
        if ((uint8_t)(first + i) < GBS_MAX_TILES)
            gbs_conv_tile((uint8_t)(first + i), data + (uint16_t)i * 16);
    gbs_spr_used = 1;
    gbs_force = 1;   /* new sprite tile data -> present must re-blit */
}
void gbs_set_sprite_tile(uint8_t nb, uint8_t tile) {
    gbs_spr_init();
    if (nb < GBS_MAX_SPRITES && tile < GBS_MAX_TILES) {
        gbs_spr_tile[nb] = tile;
        if (gbs_scb[nb].s.data != gbs_tiles[tile]) {
            gbs_scb[nb].s.data = gbs_tiles[tile]; gbs_force = 1;
        }
        if (nb >= gbs_spr_max) gbs_spr_max = nb + 1;
    }
    gbs_spr_used = 1;
}
uint8_t gbs_get_sprite_tile(uint8_t nb) {
    return nb < GBS_MAX_SPRITES ? gbs_spr_tile[nb] : 0;
}
/* prop carries FLIP_X (HFLIP) / FLIP_Y (VFLIP) for SPRCTL0. */
void gbs_set_sprite_prop(uint8_t nb, uint8_t prop) {
    gbs_spr_init();
    if (nb < GBS_MAX_SPRITES) {
        uint8_t c0 = (uint8_t)((BPP_2 | TYPE_NORMAL) |
            (prop & (HFLIP | VFLIP)));
        if (gbs_scb[nb].s.sprctl0 != c0) { gbs_scb[nb].s.sprctl0 = c0; gbs_force = 1; }
    }
}
/* sprite.move takes screen-pixel coordinates (top-left origin). */
void gbs_move_sprite(uint8_t nb, uint8_t x, uint8_t y) {
    gbs_spr_init();
    if (nb < GBS_MAX_SPRITES) {
        gbs_scb_t *q = &gbs_scb[nb];   /* one subscript, not two */
        if (q->s.hpos != x) { q->s.hpos = x; gbs_force = 1; }
        if (q->s.vpos != y) { q->s.vpos = y; gbs_force = 1; }
        if (nb >= gbs_spr_max) gbs_spr_max = nb + 1;
    }
    gbs_spr_used = 1;
}
void gbs_show_sprites(void) { gbs_spr_used = 1;
    if (!gbs_spr_visible) { gbs_spr_visible = 1; gbs_force = 1; } }
void gbs_hide_sprites(void) {
    if (gbs_spr_visible) { gbs_spr_visible = 0; gbs_force = 1; } }
void gbs_show_bkg(void) { }
uint8_t gbs_input_pressed(uint8_t button) {
    gbs_video_init();
    return (uint8_t)((joy_read(0) |
        (SUZY.joystick & (JOY_UP_MASK | JOY_DOWN_MASK))) & button);
}
/* TGI text draws transparently (pixels OR onto the screen), but the
   Game Boy's tile text *replaces* the cell -- so clear the covered
   cells first to keep reprinting (counters, scores) portable.
   Once the sprite engine engages double-buffering, gbs_present()
   draws the scene + flips, leaving the DRAW page = the one NOT on
   screen; text drawn after present (a dialogue box redrawn each frame)
   would land on the hidden page and show only every other frame ->
   flicker. So draw to BOTH pages while double-buffered (each is a
   complete frame the flip can show), then restore the draw page the
   present expects. Single-buffered (text-only) programs draw once. */
extern uint8_t gbs_draw_page;
void gbs_print_string(uint8_t x, uint8_t y, const char *s) {
    int px = (int)x * GBS_CELL_W, py = (int)y * GBS_CELL_H;
    uint8_t pass;
    gbs_video_init();
    for (pass = 0; ; ++pass) {
        tgi_setcolor(COLOR_BLACK);
        tgi_bar(px, py, px + (int)strlen(s) * GBS_CELL_W - 1, py + GBS_CELL_H - 1);
        tgi_setcolor(COLOR_WHITE);
        tgi_outtextxy(px, py, s);
        if (!gbs_spr_db || pass) break;
        tgi_setdrawpage(gbs_draw_page ^ 1);
    }
    if (gbs_spr_db) tgi_setdrawpage(gbs_draw_page);
}
void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) {
    char buf[7];
    utoa(n, buf, 10);
    gbs_print_string(x, y, buf);
}
void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {
    uint8_t pass;
    gbs_video_init();
    for (pass = 0; ; ++pass) {
        tgi_setcolor(COLOR_BLACK);
        tgi_bar((int)x * GBS_CELL_W, (int)y * GBS_CELL_H,
                (int)(x + w) * GBS_CELL_W - 1, (int)(y + h) * GBS_CELL_H - 1);
        if (!gbs_spr_db || pass) break;
        tgi_setdrawpage(gbs_draw_page ^ 1);
    }
    tgi_setcolor(COLOR_WHITE);
    if (gbs_spr_db) tgi_setdrawpage(gbs_draw_page);
}
/* delay(ms) busy-waits using the system clock, so the granularity is a
   FRAME TICK, not a millisecond. Rounded UP with a 1-tick floor:
   delay(1..16) used to truncate to 0 ticks and return immediately
   (GBDK's delay() is true milliseconds). */
/* THE TICK IS A PRESENTED FRAME, and CLOCKS_PER_SEC does not say so
   on this console: cc65 resolves it at RUNTIME (__clocks_per_sec)
   and it answers 50, while clock() advances once per frame at the
   60 Hz video_init programs -- measured, review E-8. Converting
   against the macro made every delay 20% short. */
void gbs_delay(uint16_t ms) {
    clock_t ticks = ((clock_t)ms * 60 + 999) / 1000;
    clock_t target;
    if (ms > 0 && ticks == 0) ticks = 1;
    target = clock() + ticks;
    while (clock() < target) { }
}
void gbs_seed_random(uint16_t seed) { srand(seed); }
/* Raw hardware register access (addresses are console-specific). */
void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }
uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }

/* Module: hello */

uint16_t counter = 0;

void main(void);

void main(void) {
    gbs_video_init();
    gbs_print_string(2, 2, "MOSAIK");
    gbs_print_string(2, 4, "PRESS A");
    while (1) {
        if (gbs_input_pressed(INPUT_A)) {
            counter += 1;
            gbs_clear_area(2, 6, 8, 1);
            gbs_print_number(2, 6, counter);
        }
        gbs_delay(100);
        gbs_present();
    }
}
