/* Generated by mosaik -> GBDK C backend */
/* Target console: gameboy */
#include <gbdk/platform.h>
#include <gbdk/console.h>
#include <gbdk/font.h>
#include <rand.h>
#include <stdio.h>
#include <stdint.h>

/* Input button constants mapped to GBDK joypad bits */
#define INPUT_A      J_A
#define INPUT_B      J_B
#define INPUT_SELECT J_SELECT
#define INPUT_START  J_START
#define INPUT_RIGHT  J_RIGHT
#define INPUT_LEFT   J_LEFT
#define INPUT_UP     J_UP
#define INPUT_DOWN   J_DOWN

/* Screen geometry for the build target (GBDK resolves the
   DEVICE_* macros per console at C compile time). */
#define SCREEN_WIDTH  DEVICE_SCREEN_PX_WIDTH
#define SCREEN_HEIGHT DEVICE_SCREEN_PX_HEIGHT
#define SCREEN_COLS   DEVICE_SCREEN_WIDTH
#define SCREEN_ROWS   DEVICE_SCREEN_HEIGHT

/* Hardware register addresses (for hw.read / hw.write) */
#define REG_DIV  0xFF04
#define REG_NR10 0xFF10
#define REG_BGP  0xFF47
#define REG_OBP0 0xFF48
#define REG_OBP1 0xFF49

/* Sprite property flags (graphics.sprite) */
#define FLIP_X S_FLIPX
#define FLIP_Y S_FLIPY

/* mosaik standard library helpers */
void gbs_enable_lcd(void) { DISPLAY_ON; SHOW_BKG; }
void gbs_disable_lcd(void) { DISPLAY_OFF; }
uint8_t gbs_input_pressed(uint8_t button) { return (uint8_t)(joypad() & button); }
/* GBDK-2020's console printf needs a font loaded before any text
   tiles are drawn; do it lazily on first use (once). */
void gbs_text_init(void) {
    static uint8_t gbs_font_ready = 0;
    if (!gbs_font_ready) { font_init(); font_set(font_load(font_ibm)); gbs_font_ready = 1; }
}
void gbs_print_string(uint8_t x, uint8_t y, const char *s) { gbs_text_init(); gotoxy(x, y); printf("%s", s); }
void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) { gbs_text_init(); gotoxy(x, y); printf("%d", n); }
void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {
    uint8_t i, j;
    gbs_text_init();
    for (j = 0; j < h; j++) { gotoxy(x, y + j); for (i = 0; i < w; i++) printf(" "); }
}
/* Raw hardware register access (sound, palette, timer, ...) */
void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }
uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }
/* Display visibility helpers (GBDK macros wrapped as functions) */
void gbs_show_sprites(void) { SHOW_SPRITES; }
void gbs_hide_sprites(void) { HIDE_SPRITES; }
void gbs_show_bkg(void) { SHOW_BKG; }
/* sprite.move takes screen-pixel coordinates (origin = top-left of
   the visible screen); the hardware offset differs per console. */
void gbs_move_sprite(uint8_t nb, uint8_t x, uint8_t y) {
    move_sprite(nb, (uint8_t)(x + DEVICE_SPRITE_PX_OFFSET_X),
                    (uint8_t)(y + DEVICE_SPRITE_PX_OFFSET_Y));
}
/* The window layer only exists on Game Boy-family consoles. */
void gbs_show_win(void) { SHOW_WIN; }
void gbs_hide_win(void) { HIDE_WIN; }
/* platform.sound: one square-wave beep channel. */
static uint16_t gbs_snd_frames = 0;
/* Game Boy APU, pulse channel 2 (no sweep). Powering the APU off
   clears every register, so stop() is a single write. */
void gbs_sound_stop(void) { NR52_REG = 0x00; gbs_snd_frames = 0; }
void gbs_sound_beep(uint16_t freq, uint16_t frames) {
    uint16_t period;
    if (freq < 64) freq = 64;  /* APU floor: period must be >= 0 */
    period = (uint16_t)(2048 - (uint16_t)(131072UL / freq));
    NR52_REG = 0x80;  /* APU on */
    NR51_REG = 0xFF;  /* route every channel left + right */
    NR50_REG = 0x77;  /* master volume max */
    NR21_REG = 0x80;  /* 50% duty */
    NR22_REG = 0xF0;  /* full volume, no envelope */
    NR23_REG = (uint8_t)period;
    NR24_REG = 0x80 | (uint8_t)(period >> 8);  /* trigger */
    gbs_snd_frames = frames;
}
/* wait_vblank with the beep-duration countdown (60 ticks/s). */
void gbs_wait_vblank(void) {
    vsync();
    if (gbs_snd_frames && --gbs_snd_frames == 0) gbs_sound_stop();
}

/* Module: hello */

uint16_t counter = 0;

void main(void);

void main(void) {
    gbs_enable_lcd();
    gbs_print_string(2, 2, "MOSAIK");
    gbs_print_string(2, 4, "PRESS A");
    while (1) {
        if (gbs_input_pressed(INPUT_A)) {
            counter += 1;
            gbs_clear_area(2, 6, 8, 1);
            gbs_print_number(2, 6, counter);
        }
        delay(100);
        gbs_wait_vblank();
    }
}
