/* Generated by mosaik -> GBDK C backend */
/* Target console: gameboy */
#include <gbdk/platform.h>
#include <gbdk/console.h>
#include <gbdk/font.h>
#include <rand.h>
#include <stdio.h>
#include <stdint.h>

/* Input button constants mapped to GBDK joypad bits */
#define INPUT_A      J_A
#define INPUT_B      J_B
#define INPUT_SELECT J_SELECT
#define INPUT_START  J_START
#define INPUT_RIGHT  J_RIGHT
#define INPUT_LEFT   J_LEFT
#define INPUT_UP     J_UP
#define INPUT_DOWN   J_DOWN

/* Screen geometry for the build target (GBDK resolves the
   DEVICE_* macros per console at C compile time). */
#define SCREEN_WIDTH  DEVICE_SCREEN_PX_WIDTH
#define SCREEN_HEIGHT DEVICE_SCREEN_PX_HEIGHT
#define SCREEN_COLS   DEVICE_SCREEN_WIDTH
#define SCREEN_ROWS   DEVICE_SCREEN_HEIGHT

/* Hardware register addresses (for hw.read / hw.write) */
#define REG_DIV  0xFF04
#define REG_NR10 0xFF10
#define REG_BGP  0xFF47
#define REG_OBP0 0xFF48
#define REG_OBP1 0xFF49

/* Sprite property flags (graphics.sprite) */
#define FLIP_X S_FLIPX
#define FLIP_Y S_FLIPY

/* mosaik standard library helpers */
void gbs_enable_lcd(void) { DISPLAY_ON; SHOW_BKG; }
void gbs_disable_lcd(void) { DISPLAY_OFF; }
uint8_t gbs_input_pressed(uint8_t button) { return (uint8_t)(joypad() & button); }
/* Text needs a font loaded before any glyph is drawn; do it lazily on
   first use (once). The font glyphs occupy background tile-DATA slots
   (tile = first_tile + ASCII-32), which collides with a game's
   background tileset -- that also grows up from tile 0. GBDK's font
   allocator hands out tiles sequentially from font_init(), so two
   throwaway loads (font_ibm = 96 tiles, then font_min) push the REAL
   font up to tile 139 (measured), reserving 0..138 for the game's tileset and
   leaving the top for animated/extra tiles (the reference-engine 'reserve
   tiles for the font' rule, inverted because GBDK pins the font low). */
uint8_t gbs_font_base = 132;  /* pre-probe default; the probe below finds 139 */
void gbs_text_init(void) {
    static uint8_t gbs_font_ready = 0;
    if (!gbs_font_ready) {
        uint8_t saved;
        font_init();
        font_load(font_ibm);  /* pad: reserve bkg tiles 0..95 */
        font_load(font_min);   /* pad: reserve bkg tiles 96..138 */
        font_set(font_load(font_ibm));  /* active font -> tiles 139..234 */
        /* Learn the active font's first tile rather than assuming it:
           write the ' ' glyph (font index 0), read the tile id back,
           then restore the probed cell. */
        saved = get_bkg_tile_xy(0, 0);
        gotoxy(0, 0); putchar(' ');
        gbs_font_base = get_bkg_tile_xy(0, 0);
        set_bkg_tile_xy(0, 0, saved);
        gbs_font_ready = 1;
    }
}
/* Plot glyphs into the 32x32 bkg map (all cols/rows, & 31) rather than
   gotoxy()+printf() -- printf clamps to the 20-col window and wrapped a
   scrolled box's tail off-screen. */
/* Row-buffered plotting: a 32-cell stage flushed in runs, one tile-map
   call per run instead of per cell (each call waits for VRAM itself).
   A run stops at column 31 - the map wraps there, a write does not. */
static uint8_t gbs_text_row[32];
static void gbs_text_flush(uint8_t x, uint8_t y, uint8_t n) {
    const uint8_t *p = gbs_text_row;
    uint8_t x0 = (uint8_t)(x & 31), n0;
    y = (uint8_t)(y & 31);
    while (n) {
        n0 = (uint8_t)(32 - x0);
        if (n0 > n) n0 = n;
        set_bkg_tiles(x0, y, n0, 1, p);
        p += n0; n = (uint8_t)(n - n0); x0 = 0;
    }
}
void gbs_print_string(uint8_t x, uint8_t y, const char *s) {
    uint8_t n;
    gbs_text_init();
    while (*s) {
        n = 0;
        while (*s && n < 32) { gbs_text_row[n++] = (uint8_t)(gbs_font_base + (uint8_t)(*s - 32)); s++; }
        gbs_text_flush(x, y, n);
        x = (uint8_t)(x + n);
    }
}
void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) {
    static const uint16_t pw[4] = { 10000, 1000, 100, 10 };
    uint8_t k = 0, d, i;
    gbs_text_init();
    for (i = 0; i < 4; ++i) {
        d = 0;
        while (n >= pw[i]) { n -= pw[i]; ++d; }
        if (k || d) gbs_text_row[k++] = (uint8_t)(gbs_font_base + 16 + d);
    }
    gbs_text_row[k++] = (uint8_t)(gbs_font_base + 16 + (uint8_t)n);
    gbs_text_flush(x, y, k);
}
void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {
    uint8_t i, j;
    gbs_text_init();
    if (w > 32) w = 32;  /* the map is 32 wide: wider only re-clears */
    for (i = 0; i < w; i++) gbs_text_row[i] = gbs_font_base;
    for (j = 0; j < h; j++) gbs_text_flush(x, (uint8_t)(y + j), w);
}
/* Raw hardware register access (sound, palette, timer, ...) */
void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }
uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }
/* Display visibility helpers (GBDK macros wrapped as functions) */
void gbs_show_sprites(void) { SHOW_SPRITES; }
void gbs_hide_sprites(void) { HIDE_SPRITES; }
void gbs_show_bkg(void) { SHOW_BKG; }
/* The window layer only exists on Game Boy-family consoles. */
void gbs_show_win(void) { SHOW_WIN; }
void gbs_hide_win(void) { HIDE_WIN; }
/* platform.sound: one square-wave beep channel. */
static uint16_t gbs_snd_frames = 0;
/* Game Boy APU, pulse channel 2 (no sweep). Powering the APU off
   clears every register, so stop() is a single write. */
void gbs_sound_stop(void) { NR52_REG = 0x00; gbs_snd_frames = 0; }
void gbs_sound_beep(uint16_t freq, uint16_t frames) {
    uint16_t period;
    if (freq < 64) freq = 64;  /* APU floor: period must be >= 0 */
    period = (uint16_t)(2048 - (uint16_t)(131072UL / freq));
    NR52_REG = 0x80;  /* APU on */
    NR51_REG = 0xFF;  /* route every channel left + right */
    NR50_REG = 0x77;  /* master volume max */
    NR21_REG = 0x80;  /* 50% duty */
    NR22_REG = 0xF0;  /* full volume, no envelope */
    NR23_REG = (uint8_t)period;
    NR24_REG = 0x80 | (uint8_t)(period >> 8);  /* trigger */
    gbs_snd_frames = frames;
}
/* wait_vblank with the beep-duration countdown (60 ticks/s). */
void gbs_wait_vblank(void) {
    vsync();
    if (gbs_snd_frames && --gbs_snd_frames == 0) gbs_sound_stop();
}

/* Module: hello */

uint16_t counter = 0;

void main(void);

void main(void) {
    gbs_enable_lcd();
    gbs_print_string(2, 2, "MOSAIK");
    gbs_print_string(2, 4, "PRESS A");
    while (1) {
        if (gbs_input_pressed(INPUT_A)) {
            counter += 1;
            gbs_clear_area(2, 6, 8, 1);
            gbs_print_number(2, 6, counter);
        }
        delay(100);
        gbs_wait_vblank();
    }
}
