/* Generated by mosaik -> GBDK C backend */
/* Target console: gameboy */
#include <gbdk/platform.h>
#include <gbdk/console.h>
#include <gbdk/font.h>
#include <rand.h>
#include <stdio.h>
#include <stdint.h>

/* Input button constants mapped to GBDK joypad bits */
#define INPUT_A      J_A
#define INPUT_B      J_B
#define INPUT_SELECT J_SELECT
#define INPUT_START  J_START
#define INPUT_RIGHT  J_RIGHT
#define INPUT_LEFT   J_LEFT
#define INPUT_UP     J_UP
#define INPUT_DOWN   J_DOWN

/* Screen geometry for the build target (GBDK resolves the
   DEVICE_* macros per console at C compile time). */
#define SCREEN_WIDTH  DEVICE_SCREEN_PX_WIDTH
#define SCREEN_HEIGHT DEVICE_SCREEN_PX_HEIGHT
#define SCREEN_COLS   DEVICE_SCREEN_WIDTH
#define SCREEN_ROWS   DEVICE_SCREEN_HEIGHT

/* Hardware register addresses (for hw.read / hw.write) */
#define REG_DIV  0xFF04
#define REG_NR10 0xFF10
#define REG_BGP  0xFF47
#define REG_OBP0 0xFF48
#define REG_OBP1 0xFF49

/* Sprite property flags (graphics.sprite) */
#define FLIP_X S_FLIPX
#define FLIP_Y S_FLIPY

/* mosaik standard library helpers */
void gbs_enable_lcd(void) { DISPLAY_ON; SHOW_BKG; }
void gbs_disable_lcd(void) { DISPLAY_OFF; }
uint8_t gbs_input_pressed(uint8_t button) { return (uint8_t)(joypad() & button); }
/* GBDK-2020's console printf needs a font loaded before any text
   tiles are drawn; do it lazily on first use (once). */
void gbs_text_init(void) {
    static uint8_t gbs_font_ready = 0;
    if (!gbs_font_ready) { font_init(); font_set(font_load(font_ibm)); gbs_font_ready = 1; }
}
void gbs_print_string(uint8_t x, uint8_t y, const char *s) { gbs_text_init(); gotoxy(x, y); printf("%s", s); }
void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) { gbs_text_init(); gotoxy(x, y); printf("%d", n); }
void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {
    uint8_t i, j;
    gbs_text_init();
    for (j = 0; j < h; j++) { gotoxy(x, y + j); for (i = 0; i < w; i++) printf(" "); }
}
/* Raw hardware register access (sound, palette, timer, ...) */
void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }
uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }
/* Display visibility helpers (GBDK macros wrapped as functions) */
void gbs_show_sprites(void) { SHOW_SPRITES; }
void gbs_hide_sprites(void) { HIDE_SPRITES; }
void gbs_show_bkg(void) { SHOW_BKG; }
/* sprite.move takes screen-pixel coordinates (origin = top-left of
   the visible screen); the hardware offset differs per console. */
void gbs_move_sprite(uint8_t nb, uint8_t x, uint8_t y) {
    move_sprite(nb, (uint8_t)(x + DEVICE_SPRITE_PX_OFFSET_X),
                    (uint8_t)(y + DEVICE_SPRITE_PX_OFFSET_Y));
}
/* The window layer only exists on Game Boy-family consoles. */
void gbs_show_win(void) { SHOW_WIN; }
void gbs_hide_win(void) { HIDE_WIN; }

/* Module: pong */

const uint8_t TILES[32] = {60, 60, 126, 126, 255, 255, 255, 255, 255, 255, 255, 255, 126, 126, 60, 60, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255};
#define PADDLE_X (16)
#define PADDLE_FACE (24)
#define PADDLE_HEIGHT (24)
#define PADDLE_TOP (4)
#define PADDLE_BOTTOM ((SCREEN_HEIGHT - 28))
#define WALL_TOP (4)
#define WALL_BOTTOM ((SCREEN_HEIGHT - 12))
#define WALL_RIGHT ((SCREEN_WIDTH - 12))

uint8_t paddle_y = 64;
uint8_t ball_x = (SCREEN_WIDTH / 2);
uint8_t ball_y = (SCREEN_HEIGHT / 2);
int8_t ball_dx = (-2);
int8_t ball_dy = 2;

void update_paddle(void);
void update_ball(void);
void draw(void);
void main(void);

void update_paddle(void) {
    if ((gbs_input_pressed(INPUT_UP) && (paddle_y > PADDLE_TOP))) {
        paddle_y -= 2;
    }
    if ((gbs_input_pressed(INPUT_DOWN) && (paddle_y < PADDLE_BOTTOM))) {
        paddle_y += 2;
    }
}

void update_ball(void) {
    ball_x += ball_dx;
    ball_y += ball_dy;
    if ((ball_y <= WALL_TOP)) {
        ball_y = WALL_TOP;
        ball_dy = (-ball_dy);
    }
    if ((ball_y >= WALL_BOTTOM)) {
        ball_y = WALL_BOTTOM;
        ball_dy = (-ball_dy);
    }
    if ((ball_x >= WALL_RIGHT)) {
        ball_x = WALL_RIGHT;
        ball_dx = (-ball_dx);
    }
    if ((ball_x <= PADDLE_FACE)) {
        if (((ball_y >= paddle_y) && (ball_y <= (paddle_y + PADDLE_HEIGHT)))) {
            ball_x = PADDLE_FACE;
            ball_dx = (-ball_dx);
        } else {
            ball_x = (SCREEN_WIDTH / 2);
            ball_y = (SCREEN_HEIGHT / 2);
            ball_dx = (-2);
            ball_dy = 2;
        }
    }
}

void draw(void) {
    gbs_move_sprite(0, ball_x, ball_y);
    gbs_move_sprite(1, PADDLE_X, paddle_y);
    gbs_move_sprite(2, PADDLE_X, (paddle_y + 8));
    gbs_move_sprite(3, PADDLE_X, (paddle_y + 16));
}

void main(void) {
    set_sprite_data(0, 2, TILES);
    set_sprite_tile(0, 0);
    set_sprite_tile(1, 1);
    set_sprite_tile(2, 1);
    set_sprite_tile(3, 1);
    draw();
    gbs_enable_lcd();
    gbs_show_sprites();
    while (1) {
        update_paddle();
        update_ball();
        draw();
        vsync();
    }
}
