#!/usr/bin/env python3
"""vm-boxtest UI-asset generator.

Encodes the custom 9-slice FRAME (frame.png, 3x3 tiles) + custom FONT (font.png,
96 glyphs) -- both drawn by projects/bigworld-paint/assets/gen_ui_art.py, which
writes the same pair into both projects -- to GB 2bpp,
BRIGHTNESS-RANKED (lightest palette colour -> 2bpp 0 = paper, darkest -> 3 = ink)
so they render with contrast under ANY background palette. This is the same
inline-ranked encode the studio's composed custom font / frame use (byte-identical
to bigworld-paint / ui-quest). Emits src/uidata.mos.

    python projects/vm-boxtest/assets/gen.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "uidata.mos")


def _luma(rgb):
    r, g, b = rgb
    return 0.299 * r + 0.587 * g + 0.114 * b


def encode_ui_tiles(png_path, max_tiles=None):
    from PIL import Image
    im = Image.open(png_path).convert("P")
    pal = im.getpalette()
    w, h = im.size
    px = im.load()
    used = sorted({px[x, y] for y in range(h) for x in range(w)})
    light = sorted(used, key=lambda idx: _luma(pal[idx * 3:idx * 3 + 3]), reverse=True)
    n = len(light)
    rank = {idx: (round(i * 3 / (n - 1)) if n > 1 else 0) for i, idx in enumerate(light)}
    out, cnt = [], 0
    for ty in range(h // 8):
        for tx in range(w // 8):
            if max_tiles and cnt >= max_tiles:
                break
            for row in range(8):
                b0 = b1 = 0
                for col in range(8):
                    v = rank[px[tx * 8 + col, ty * 8 + row]]
                    b0 |= (v & 1) << (7 - col)
                    b1 |= ((v >> 1) & 1) << (7 - col)
                out += [b0, b1]
            cnt += 1
    return out


def _emit_array(name, data, indent):
    lines = ["%sconst %s: array[u8, %d] = [" % (indent, name, len(data))]
    for i in range(0, len(data), 16):
        row = ", ".join(str(b) for b in data[i:i + 16])
        lines.append("%s    %s," % (indent, row))
    lines[-1] = lines[-1].rstrip(",")
    lines.append("%s]" % indent)
    return lines


def main():
    font = encode_ui_tiles(os.path.join(HERE, "font.png"), max_tiles=96)
    frame = encode_ui_tiles(os.path.join(HERE, "frame.png"))
    L = [
        "-- uidata.mos -- GENERATED by assets/gen.py; do not edit by hand.",
        "-- The custom 9-slice FRAME (9 tiles) + custom FONT (96 glyphs), inline +",
        "-- brightness-ranked, from the frame/font PNGs gen_ui_art.py draws.",
        "",
        'module "uidata" {',
    ]
    # The custom font + frame are GB-family-only tile/font DATA (the Lynx frames via
    # text.fill_box and keeps its built-in font). Define them platform-conditionally
    # so the ~1.7 KB of data emits a 16-byte STUB on the Lynx/PCE/NES -- a bare full
    # const would NOT tree-shake there (it is referenced from a conditional-compiled
    # branch) and would overflow the tight Lynx MAIN. Same idiom as bigworld-paint.
    L.append('    -- Custom font + 9-slice frame, inline brightness-ranked 2bpp')
    L.append('    -- (drawn by bigworld-paint/assets/gen_ui_art.py). GB family only; the Lynx/')
    L.append('    -- PCE/NES get a 16-byte STUB (unused there -- keeps their MAIN small).')
    L.append('    if platform == "lynx" or platform == "pce" or platform == "nes" {')
    L += _emit_array("FONT_TILES", [0] * 16, "        ")
    L += _emit_array("FRAME_TILES", [0] * 16, "        ")
    L.append('    } else {')
    L += _emit_array("FONT_TILES", font, "        ")
    L += _emit_array("FRAME_TILES", frame, "        ")
    L.append('    }')
    L.append("")
    L.append("    export FONT_TILES, FRAME_TILES")
    L.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", os.path.normpath(OUT), "(font %d B, frame %d B)" % (len(font), len(frame)))


if __name__ == "__main__":
    main()
