#!/usr/bin/env python3
"""Generate vm-shop -- the VM8 SHOP proof.

The Stage-4 gap analysis asks whether a classic GB-RPG shop is expressible as EVENT
SCRIPTS over the `menu` op + heap vars (no new engine module). It is: the keeper
NPC's On Interact spawns a LOOPING `shop` script (loop=true, which jumps back to its
own start) that opens a Buy/Sell/Leave menu, branches on the picked index (switch),
spends the `gold` heap var into `potions`/`ethers` counters (guarded on affordability),
sells them back at half price, and TERMINATES (stop) when Leave is picked. A guard
heap var (`shop_lock`) locks the player ONCE for the whole session (a loop re-runs the
top each iteration, so an unguarded `lock` would grow the lock count).

Author the game as DATA: world.toml (a field + player + keeper) + scripts/*.evt.toml
(the boot gold grant + the shop state machine), then the transpilers emit
src/scenes.mos + src/scripts.mos. Run:
  python projects/vm-shop/assets/gen_world.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PROJ))
sys.path.insert(0, ROOT)           # so `import mosaik_assets` resolves

W, H = 12, 9                       # tiles per room (96 x 72 px, fits every screen)


def room():
    """A bordered floor room + its parallel collision layer (1 = SOLID walls)."""
    tiles, coll = [], []
    for y in range(H):
        trow, crow = [], []
        for x in range(W):
            wall = x == 0 or y == 0 or x == W - 1 or y == H - 1
            trow.append(1 if wall else 0)
            crow.append(1 if wall else 0)
        tiles.append(trow)
        coll.append(crow)
    return tiles, coll


def rows(grid):
    return "[" + ", ".join("[" + ",".join(str(v) for v in r) + "]" for r in grid) + "]"


def main():
    field_t, field_c = room()

    from mosaik_assets import write_png_indexed
    pal = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    os.makedirs(os.path.join(PROJ, "assets"), exist_ok=True)
    # 2 tiles: 0 floor (white), 1 wall (black).
    write_png_indexed(os.path.join(PROJ, "assets", "tiles.png"), 8, 16,
                      [0] * 64 + [3] * 64, pal)

    # ---- world.toml (a field + the player + the keeper) ----
    world = []
    world.append("# vm-shop -- GENERATED by assets/gen_world.py (edit that + rerun).")
    world.append('[[scene]]')
    world.append('name = "field"')
    world.append("map = %s" % rows(field_t))
    world.append("collision = %s" % rows(field_c))
    # the player start (bottom centre) + the keeper NPC (upper centre)
    world.append('[[scene.object]]\nkind = "player"\nid = 0\nx = 48\ny = 48')
    world.append('[[scene.object]]\nkind = "keeper"\nid = 1\nx = 48\ny = 24'
                 '\non_interact = "shop"')
    world.append("")
    world.append('[world]\nmodule = "scenes"\nmap_w = %d\nmap_h = %d\nvm = true'
                 '\nnext_object_id = 2' % (W, H))
    world.append('[tileset]\npng = "assets/tiles.png"')
    world.append('[kinds]\nplayer = 0\nkeeper = 1')
    with open(os.path.join(PROJ, "world.toml"), "w", encoding="utf-8") as f:
        f.write("\n".join(world) + "\n")

    # ---- scripts/*.evt.toml (the shop state machine as event lists) ----
    os.makedirs(os.path.join(PROJ, "scripts"), exist_ok=True)
    events = '''# vm-shop logic -- the VM8 event lists (the reference engine's project-file analogue).
# main: boot the economy (grant starting gold).
# shop: a LOOPING (loop=true) Buy/Sell/Leave menu -- the classic GB-RPG shop as a
#       script state machine over the `menu` op + heap vars. `shop_lock` locks the
#       player ONCE for the whole session; Leave unlocks + stops (ends the thread).

[[script]]
name = "main"
events = [
  { event = "set_var", var = "gold", value = 20 },
  { event = "stop" },
]

# The looping shop menu. Each choice calls a transaction sub-script (the `toml`
# lib mis-tracks inline tables nested past ~2 levels, so the buy/sell branch lives
# in a sub, not inline in the switch case -- which also demonstrates CALL/RET).
[[script]]
name = "shop"
loop = true
events = [
  { event = "if", cond = "shop_lock == 0", then = [ { event = "lock" }, { event = "set_var", var = "shop_lock", value = 1 } ] },
  { event = "menu", var = "choice", row = 4, options = ["BUY POTION 5", "BUY ETHER 8", "SELL POTION", "LEAVE"] },
  { event = "switch", value = "choice", cases = [
      { value = 0, then = [ { event = "call", script = "buy_potion" } ] },
      { value = 1, then = [ { event = "call", script = "buy_ether" } ] },
      { value = 2, then = [ { event = "call", script = "sell_potion" } ] },
    ],
    default = [
      { event = "text", string = "COME AGAIN!" },
      { event = "unlock" },
      { event = "set_var", var = "shop_lock", value = 0 },
      { event = "stop" },
    ] },
]

[[script]]
name = "buy_potion"
sub = true
events = [
  { event = "if", cond = "gold >= 5",
    then = [
      { event = "set_var", var = "gold", expr = "gold - 5" },
      { event = "set_var", var = "potions", expr = "potions + 1" },
      { event = "text", string = "BOUGHT A POTION!" },
    ],
    else = [ { event = "text", string = "NEED 5 GOLD." } ] },
]

[[script]]
name = "buy_ether"
sub = true
events = [
  { event = "if", cond = "gold >= 8",
    then = [
      { event = "set_var", var = "gold", expr = "gold - 8" },
      { event = "set_var", var = "ethers", expr = "ethers + 1" },
      { event = "text", string = "BOUGHT AN ETHER!" },
    ],
    else = [ { event = "text", string = "NEED 8 GOLD." } ] },
]

[[script]]
name = "sell_potion"
sub = true
events = [
  { event = "if", cond = "potions >= 1",
    then = [
      { event = "set_var", var = "potions", expr = "potions - 1" },
      { event = "set_var", var = "gold", expr = "gold + 2" },
      { event = "text", string = "SOLD A POTION." },
    ],
    else = [ { event = "text", string = "NO POTIONS." } ] },
]
'''
    with open(os.path.join(PROJ, "scripts", "main.evt.toml"), "w",
              encoding="utf-8") as f:
        f.write(events)

    # ---- transpile: world.toml -> src/scenes.mos ; events -> src/scripts.mos ----
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_scenes.py"),
                    os.path.join(PROJ, "world.toml"),
                    "-o", os.path.join(PROJ, "src", "scenes.mos")], check=True, cwd=ROOT)
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_vm.py"),
                    os.path.join(PROJ, "scripts"),
                    "-o", os.path.join(PROJ, "src", "scripts.mos")], check=True, cwd=ROOT)
    print("vm-shop generated (world.toml + scripts + src/scenes.mos + src/scripts.mos)")


if __name__ == "__main__":
    main()
