#!/usr/bin/env python3
"""Generate vm-combat -- the VM8 COMBAT-KIT proof.

A one-room arena: a player + two enemies that CHASE. Swing the sword (B) facing an
enemy to kill it (2 HP each); contact costs the player a heart (i-frames); 0 hearts
reloads the arena. Combat is NATIVE (vm.combat over the shared actor pool, reusing
genre.combat's math); the HUD is engine.hud hearts. All the game DATA is world.toml
(placements) + a do-nothing boot script -- the fight is engine, not bytecode.

  python projects/vm-combat/assets/gen_world.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PROJ))
sys.path.insert(0, ROOT)

W, H = 12, 9


def room():
    tiles, coll = [], []
    for y in range(H):
        trow, crow = [], []
        for x in range(W):
            wall = x == 0 or y == 0 or x == W - 1 or y == H - 1
            trow.append(1 if wall else 0)
            crow.append(1 if wall else 0)
        tiles.append(trow)
        coll.append(crow)
    return tiles, coll


def rows(g):
    return "[" + ", ".join("[" + ",".join(str(v) for v in r) + "]" for r in g) + "]"


def main():
    t, c = room()
    from mosaik_assets import write_png_indexed
    pal = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    os.makedirs(os.path.join(PROJ, "assets"), exist_ok=True)
    write_png_indexed(os.path.join(PROJ, "assets", "tiles.png"), 8, 16,
                      [0] * 64 + [3] * 64, pal)

    world = [
        "# vm-combat -- GENERATED by assets/gen_world.py.",
        '[[scene]]', 'name = "arena"',
        "map = %s" % rows(t), "collision = %s" % rows(c),
        '[[scene.object]]\nkind = "player"\nid = 0\nx = 48\ny = 56',
        '[[scene.object]]\nkind = "enemy"\nid = 1\nx = 24\ny = 24',
        '[[scene.object]]\nkind = "enemy"\nid = 2\nx = 72\ny = 24',
        "",
        '[world]\nmodule = "scenes"\nmap_w = %d\nmap_h = %d\nvm = true'
        '\nnext_object_id = 3' % (W, H),
        '[tileset]\npng = "assets/tiles.png"',
        '[kinds]\nplayer = 0\nenemy = 1',
    ]
    with open(os.path.join(PROJ, "world.toml"), "w", encoding="utf-8") as f:
        f.write("\n".join(world) + "\n")

    os.makedirs(os.path.join(PROJ, "scripts"), exist_ok=True)
    with open(os.path.join(PROJ, "scripts", "main.evt.toml"), "w",
              encoding="utf-8") as f:
        f.write('# Combat is native (vm.combat); the boot script does nothing.\n'
                '[[script]]\nname = "main"\nevents = [ { event = "stop" } ]\n')

    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_scenes.py"),
                    os.path.join(PROJ, "world.toml"),
                    "-o", os.path.join(PROJ, "src", "scenes.mos")], check=True, cwd=ROOT)
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_vm.py"),
                    os.path.join(PROJ, "scripts"),
                    "-o", os.path.join(PROJ, "src", "scripts.mos")], check=True, cwd=ROOT)
    print("vm-combat generated")


if __name__ == "__main__":
    main()
