"""GBDK backend: prelude + stdlib lowering map (mixin for CodeGenerator)."""


class GbdkBackend:
    """GBDK-specific codegen: the stdlib call map and C prelude.

    Mixed into CodeGenerator; all methods run against the full generator
    instance (self.emit, self.caps, self.platform, ...).
    """

    # mosaik stdlib calls -> C helper / GBDK function names.
    STDLIB_CALLS_GBDK = {
        ('video', 'enable_lcd'): 'gbs_enable_lcd',
        ('video', 'disable_lcd'): 'gbs_disable_lcd',
        ('video', 'wait_vblank'): 'vsync',
        ('input', 'pressed'): 'gbs_input_pressed',
        ('input', 'held'): 'gbs_input_pressed',
        ('text', 'print_string'): 'gbs_print_string',
        ('text', 'print_number'): 'gbs_print_number',
        ('text', 'clear_area'): 'gbs_clear_area',
        ('hw', 'write'): 'gbs_hw_write',
        ('hw', 'read'): 'gbs_hw_read',
        # Display visibility (macros, wrapped as helpers).
        ('video', 'show_sprites'): 'gbs_show_sprites',
        ('video', 'hide_sprites'): 'gbs_hide_sprites',
        ('video', 'show_background'): 'gbs_show_bkg',
        ('video', 'show_window'): 'gbs_show_win',
        ('video', 'hide_window'): 'gbs_hide_win',
        # Sprites (graphics.sprite). sprite.move takes screen-pixel coords;
        # the gbs_ wrapper adds the per-console hardware offset.
        ('sprite', 'set_data'): 'set_sprite_data',
        ('sprite', 'set_tile'): 'set_sprite_tile',
        ('sprite', 'get_tile'): 'get_sprite_tile',
        ('sprite', 'set_prop'): 'set_sprite_prop',
        ('sprite', 'move'): 'gbs_move_sprite',
        # Background (graphics.bkg).
        ('bkg', 'set_data'): 'set_bkg_data',
        ('bkg', 'set_tiles'): 'set_bkg_tiles',
        ('bkg', 'scroll'): 'scroll_bkg',
        ('bkg', 'move'): 'move_bkg',
        # Window (graphics.window).
        ('window', 'set_tiles'): 'set_win_tiles',
        ('window', 'move'): 'move_win',
        # System utilities (platform.system).
        ('system', 'delay'): 'delay',
        ('system', 'random'): 'rand',
        ('system', 'seed_random'): 'initrand',
    }

    def _emit_prelude_gbdk(self):
        self.emit("/* Generated by mosaik -> GBDK C backend */")
        self.emit("/* Target console: %s */" % self.platform)
        # <gbdk/platform.h> pulls in the correct console header for the build
        # target (Game Boy, Pocket, Mega Duck, SMS/GG, NES), so the same
        # generated C compiles for every supported platform.
        self.emit("#include <gbdk/platform.h>")
        self.emit("#include <gbdk/console.h>")
        self.emit("#include <gbdk/font.h>")
        self.emit("#include <rand.h>")
        self.emit("#include <stdio.h>")
        self.emit("#include <stdint.h>")
        self.emit("")
        self.emit("/* Input button constants mapped to GBDK joypad bits */")
        self.emit("#define INPUT_A      J_A")
        self.emit("#define INPUT_B      J_B")
        self.emit("#define INPUT_SELECT J_SELECT")
        self.emit("#define INPUT_START  J_START")
        self.emit("#define INPUT_RIGHT  J_RIGHT")
        self.emit("#define INPUT_LEFT   J_LEFT")
        self.emit("#define INPUT_UP     J_UP")
        self.emit("#define INPUT_DOWN   J_DOWN")
        self.emit("")
        self.emit("/* Screen geometry for the build target (GBDK resolves the")
        self.emit("   DEVICE_* macros per console at C compile time). */")
        self.emit("#define SCREEN_WIDTH  DEVICE_SCREEN_PX_WIDTH")
        self.emit("#define SCREEN_HEIGHT DEVICE_SCREEN_PX_HEIGHT")
        self.emit("#define SCREEN_COLS   DEVICE_SCREEN_WIDTH")
        self.emit("#define SCREEN_ROWS   DEVICE_SCREEN_HEIGHT")
        self.emit("")
        if self.caps['has_gb_regs']:
            self.emit("/* Hardware register addresses (for hw.read / hw.write) */")
            self.emit("#define REG_DIV  0xFF04")
            self.emit("#define REG_NR10 0xFF10")
            self.emit("#define REG_BGP  0xFF47")
            self.emit("#define REG_OBP0 0xFF48")
            self.emit("#define REG_OBP1 0xFF49")
            self.emit("")
        self.emit("/* Sprite property flags (graphics.sprite) */")
        self.emit("#define FLIP_X S_FLIPX")
        self.emit("#define FLIP_Y S_FLIPY")
        self.emit("")
        self.emit("/* mosaik standard library helpers */")
        self.emit("void gbs_enable_lcd(void) { DISPLAY_ON; SHOW_BKG; }")
        self.emit("void gbs_disable_lcd(void) { DISPLAY_OFF; }")
        self.emit("uint8_t gbs_input_pressed(uint8_t button) { return (uint8_t)(joypad() & button); }")
        self.emit("/* GBDK-2020's console printf needs a font loaded before any text")
        self.emit("   tiles are drawn; do it lazily on first use (once). */")
        self.emit("void gbs_text_init(void) {")
        self.emit("    static uint8_t gbs_font_ready = 0;")
        self.emit("    if (!gbs_font_ready) { font_init(); font_set(font_load(font_ibm)); gbs_font_ready = 1; }")
        self.emit("}")
        self.emit("void gbs_print_string(uint8_t x, uint8_t y, const char *s) { gbs_text_init(); gotoxy(x, y); printf(\"%s\", s); }")
        self.emit("void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) { gbs_text_init(); gotoxy(x, y); printf(\"%d\", n); }")
        self.emit("void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {")
        self.emit("    uint8_t i, j;")
        self.emit("    gbs_text_init();")
        self.emit("    for (j = 0; j < h; j++) { gotoxy(x, y + j); for (i = 0; i < w; i++) printf(\" \"); }")
        self.emit("}")
        self.emit("/* Raw hardware register access (sound, palette, timer, ...) */")
        self.emit("void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }")
        self.emit("uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }")
        self.emit("/* Display visibility helpers (GBDK macros wrapped as functions) */")
        self.emit("void gbs_show_sprites(void) { SHOW_SPRITES; }")
        self.emit("void gbs_hide_sprites(void) { HIDE_SPRITES; }")
        self.emit("void gbs_show_bkg(void) { SHOW_BKG; }")
        self.emit("/* sprite.move takes screen-pixel coordinates (origin = top-left of")
        self.emit("   the visible screen); the hardware offset differs per console. */")
        self.emit("void gbs_move_sprite(uint8_t nb, uint8_t x, uint8_t y) {")
        self.emit("    move_sprite(nb, (uint8_t)(x + DEVICE_SPRITE_PX_OFFSET_X),")
        self.emit("                    (uint8_t)(y + DEVICE_SPRITE_PX_OFFSET_Y));")
        self.emit("}")
        if self.caps['has_window']:
            self.emit("/* The window layer only exists on Game Boy-family consoles. */")
            self.emit("void gbs_show_win(void) { SHOW_WIN; }")
            self.emit("void gbs_hide_win(void) { HIDE_WIN; }")
        self.emit("")
