"""BATCH sprite verbs for the GBDK backend: whole pools in one native call.

A GbdkBackend concern mixin - methods run against the full CodeGenerator
instance (self.emit, self.caps, ...).

WHY THEY EXIST. A shooter keeps POOLS - bullets, shots, swarms - and does the
same three things to every entry every frame: move it, draw it, test it. In
compiled C each of those is a loop of calls: `sprite.move` alone costs about
1,300 cycles on the Game Boy once the metasprite layer is linked, so sixteen
bullets cost a third of a frame before anything else has happened. These
verbs do a whole pool in one tight loop:

    sprite.plot(first, n, xs, ys, cols)
        place n entries on hardware sprites first, first+1, ...: entry i sits
        at (xs[i], ys[i]) in SCREEN pixels and is `cols` sprites wide (side by
        side, 8 px apart), so it owns `cols` consecutive sprites. Plain
        hardware sprites only - it bypasses the metasprite layer.
    sprite.drift(pos, vel, n)
        pos[i] += vel[i] for n bytes (wrapping, so a velocity of 255 is -1).
    sprite.hit_box(x, y, w, h)  then  sprite.hit(xs, ys, n) -> u8
        the index of the first entry with x <= xs[i] < x + w and
        y <= ys[i] < y + h (all wrapping bytes), or 255. One box, many scans.

`xs` / `ys` / `vel` are plain byte arrays - structure-of-arrays, which is
what makes the loops this short. An entry is "off" simply by being parked
off screen (y = 224 is hidden on every console here), so there is no flag to
test in the hot loop.

Cost per entry, Game Boy machine cycles (Z80 T-states on SMS / Game Gear):
plot 32 (about 100) for one sprite per entry and 54 for two, drift 12 (46),
hit 16-28 (60-110).

Assembly on the GB family and SMS / Game Gear; a portable C loop elsewhere.
The assembly never takes arguments in registers: C stores them in statics
and calls a parameterless NAKED routine, so it does not depend on which
calling convention this sdcc uses.
"""


class GbdkBatchMixin:
    def _batch_asm(self):
        return bool(self.caps.get('has_gb_regs')) or self.platform in ('sms', 'gamegear')

    def _emit_gbdk_batch_protos(self):
        emit = self.emit
        if not self._batch_asm():
            emit("void gbs_spr_plot(uint8_t first, uint8_t n, const uint8_t *xs,")
            emit("                  const uint8_t *ys, uint8_t cols);")
            emit("void gbs_spr_drift(uint8_t *pos, const uint8_t *vel, uint8_t n);")
            emit("void gbs_spr_hit_box(uint8_t x, uint8_t y, uint8_t w, uint8_t h);")
            emit("uint8_t gbs_spr_hit(const uint8_t *xs, const uint8_t *ys, uint8_t n);")
            return
        # The verbs are MACROS here: the arguments go straight into the
        # statics the assembly reads. As a C function the same hand-over was
        # about 250 machine cycles of stack shuffling per call under sdcc -
        # more than drawing eight bullets - and a shooter makes twenty of
        # these calls a frame. With constant arguments (the usual case: an
        # array name, a pool size) each store is a single load.
        emit("/* ---- batch sprite verbs (sprite.plot / drift / hit) ---- */")
        emit("extern const uint8_t *gbs_bt_a, *gbs_bt_b;")
        emit("extern uint8_t *gbs_bt_d, *gbs_bt_e;")
        emit("extern uint8_t gbs_bt_n, gbs_bt_r;")
        emit("extern uint8_t gbs_bt_box[4];")
        emit("void gbs_bt_plot1(void);")
        emit("void gbs_bt_plot2(void);")
        emit("void gbs_bt_drift(void);")
        emit("void gbs_bt_hit(void);")
        emit("void gbs_spr_plotn(uint8_t first, uint8_t n, const uint8_t *xs,")
        emit("                   const uint8_t *ys, uint8_t cols);")
        emit("#define gbs_spr_hit_box(x, y, w, h) (gbs_bt_box[0] = (x), \\")
        emit("    gbs_bt_box[1] = (w), gbs_bt_box[2] = (y), gbs_bt_box[3] = (h))")
        emit("#define gbs_spr_drift(pos, vel, n) (gbs_bt_d = (pos), \\")
        emit("    gbs_bt_a = (vel), gbs_bt_n = (n), gbs_bt_drift())")
        emit("#define gbs_spr_hit(xs, ys, n) (gbs_bt_a = (xs), gbs_bt_b = (ys), \\")
        emit("    gbs_bt_n = (n), gbs_bt_hit(), gbs_bt_r)")
        if self.caps.get('has_gb_regs'):
            dest = "gbs_bt_d = (uint8_t *)&shadow_OAM[first]"
        else:
            dest = ("gbs_bt_d = (uint8_t *)shadow_OAM + (first), "
                    "gbs_bt_e = (uint8_t *)shadow_OAM + 0x40 + (uint8_t)((first) << 1)")
        emit("#define gbs_spr_plot(first, n, xs, ys, cols) (gbs_bt_a = (xs), \\")
        emit("    gbs_bt_b = (ys), %s, \\" % dest)
        emit("    gbs_bt_n = (n), ((cols) == 1 ? gbs_bt_plot1() : \\")
        emit("    (cols) == 2 ? gbs_bt_plot2() : gbs_spr_plotn(first, n, xs, ys, cols)))")

    def _emit_gbdk_batch(self):
        if self.caps.get('has_gb_regs'):
            self._emit_batch_sm83()
        elif self.platform in ('sms', 'gamegear'):
            self._emit_batch_z80()
        else:
            self._emit_batch_c()

    def _emit_batch_state(self):
        emit = self.emit
        self._emit_gbdk_batch_protos()      # the macros, for this unit too
        emit("/* ---- batch sprite verbs (sprite.plot / drift / hit) ----")
        emit("   Arguments travel in statics (stored by the macros in the prototype")
        emit("   block): the assembly below is parameterless. A count of 0 is a no-op. */")
        emit("const uint8_t *gbs_bt_a, *gbs_bt_b;   /* two source arrays */")
        emit("uint8_t *gbs_bt_d, *gbs_bt_e;         /* destinations */")
        emit("uint8_t gbs_bt_n, gbs_bt_r;           /* count, result */")
        emit("uint8_t gbs_bt_box[4];                /* x, w, y, h */")

    # ------------------------------------------------------------- GB family
    def _emit_batch_sm83(self):
        emit = self.emit
        self._emit_batch_state()
        emit("void gbs_bt_plot1(void) NAKED {")
        emit("__asm")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, #_gbs_bt_a")
        emit("        ld a, (hl+)")
        emit("        ld c, a")
        emit("        ld b, (hl)              ; bc = xs")
        emit("        ld hl, #_gbs_bt_b")
        emit("        ld a, (hl+)")
        emit("        ld e, a")
        emit("        ld d, (hl)              ; de = ys")
        emit("        ld hl, #_gbs_bt_d")
        emit("        ld a, (hl+)")
        emit("        ld h, (hl)")
        emit("        ld l, a                 ; hl = the first OAM entry")
        emit("1$:")
        emit("        ld a, (de)")
        emit("        inc de")
        emit("        add a, #16              ; DEVICE_SPRITE_PX_OFFSET_Y")
        emit("        ld (hl+), a")
        emit("        ld a, (bc)")
        emit("        inc bc")
        emit("        add a, #8               ; DEVICE_SPRITE_PX_OFFSET_X")
        emit("        ld (hl+), a")
        emit("        inc hl")
        emit("        inc hl                  ; tile and attributes stay")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        dec a")
        emit("        ld (#_gbs_bt_n), a")
        emit("        jr nz, 1$")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")
        emit("/* Two sprites side by side per entry (a 16 px wide enemy). */")
        emit("void gbs_bt_plot2(void) NAKED {")
        emit("__asm")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, #_gbs_bt_a")
        emit("        ld a, (hl+)")
        emit("        ld c, a")
        emit("        ld b, (hl)              ; bc = xs")
        emit("        ld hl, #_gbs_bt_b")
        emit("        ld a, (hl+)")
        emit("        ld e, a")
        emit("        ld d, (hl)              ; de = ys")
        emit("        ld hl, #_gbs_bt_d")
        emit("        ld a, (hl+)")
        emit("        ld h, (hl)")
        emit("        ld l, a")
        emit("1$:")
        emit("        ld a, (de)")
        emit("        inc de")
        emit("        add a, #16")
        emit("        ld (hl+), a             ; y of the left sprite")
        emit("        inc hl")
        emit("        inc hl")
        emit("        inc hl")
        emit("        ld (hl-), a             ; y of the right one")
        emit("        dec hl")
        emit("        dec hl")
        emit("        ld a, (bc)")
        emit("        inc bc")
        emit("        add a, #8")
        emit("        ld (hl+), a             ; x of the left sprite")
        emit("        inc hl")
        emit("        inc hl")
        emit("        inc hl")
        emit("        add a, #8")
        emit("        ld (hl+), a             ; x of the right one")
        emit("        inc hl")
        emit("        inc hl")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        dec a")
        emit("        ld (#_gbs_bt_n), a")
        emit("        jr nz, 1$")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")
        emit("/* Three or more sprites per entry: a plain loop. */")
        emit("void gbs_spr_plotn(uint8_t first, uint8_t n, const uint8_t *xs,")
        emit("                   const uint8_t *ys, uint8_t cols) {")
        emit("    uint8_t *p, x, y, c;")
        emit("    if (!n) return;")
        emit("    p = (uint8_t *)&shadow_OAM[first];")
        emit("    do {")
        emit("        y = (uint8_t)(*ys++ + 16);")
        emit("        x = (uint8_t)(*xs++ + 8);")
        emit("        c = cols;")
        emit("        do { *p++ = y; *p++ = x; p += 2; x += 8; } while (--c);")
        emit("    } while (--n);")
        emit("}")
        emit("void gbs_bt_drift(void) NAKED {")
        emit("__asm")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, #_gbs_bt_a")
        emit("        ld a, (hl+)")
        emit("        ld e, a")
        emit("        ld d, (hl)              ; de = vel")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("        ld hl, #_gbs_bt_d")
        emit("        ld a, (hl+)")
        emit("        ld h, (hl)")
        emit("        ld l, a                 ; hl = pos")
        emit("1$:")
        emit("        ld a, (de)")
        emit("        inc de")
        emit("        add a, (hl)")
        emit("        ld (hl+), a")
        emit("        dec b")
        emit("        jr nz, 1$")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")
        emit("void gbs_bt_hit(void) NAKED {")
        emit("__asm")
        emit("        ld a, #255")
        emit("        ld (#_gbs_bt_r), a")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, #_gbs_bt_b")
        emit("        ld a, (hl+)")
        emit("        ld e, a")
        emit("        ld d, (hl)              ; de = ys")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("        ld c, #0                ; the index")
        emit("        ld hl, #_gbs_bt_a")
        emit("        ld a, (hl+)")
        emit("        ld h, (hl)")
        emit("        ld l, a                 ; hl = xs")
        emit("1$:")
        emit("        ld a, (hl+)")
        emit("        push hl")
        emit("        ld hl, #_gbs_bt_box")
        emit("        sub a, (hl)             ; x - box.x")
        emit("        inc hl")
        emit("        cp a, (hl)              ; < box.w ?")
        emit("        jr nc, 2$")
        emit("        inc hl")
        emit("        ld a, (de)")
        emit("        sub a, (hl)             ; y - box.y")
        emit("        inc hl")
        emit("        cp a, (hl)              ; < box.h ?")
        emit("        jr c, 3$")
        emit("2$:")
        emit("        pop hl")
        emit("        inc de")
        emit("        inc c")
        emit("        dec b")
        emit("        jr nz, 1$")
        emit("        ld c, #255              ; nothing inside")
        emit("        jr 4$")
        emit("3$:")
        emit("        pop hl")
        emit("4$:")
        emit("        ld a, c")
        emit("        ld (#_gbs_bt_r), a")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")

    # --------------------------------------------------------- SMS / Game Gear
    def _emit_batch_z80(self):
        emit = self.emit
        offx = 48 if self.platform == 'gamegear' else 0
        offy = 23 if self.platform == 'gamegear' else 255
        self._emit_batch_state()
        emit("/* The sprite table here is 64 Y bytes, then 64 (X, tile) pairs. A Y")
        emit("   of 0xD0 ends the list, so anything from there up parks at 0xC0 -")
        emit("   what GBDK's own move_sprite does. */")
        emit("void gbs_bt_plot1(void) NAKED {")
        emit("__asm")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, (#_gbs_bt_b)     ; ys")
        emit("        ld de, (#_gbs_bt_d)     ; the Y bytes")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("1$:")
        emit("        ld a, (hl)")
        emit("        inc hl")
        emit("        add a, #%d              ; DEVICE_SPRITE_PX_OFFSET_Y" % offy)
        emit("        cp #0xD0")
        emit("        jr c, 2$")
        emit("        ld a, #0xC0")
        emit("2$:")
        emit("        ld (de), a")
        emit("        inc de")
        emit("        djnz 1$")
        emit("        ld de, (#_gbs_bt_e)     ; the X byte of `first`")
        emit("        ld hl, (#_gbs_bt_a)     ; xs")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("3$:")
        emit("        ld a, (hl)")
        emit("        inc hl")
        if offx:
            emit("        add a, #%d              ; DEVICE_SPRITE_PX_OFFSET_X" % offx)
        emit("        ld (de), a")
        emit("        inc de")
        emit("        inc de")
        emit("        djnz 3$")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")
        emit("/* Two sprites side by side per entry (a 16 px wide enemy). */")
        emit("void gbs_bt_plot2(void) NAKED {")
        emit("__asm")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, (#_gbs_bt_b)")
        emit("        ld de, (#_gbs_bt_d)")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("1$:")
        emit("        ld a, (hl)")
        emit("        inc hl")
        emit("        add a, #%d" % offy)
        emit("        cp #0xD0")
        emit("        jr c, 2$")
        emit("        ld a, #0xC0")
        emit("2$:")
        emit("        ld (de), a")
        emit("        inc de")
        emit("        ld (de), a")
        emit("        inc de")
        emit("        djnz 1$")
        emit("        ld de, (#_gbs_bt_e)")
        emit("        ld hl, (#_gbs_bt_a)")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("3$:")
        emit("        ld a, (hl)")
        emit("        inc hl")
        if offx:
            emit("        add a, #%d" % offx)
        emit("        ld (de), a")
        emit("        inc de")
        emit("        inc de")
        emit("        add a, #8")
        emit("        ld (de), a")
        emit("        inc de")
        emit("        inc de")
        emit("        djnz 3$")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")
        emit("/* Three or more sprites per entry: a plain loop. */")
        emit("void gbs_spr_plotn(uint8_t first, uint8_t n, const uint8_t *xs,")
        emit("                   const uint8_t *ys, uint8_t cols) {")
        emit("    uint8_t *py, *px, x, y, c;")
        emit("    if (!n) return;")
        emit("    py = (uint8_t *)shadow_OAM + first;")
        emit("    px = (uint8_t *)shadow_OAM + 0x40 + ((uint8_t)(first << 1));")
        emit("    do {")
        emit("        y = (uint8_t)(*ys++ + DEVICE_SPRITE_PX_OFFSET_Y);")
        emit("        if (y >= 0xD0) y = 0xC0;")
        emit("        x = (uint8_t)(*xs++ + DEVICE_SPRITE_PX_OFFSET_X);")
        emit("        c = cols;")
        emit("        do { *py++ = y; *px = x; px += 2; x += 8; } while (--c);")
        emit("    } while (--n);")
        emit("}")
        emit("void gbs_bt_drift(void) NAKED {")
        emit("__asm")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        ld hl, (#_gbs_bt_d)     ; pos")
        emit("        ld de, (#_gbs_bt_a)     ; vel")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("1$:")
        emit("        ld a, (de)")
        emit("        inc de")
        emit("        add a, (hl)")
        emit("        ld (hl), a")
        emit("        inc hl")
        emit("        djnz 1$")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")
        emit("/* The box lives in the alternate register set for the scan: neither")
        emit("   sdcc nor GBDK's interrupt code uses it. */")
        emit("void gbs_bt_hit(void) NAKED {")
        emit("__asm")
        emit("        ld a, #255")
        emit("        ld (#_gbs_bt_r), a")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        or a, a")
        emit("        ret z")
        emit("        push bc")
        emit("        exx")
        emit("        ld bc, (#_gbs_bt_box)       ; c = x, b = w")
        emit("        ld de, (#_gbs_bt_box + 2)   ; e = y, d = h")
        emit("        exx")
        emit("        ld hl, (#_gbs_bt_a)     ; xs")
        emit("        ld de, (#_gbs_bt_b)     ; ys")
        emit("        ld a, (#_gbs_bt_n)")
        emit("        ld b, a")
        emit("        ld c, #0")
        emit("1$:")
        emit("        ld a, (hl)")
        emit("        exx")
        emit("        sub c")
        emit("        cp b")
        emit("        exx")
        emit("        jr nc, 2$")
        emit("        ld a, (de)")
        emit("        exx")
        emit("        sub e")
        emit("        cp d")
        emit("        exx")
        emit("        jr c, 3$")
        emit("2$:")
        emit("        inc hl")
        emit("        inc de")
        emit("        inc c")
        emit("        djnz 1$")
        emit("        ld c, #255")
        emit("3$:")
        emit("        ld a, c")
        emit("        ld (#_gbs_bt_r), a")
        emit("        pop bc")
        emit("        ret")
        emit("__endasm;")
        emit("}")

    # ------------------------------------------------------------ portable C
    def _emit_batch_c(self, mover="move_sprite", offs=True):
        emit = self.emit
        emit("/* ---- batch sprite verbs (sprite.plot / drift / hit): portable C ---- */")
        emit("static uint8_t gbs_bt_box[4];             /* x, w, y, h */")
        emit("void gbs_spr_hit_box(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {")
        emit("    gbs_bt_box[0] = x; gbs_bt_box[1] = w;")
        emit("    gbs_bt_box[2] = y; gbs_bt_box[3] = h;")
        emit("}")
        emit("void gbs_spr_plot(uint8_t first, uint8_t n, const uint8_t *xs,")
        emit("                  const uint8_t *ys, uint8_t cols) {")
        emit("    uint8_t x, y, c;")
        emit("    while (n--) {")
        if offs:
            emit("        x = (uint8_t)(*xs++ + DEVICE_SPRITE_PX_OFFSET_X);")
            emit("        y = (uint8_t)(*ys++ + DEVICE_SPRITE_PX_OFFSET_Y);")
        else:
            emit("        x = *xs++;")
            emit("        y = *ys++;")
        emit("        for (c = cols; c; --c) { %s(first++, x, y); x += 8; }" % mover)
        emit("    }")
        emit("}")
        emit("void gbs_spr_drift(uint8_t *pos, const uint8_t *vel, uint8_t n) {")
        emit("    while (n--) { *pos = (uint8_t)(*pos + *vel++); ++pos; }")
        emit("}")
        emit("uint8_t gbs_spr_hit(const uint8_t *xs, const uint8_t *ys, uint8_t n) {")
        emit("    uint8_t i;")
        emit("    for (i = 0; i < n; ++i)")
        emit("        if ((uint8_t)(xs[i] - gbs_bt_box[0]) < gbs_bt_box[1]")
        emit("            && (uint8_t)(ys[i] - gbs_bt_box[2]) < gbs_bt_box[3]) return i;")
        emit("    return 255;")
        emit("}")
