"""GBDK backend: prelude + stdlib lowering map (mixin for CodeGenerator)."""


class GbdkBackend:
    """GBDK-specific codegen: the stdlib call map and C prelude.

    Mixed into CodeGenerator; all methods run against the full generator
    instance (self.emit, self.caps, self.platform, ...).
    """

    # mosaik stdlib calls -> C helper / GBDK function names.
    STDLIB_CALLS_GBDK = {
        ('video', 'enable_lcd'): 'gbs_enable_lcd',
        ('video', 'disable_lcd'): 'gbs_disable_lcd',
        # wait_vblank is a vsync() wrapper so it can also count down the
        # platform.sound beep duration (60 ticks/s on every console).
        ('video', 'wait_vblank'): 'gbs_wait_vblank',
        ('input', 'pressed'): 'gbs_input_pressed',
        ('input', 'held'): 'gbs_input_pressed',
        ('text', 'print_string'): 'gbs_print_string',
        ('text', 'print_number'): 'gbs_print_number',
        ('text', 'clear_area'): 'gbs_clear_area',
        ('hw', 'write'): 'gbs_hw_write',
        ('hw', 'read'): 'gbs_hw_read',
        # Display visibility (macros, wrapped as helpers).
        ('video', 'show_sprites'): 'gbs_show_sprites',
        ('video', 'hide_sprites'): 'gbs_hide_sprites',
        ('video', 'show_background'): 'gbs_show_bkg',
        ('video', 'show_window'): 'gbs_show_win',
        ('video', 'hide_window'): 'gbs_hide_win',
        # Sprites (graphics.sprite). sprite.move takes screen-pixel coords;
        # the gbs_ wrapper adds the per-console hardware offset.
        ('sprite', 'set_data'): 'set_sprite_data',
        ('sprite', 'set_tile'): 'set_sprite_tile',
        ('sprite', 'get_tile'): 'get_sprite_tile',
        ('sprite', 'set_prop'): 'set_sprite_prop',
        ('sprite', 'move'): 'gbs_move_sprite',
        # Background (graphics.bkg).
        ('bkg', 'set_data'): 'set_bkg_data',
        ('bkg', 'set_tiles'): 'set_bkg_tiles',
        ('bkg', 'scroll'): 'scroll_bkg',
        ('bkg', 'move'): 'move_bkg',
        # Window (graphics.window).
        ('window', 'set_tiles'): 'set_win_tiles',
        ('window', 'move'): 'move_win',
        # System utilities (platform.system).
        ('system', 'delay'): 'delay',
        ('system', 'random'): 'rand',
        ('system', 'seed_random'): 'initrand',
        # Sound (platform.sound): one square-wave beep channel.
        ('sound', 'beep'): 'gbs_sound_beep',
        ('sound', 'stop'): 'gbs_sound_stop',
    }

    def _emit_prelude_gbdk(self):
        self.emit("/* Generated by mosaik -> GBDK C backend */")
        self.emit("/* Target console: %s */" % self.platform)
        # <gbdk/platform.h> pulls in the correct console header for the build
        # target (Game Boy, Pocket, Mega Duck, SMS/GG, NES), so the same
        # generated C compiles for every supported platform.
        self.emit("#include <gbdk/platform.h>")
        self.emit("#include <gbdk/console.h>")
        self.emit("#include <gbdk/font.h>")
        self.emit("#include <rand.h>")
        self.emit("#include <stdio.h>")
        self.emit("#include <stdint.h>")
        self.emit("")
        self.emit("/* Input button constants mapped to GBDK joypad bits */")
        self.emit("#define INPUT_A      J_A")
        self.emit("#define INPUT_B      J_B")
        self.emit("#define INPUT_SELECT J_SELECT")
        self.emit("#define INPUT_START  J_START")
        self.emit("#define INPUT_RIGHT  J_RIGHT")
        self.emit("#define INPUT_LEFT   J_LEFT")
        self.emit("#define INPUT_UP     J_UP")
        self.emit("#define INPUT_DOWN   J_DOWN")
        self.emit("")
        self.emit("/* Screen geometry for the build target (GBDK resolves the")
        self.emit("   DEVICE_* macros per console at C compile time). */")
        self.emit("#define SCREEN_WIDTH  DEVICE_SCREEN_PX_WIDTH")
        self.emit("#define SCREEN_HEIGHT DEVICE_SCREEN_PX_HEIGHT")
        self.emit("#define SCREEN_COLS   DEVICE_SCREEN_WIDTH")
        self.emit("#define SCREEN_ROWS   DEVICE_SCREEN_HEIGHT")
        self.emit("")
        if self.caps['has_gb_regs']:
            self.emit("/* Hardware register addresses (for hw.read / hw.write) */")
            self.emit("#define REG_DIV  0xFF04")
            self.emit("#define REG_NR10 0xFF10")
            self.emit("#define REG_BGP  0xFF47")
            self.emit("#define REG_OBP0 0xFF48")
            self.emit("#define REG_OBP1 0xFF49")
            self.emit("")
        self.emit("/* Sprite property flags (graphics.sprite) */")
        self.emit("#define FLIP_X S_FLIPX")
        self.emit("#define FLIP_Y S_FLIPY")
        self.emit("")
        self.emit("/* mosaik standard library helpers */")
        self.emit("void gbs_enable_lcd(void) { DISPLAY_ON; SHOW_BKG; }")
        self.emit("void gbs_disable_lcd(void) { DISPLAY_OFF; }")
        self.emit("uint8_t gbs_input_pressed(uint8_t button) { return (uint8_t)(joypad() & button); }")
        self.emit("/* GBDK-2020's console printf needs a font loaded before any text")
        self.emit("   tiles are drawn; do it lazily on first use (once). */")
        self.emit("void gbs_text_init(void) {")
        self.emit("    static uint8_t gbs_font_ready = 0;")
        self.emit("    if (!gbs_font_ready) { font_init(); font_set(font_load(font_ibm)); gbs_font_ready = 1; }")
        self.emit("}")
        self.emit("void gbs_print_string(uint8_t x, uint8_t y, const char *s) { gbs_text_init(); gotoxy(x, y); printf(\"%s\", s); }")
        self.emit("void gbs_print_number(uint8_t x, uint8_t y, uint16_t n) { gbs_text_init(); gotoxy(x, y); printf(\"%d\", n); }")
        self.emit("void gbs_clear_area(uint8_t x, uint8_t y, uint8_t w, uint8_t h) {")
        self.emit("    uint8_t i, j;")
        self.emit("    gbs_text_init();")
        self.emit("    for (j = 0; j < h; j++) { gotoxy(x, y + j); for (i = 0; i < w; i++) printf(\" \"); }")
        self.emit("}")
        self.emit("/* Raw hardware register access (sound, palette, timer, ...) */")
        self.emit("void gbs_hw_write(uint16_t addr, uint8_t value) { *(volatile uint8_t *)addr = value; }")
        self.emit("uint8_t gbs_hw_read(uint16_t addr) { return *(volatile uint8_t *)addr; }")
        self.emit("/* Display visibility helpers (GBDK macros wrapped as functions) */")
        self.emit("void gbs_show_sprites(void) { SHOW_SPRITES; }")
        self.emit("void gbs_hide_sprites(void) { HIDE_SPRITES; }")
        self.emit("void gbs_show_bkg(void) { SHOW_BKG; }")
        self.emit("/* sprite.move takes screen-pixel coordinates (origin = top-left of")
        self.emit("   the visible screen); the hardware offset differs per console. */")
        self.emit("void gbs_move_sprite(uint8_t nb, uint8_t x, uint8_t y) {")
        self.emit("    move_sprite(nb, (uint8_t)(x + DEVICE_SPRITE_PX_OFFSET_X),")
        self.emit("                    (uint8_t)(y + DEVICE_SPRITE_PX_OFFSET_Y));")
        self.emit("}")
        if self.caps['has_window']:
            self.emit("/* The window layer only exists on Game Boy-family consoles. */")
            self.emit("void gbs_show_win(void) { SHOW_WIN; }")
            self.emit("void gbs_hide_win(void) { HIDE_WIN; }")
        self._emit_gbdk_sound()
        self.emit("")

    def _emit_gbdk_sound(self):
        """platform.sound for GBDK consoles: one square-wave beep channel.

        sound.beep(freq_hz, frames) starts a tone; the duration counts down in
        gbs_wait_vblank (60 ticks/s, so `frames` matches the wait_vblank pacing
        on every console; 0 = play until sound.stop()). The tone generator
        differs per family: Game Boy APU pulse channel 2 (the NR*_REG symbols
        resolve per console in GBDK's library -- the Mega Duck remap included),
        the SN76489 PSG on SMS/Game Gear, and APU pulse 1 on the NES.
        """
        self.emit("/* platform.sound: one square-wave beep channel. */")
        self.emit("static uint16_t gbs_snd_frames = 0;")
        if self.caps['has_gb_regs']:
            # Mega Duck quirk: the volume-envelope registers (NR12/NR22/NR42)
            # have their nibbles swapped relative to the Game Boy.
            envelope = '0x0F' if self.platform == 'megaduck' else '0xF0'
            self.emit("/* Game Boy APU, pulse channel 2 (no sweep). Powering the APU off")
            self.emit("   clears every register, so stop() is a single write. */")
            self.emit("void gbs_sound_stop(void) { NR52_REG = 0x00; gbs_snd_frames = 0; }")
            self.emit("void gbs_sound_beep(uint16_t freq, uint16_t frames) {")
            self.emit("    uint16_t period;")
            self.emit("    if (freq < 64) freq = 64;  /* APU floor: period must be >= 0 */")
            self.emit("    period = (uint16_t)(2048 - (uint16_t)(131072UL / freq));")
            self.emit("    NR52_REG = 0x80;  /* APU on */")
            self.emit("    NR51_REG = 0xFF;  /* route every channel left + right */")
            self.emit("    NR50_REG = 0x77;  /* master volume max */")
            self.emit("    NR21_REG = 0x80;  /* 50% duty */")
            self.emit("    NR22_REG = %s;  /* full volume, no envelope */" % envelope)
            self.emit("    NR23_REG = (uint8_t)period;")
            self.emit("    NR24_REG = 0x80 | (uint8_t)(period >> 8);  /* trigger */")
            self.emit("    gbs_snd_frames = frames;")
            self.emit("}")
        elif self.platform in ('sms', 'gamegear'):
            self.emit("/* SN76489 PSG, tone channel 0 (latch/data bytes on the PSG port). */")
            self.emit("void gbs_sound_stop(void) {")
            self.emit("    PSG = PSG_LATCH | PSG_CH0 | PSG_VOLUME | 0x0F;  /* attenuation max */")
            self.emit("    gbs_snd_frames = 0;")
            self.emit("}")
            self.emit("void gbs_sound_beep(uint16_t freq, uint16_t frames) {")
            self.emit("    uint16_t divider;")
            self.emit("    if (freq < 110) freq = 110;  /* divider must fit 10 bits */")
            self.emit("    divider = (uint16_t)(111861UL / freq);  /* 3.579545 MHz / 32 / f */")
            if self.platform == 'gamegear':
                self.emit("    GG_SOUND_PAN = 0xFF;  /* all channels to both ears */")
            self.emit("    PSG = (uint8_t)(PSG_LATCH | PSG_CH0 | (divider & 0x0F));")
            self.emit("    PSG = (uint8_t)((divider >> 4) & 0x3F);")
            self.emit("    PSG = PSG_LATCH | PSG_CH0 | PSG_VOLUME | 0x00;  /* attenuation 0 = loudest */")
            self.emit("    gbs_snd_frames = frames;")
            self.emit("}")
        else:
            self.emit("/* NES APU, pulse channel 1. */")
            self.emit("void gbs_sound_stop(void) {")
            self.emit("    (*(volatile uint8_t *)0x4015) = 0x00;  /* silence all channels */")
            self.emit("    gbs_snd_frames = 0;")
            self.emit("}")
            self.emit("void gbs_sound_beep(uint16_t freq, uint16_t frames) {")
            self.emit("    uint16_t timer;")
            self.emit("    if (freq < 55) freq = 55;  /* timer must fit 11 bits */")
            self.emit("    timer = (uint16_t)(111861UL / freq) - 1;  /* 1.789773 MHz / 16 / f */")
            self.emit("    (*(volatile uint8_t *)0x4015) = 0x01;  /* enable pulse 1 */")
            self.emit("    (*(volatile uint8_t *)0x4000) = 0xBF;  /* 50% duty, no length, vol 15 */")
            self.emit("    (*(volatile uint8_t *)0x4001) = 0x08;  /* sweep off (negate: no mute) */")
            self.emit("    (*(volatile uint8_t *)0x4002) = (uint8_t)timer;")
            self.emit("    (*(volatile uint8_t *)0x4003) = (uint8_t)((timer >> 8) & 0x07);")
            self.emit("    gbs_snd_frames = frames;")
            self.emit("}")
        self.emit("/* wait_vblank with the beep-duration countdown (60 ticks/s). */")
        self.emit("void gbs_wait_vblank(void) {")
        self.emit("    vsync();")
        self.emit("    if (gbs_snd_frames && --gbs_snd_frames == 0) gbs_sound_stop();")
        self.emit("}")
