"""CodeGenerator declaration/type/struct/enum emission, mixed into generator.CodeGenerator.

Split out of the former monolithic generator.py; a plain mixin class composed
into CodeGenerator - methods reference sibling methods/attributes via self."""
import dataclasses
import re

from ..ast_nodes import *  # noqa: F401,F403
from ..platforms import (PLATFORM_CAPS, canonical_platform,
                         framework_for_platform, platform_caps)


class DeclEmitMixin:
    # -- ROM banking (bank(N) placement) ----------------------------------

    def _in_bank_unit(self, func) -> bool:
        """True when the function's body belongs to a bank TU, not the main TU.
        Never on cc65: there a banked body stays in the ONE TU, wrapped in its
        bank's segment pragmas (see cc65_bank)."""
        return (self.banking_active and func.bank > 0
                and self.framework != 'cc65')

    # -- Build-driven cold-code banking (`[build] code_banks`) ---------------
    # Whole modules' function bodies leave the resident image for a switchable
    # ROM bank (the GB-family engine-code banking, gbs-import item 1D). Two
    # phases because placement depends on the streamed-symbol set, which is
    # only known after _collect_streamed:
    #   Phase A (_plan_code_banks, before bank(N) collection): validate the
    #     request, reserve the code bank, and split every ADDRESS-TAKEN
    #     function (a vm.core seam registration target) into a resident stub
    #     + a body candidate -- a function pointer must target home code, so
    #     the stub keeps the address while the body banks.
    #   Phase B (_apply_code_banks, after _collect_streamed): assign the bank
    #     to every candidate whose body does NOT switch the ROM window; the
    #     ones that do stay home and get the bank-neutrality wrapper (they
    #     must restore the entry bank, or a BANKED caller resumes under a
    #     switched-out window and executes garbage).
    # The interpreter's hot path must never bank: a trampoline per fetched
    # byte is the Lynx page-reader mistake all over again. 'scripts' is
    # refused outright for that reason. 'vm.core' is NOT: it carries both the
    # hot path AND a cold half (boot, the seam setters, spawn/kill/
    # reset_scene_ui) that runs once per boot / scene change / event, and the
    # module pins its own hot functions with `bank(0)` -- the same per-function
    # escape the generated collision probes use. See the header comment in
    # lib/vm/core.mos; measured at ~880 B of GB bank 0 on the reference-engine sample conversion.
    # A module listed here that does NOT pin its hot path is the caller's
    # mistake, not something this layer can detect.

    _CODE_BANK_REFUSED = {
        'scripts': "the generated bytecode module (fetch() runs per "
                   "instruction byte; its CODE blob must stay resident)",
    }

    def _plan_code_banks(self, program, banked):
        """Phase A of `[build] code_banks` (see the class comment above)."""
        self._code_bank_num = 0
        self._bank_candidates = []
        if not self.code_banks:
            return
        if not self._rom_banking_capable():
            print("    Note: [build] code_banks ignored on %s (no banked-ROM "
                  "support on this console; code stays in the linear image)"
                  % self.platform)
            return
        for name in self.code_banks:
            if name in self._CODE_BANK_REFUSED:
                raise RuntimeError(
                    "[build] code_banks must not list '%s': %s"
                    % (name, self._CODE_BANK_REFUSED[name]))
        mods = {m.name: m for m in program.modules}
        missing = [n for n in self.code_banks if n not in mods]
        if missing:
            print("    Note: [build] code_banks names module(s) not in this "
                  "build: %s" % ", ".join(missing))
        # ONE BANK PER MODULE, above any explicit bank(N) placement; streamed
        # DATA banks are assigned above them in turn (_collect_streamed_gb).
        # Per-module because a shared code bank overflows silently once enough
        # modules bank (~20 KB of engine code into one 16 KB window -- caught
        # at link now, but packing by estimated size is guesswork), while
        # per-module banks need no size estimate at all: no engine module
        # comes near 16 KB, cross-bank calls already trampoline either way,
        # and ROM banks are the abundant resource (the cart auto-sizes; GB
        # Studio ships this class of game as a 512 KB cart for the same
        # reason).
        start = max((f.bank for _m, f in banked), default=0) + 1
        self._code_bank_of = {}
        for name in self.code_banks:
            if name in mods:
                self._code_bank_of[name] = start + len(self._code_bank_of)
        self._code_bank_num = start if self._code_bank_of else 0
        addr_taken = self._collect_address_taken(program)
        for name in self.code_banks:
            module = mods.get(name)
            if module is None:
                continue
            for decl in list(module.declarations):
                if not isinstance(decl, FunctionDecl) or decl.name == 'main':
                    continue
                if decl.bank_pinned:
                    # `bank(0)`: the author says this one is HOT. Banking is
                    # per MODULE but hotness is per FUNCTION - the generated
                    # collision probes are ~40 bytes each on a path that runs
                    # 30+ times a frame, while the rest of `rooms` is cold
                    # room-load code that must bank or bank 0 overflows.
                    continue
                if decl.hot and self._overlay_banking():
                    # `hot`: called per frame. A Lynx "bank" is a cart
                    # OVERLAY loaded on a miss, so a per-frame function in one
                    # would reload every frame (cc65_bank). Resident.
                    continue
                if (module.name, decl.name) in addr_taken:
                    decl = self._split_banked_stub(module, decl)
                self._bank_candidates.append((module, decl))

    def _split_banked_stub(self, module, decl):
        """Split an address-taken function into a resident stub (keeps the
        name, so every registered pointer still targets home code) + a
        `<name>__bimpl` body candidate the stub calls directly (direct calls
        to banked code go through sdcc's trampoline and are fine). Returns
        the body decl."""
        impl = FunctionDecl(name=decl.name + "__bimpl",
                            parameters=decl.parameters,
                            return_type=decl.return_type,
                            body=decl.body,
                            is_local=True)
        call = FunctionCall(function=Identifier(name=impl.name),
                            arguments=[Identifier(name=p.name)
                                       for p in decl.parameters])
        if decl.return_type is not None:
            decl.body = [ReturnStmt(value=call)]
        else:
            decl.body = [ExpressionStmt(expression=call)]
        module.declarations.insert(module.declarations.index(decl) + 1, impl)
        return impl

    def _collect_address_taken(self, program):
        """Every program function referenced as a VALUE (not a call's callee)
        -- the callback registrations. Same node patterns as
        _check_fnptr_targets, collected instead of rejected. Conservative:
        a false positive only costs a needless (harmless) stub."""
        own = {m.name: {d.name for d in m.declarations
                        if isinstance(d, FunctionDecl)}
               for m in program.modules}
        alias_of = {m.name.rsplit('.', 1)[-1]: m.name for m in program.modules}
        callees = set()

        def mark(node):
            if isinstance(node, FunctionCall):
                callees.add(id(node.function))
            if isinstance(node, ASTNode):
                for f in dataclasses.fields(node):
                    mark(getattr(node, f.name))
            elif isinstance(node, (list, tuple)):
                for x in node:
                    mark(x)

        mark(program)
        taken = set()

        def check(module_name, node):
            if id(node) not in callees:
                if (isinstance(node, Identifier)
                        and node.name in own[module_name]):
                    taken.add((module_name, node.name))
                elif (isinstance(node, FieldAccess)
                      and isinstance(node.object, Identifier)):
                    target = alias_of.get(node.object.name)
                    if target and node.field in own.get(target, ()):
                        taken.add((target, node.field))
            if isinstance(node, ASTNode):
                for f in dataclasses.fields(node):
                    check(module_name, getattr(node, f.name))
            elif isinstance(node, (list, tuple)):
                for x in node:
                    check(module_name, x)

        for module in program.modules:
            check(module.name, module.declarations)
        return taken

    def _apply_code_banks(self, program):
        """Phase B of `[build] code_banks`: mark the bank-neutrality wrappers
        and place the candidates that are safe to bank."""
        self._bank_neutral_funcs = set()
        if not self._code_bank_num:
            return
        # Any function whose body switches the ROM window (a GB streamed-seam
        # lowering) must restore the entry bank on exit -- BANKED callers
        # resume through the sdcc trampoline, which restores what CURRENT_BANK
        # said at call time, but a plain (near) caller resumes directly and
        # inherits whatever the callee left mapped.
        if self._stream_mode == 'gb':
            for module in program.modules:
                self._enter_module(module)
                for decl in module.declarations:
                    if (isinstance(decl, FunctionDecl)
                            and self._func_touches_streamed(decl)):
                        self._bank_neutral_funcs.add(id(decl))
        placed = 0
        for module, decl in self._bank_candidates:
            if id(decl) in self._bank_neutral_funcs:
                continue    # switches the window itself: must stay home
            decl.bank = self._code_bank_of[module.name]
            placed += 1
        if placed:
            banks = sorted(set(self._code_bank_of.values()))
            print("    Code banking: %d function(s) placed in ROM banks %d-%d "
                  "(one bank per module: %s)"
                  % (placed, banks[0], banks[-1], ", ".join(self.code_banks)))
            # Re-run the callback-target check over the final placement: a
            # banked function referenced as a value would read the wrong code
            # through its pointer. Phase A's stub split should make this
            # impossible; failing loudly beats a silent wrong pointer.
            banked = [(m, d) for m in program.modules
                      for d in m.declarations
                      if isinstance(d, FunctionDecl) and d.bank > 0]
            self._check_fnptr_targets(program, banked)
        # Unconditional: the far-read sprite placement below does not depend
        # on any function having banked (a sheet uploaded from `main()` banks
        # too), and with nothing placed the co-location loops see reader bank
        # 0 everywhere and move nothing, exactly as before.
        if self._code_bank_num:
            self._collect_bank_local_consts(program)

    def _collect_near_bank_locals(self, program):
        """EVERY CALL TO A BANKED FUNCTION IS A TRAMPOLINE, INCLUDING A
        SAME-BANK ONE (~164 cycles + 8 bytes against a direct call's 24 + 3;
        the 2026-08-28 census: 80 banked calls a frame in the town room idle,
        38% of them same-bank = ~4,400 cycles a frame). A module-private
        `local function` placed in a ROM bank whose callers ALL sit in that
        same bank never needs the trampoline: its callers can only be running
        while their common bank is mapped, so a direct near call is always
        valid. Such functions are emitted WITHOUT `BANKED` -- `#pragma bank`
        still places their body in the bank's code segment; only the calling
        convention changes, consistently at the definition and every
        prototype (both come from _function_signature).

        The conditions, each load-bearing:
        - `is_local`: module-private by construction, so every call site is
          in its own module (a cross-module call could come from any bank).
        - all intra-module callers share the function's own bank. This is
          what keeps a `bank(0)`-pinned hot function's helpers, and the
          resident stub -> `__bimpl` call of an address-taken split, on the
          trampoline: their callers are bank 0, the body is not.
        - not address-taken (a function pointer must target home code; a
          near-emitted banked body through a pointer would be called
          unmapped). _collect_address_taken is conservative, which here only
          costs a kept trampoline.
        - not window-switching (a GB streamed-seam read): the trampoline is
          what restores the caller's bank today, so a near call into a body
          that leaves a different window mapped would resume the caller
          under the wrong bank -- the same bank-neutrality question
          _apply_code_banks answers for stay-home candidates. (Under
          code_banks those functions stay home anyway; explicit bank(N)
          bodies are excluded here.)
        A candidate's body may freely CALL banked functions -- the inner
        trampoline restores the mapped bank before returning -- and may call
        other near-emitted locals, which are bank-neutral by this same
        analysis, inductively."""
        self._near_bank_funcs = set()
        if not self.banking_active:
            return
        addr_taken = self._collect_address_taken(program)
        for module in program.modules:
            self._enter_module(module)
            funcs = [d for d in module.declarations
                     if isinstance(d, FunctionDecl)]
            cands = {}
            for d in funcs:
                if (d.is_local and d.bank > 0
                        and (module.name, d.name) not in addr_taken
                        and not (self._stream_mode == 'gb'
                                 and self._func_touches_streamed(d))):
                    cands[d.name] = d
            if not cands:
                continue
            caller_banks = {n: set() for n in cands}

            def walk(node, bank):
                if isinstance(node, FunctionCall):
                    fn = node.function
                    if isinstance(fn, Identifier) and fn.name in caller_banks:
                        caller_banks[fn.name].add(bank)
                if isinstance(node, ASTNode):
                    for f in dataclasses.fields(node):
                        walk(getattr(node, f.name), bank)
                elif isinstance(node, (list, tuple)):
                    for x in node:
                        walk(x, bank)

            for d in funcs:
                walk(d.body, d.bank)
            for vd in module.declarations:
                # A module-level initializer evaluates at home; a call from
                # one (not valid C anyway) must disqualify, not qualify.
                if isinstance(vd, VarDecl) and vd.initializer is not None:
                    walk(vd.initializer, 0)
            for n, d in cands.items():
                banks = caller_banks[n]
                if banks and banks <= {d.bank}:
                    self._near_bank_funcs.add(id(d))

    def _collect_bank_local_consts(self, program):
        """Stage 2b of code banking: a listed module's const ARRAYS move into
        the module's code bank when every reference to them comes from a
        function placed in that same bank -- banked code reads them directly
        while its own bank is mapped, so the move is free (no switch, no
        seam). A single reference from home (or from a home-pinned function)
        disqualifies the const: home code reads the window unswitched and
        would see whatever bank happens to be mapped. The big wins are the
        generated clips frame tables and a music driver's period tables --
        const data only its own (banked) module ever touches."""
        self._bank_local_consts = {}
        listed = {m.name: m for m in program.modules
                  if m.name in self.code_banks}
        if not listed:
            return
        # Candidates: const arrays of listed modules, not already banked as
        # streamed DATA (those live in their own data banks). Each candidate's
        # home is ITS OWN module's code bank -- a reader in any other bank
        # (home or another module's bank) reads the window unswitched, so it
        # disqualifies the const.
        candidates = {}
        cand_bank = {}
        for module in listed.values():
            for decl in module.declarations:
                if (isinstance(decl, VarDecl) and decl.is_const
                        and isinstance(decl.initializer, ArrayLiteral)):
                    c_name = self._mangled(module.name, decl.name)
                    if c_name not in self.streamed:
                        candidates[c_name] = decl
                        cand_bank[c_name] = self._code_bank_of[module.name]
        # ASSET arrays (`[assets] sprites` sheets) are emitted by the CODEGEN,
        # not declared in any module, so they have no module bank of their own
        # -- their home is decided by their READERS. This matters because
        # `<name>_tiles` is typically the single biggest resident const in a
        # VM8 game (2 KB on the reference-engine import) and it is read exactly once,
        # by the shell's one-time `sprite.set_data` upload: put that call in a
        # banked helper and the whole sheet leaves the resident image. A read
        # from HOME (bank 0) disqualifies it, exactly like a module const --
        # and `main()` is never banked, so an upload written inline in `main()`
        # keeps the sheet resident (which is what it used to do).
        #
        # ...AND CO-LOCATION IS NOT WHERE THE ART BELONGS ONCE THERE IS A LOT
        # OF IT. A code bank is ONE 16 KB window, and the sheets then compete
        # with the module's own code for it: the SMS/GG sample conversion's `rooms` bank
        # reached 16,445 B (61 past the window, 95 on the Game Gear - SMS/GG
        # have no hardware flip, so the soft-flip mirrors are real baked art)
        # and the link refused the ROM. `sheet_uploads` below is the way out:
        # a sheet read ONLY by `sprite.set_data` needs no co-location at all,
        # because the upload can go through a FAR read (`gbs_spr_data_far`
        # maps the sheet's bank, uploads, restores the caller's - the caller
        # may itself be banked, which is why the helper is resident). So the
        # art goes into a DATA bank instead, the code bank is left entirely
        # for code, and a room load pays one bank switch per sheet.
        # Measured on the SMS/GG sample conversion: rooms bank 16,445 -> 7,485 B.
        asset_banks = {"%s_tiles" % name: set()
                       for name, _d, _b in (self.assets or [])
                       if "%s_tiles" % name not in self.sheet_stream}
        # sheet symbol -> is every read of it a `sprite.set_data` upload?
        # (Seeded True; any OTHER read clears it and the sheet falls back to
        # the co-location rule above, byte for byte.)
        upload_only = {sym: True for sym in asset_banks}
        if not candidates and not asset_banks:
            return
        disqualified = set()

        def is_sheet_upload(node, local_names):
            return self._is_sheet_upload(node, asset_banks, local_names)

        def scan(node, reader_bank, local_names):
            if is_sheet_upload(node, local_names):
                # The sheet argument is a FAR-capable read: record the bank
                # like any other read (the fallback path needs it) but do not
                # descend into it, so it is not counted as an "other" read.
                asset_banks[node.arguments[2].name].add(reader_bank)
                for arg in node.arguments[:2]:
                    scan(arg, reader_bank, local_names)
                return
            if isinstance(node, Identifier):
                if node.name in asset_banks and node.name not in local_names:
                    upload_only[node.name] = False
                    asset_banks[node.name].add(reader_bank)
                c = (self._mangled(self.current_module, node.name)
                     if node.name in self.current_symbols
                     and node.name not in local_names else None)
                if c in candidates and reader_bank != cand_bank[c]:
                    disqualified.add(c)
            elif (isinstance(node, FieldAccess)
                  and isinstance(node.object, Identifier)):
                resolved = self._module_member(node.object.name, node.field)
                if (resolved in candidates
                        and reader_bank != cand_bank[resolved]):
                    disqualified.add(resolved)
            if isinstance(node, ASTNode):
                for f in dataclasses.fields(node):
                    scan(getattr(node, f.name), reader_bank, local_names)
            elif isinstance(node, (list, tuple)):
                for x in node:
                    scan(x, reader_bank, local_names)

        for module in program.modules:
            self._enter_module(module)
            for decl in module.declarations:
                if isinstance(decl, FunctionDecl):
                    local_names = {p.name for p in decl.parameters}
                    self._collect_locals(decl.body, local_names)
                    scan(decl.body, decl.bank, local_names)
                elif isinstance(decl, VarDecl) and decl.initializer is not None:
                    # A module-level initializer (or a scalar const, which
                    # lowers to a #define expanded at arbitrary use sites)
                    # referencing the array cannot be bank-tracked: keep the
                    # array home.
                    if not (decl.is_const
                            and isinstance(decl.initializer, ArrayLiteral)):
                        scan(decl.initializer, 0, set())
        moved = [c for c in candidates if c not in disqualified]
        for c_name in moved:
            self._bank_local_consts[c_name] = cand_bank[c_name]
        # A sheet read ONLY by `sprite.set_data` goes into a DATA bank and is
        # uploaded through the far helper: the reader's own bank is then
        # irrelevant, so this covers a home upload too (a sheet `main()`
        # uploads used to stay RESIDENT). No reads at all leaves it where it
        # is - it is dead data, and moving it would be a pointless diff.
        # `_prelude_data_bank` returns 0 when this build has no banks at all,
        # which is what keeps every unbanked program byte-identical.
        sizes = {"%s_tiles" % name: len(data)
                 for name, data, _b in (self.assets or [])}
        far = [sym for sym, banks in sorted(asset_banks.items())
               if banks and upload_only[sym]]
        self._bank_sprite_art(far, sizes)
        far = [sym for sym in far if sym in self.asset_far_bank]
        # An asset array read some OTHER way co-locates as before: when EVERY
        # read comes from one and the same banked function set. Any home read
        # pins it resident.
        for sym, banks in sorted(asset_banks.items()):
            if sym in self.asset_far_bank:
                continue
            if len(banks) == 1:
                bank = next(iter(banks))
                if bank > 0:
                    self._bank_local_consts[sym] = bank
                    moved.append(sym)
        if moved:
            print("    Code banking: %d const array(s) co-located in their "
                  "module's ROM bank (read only by that bank's code)"
                  % len(moved))
        if far:
            banks = sorted(set(self.asset_far_bank.values()))
            print("    Code banking: %d sprite sheet(s), %d bytes, in data "
                  "bank(s) %s (uploaded through the far read)"
                  % (len(far), sum(sizes[s] for s in far),
                     ", ".join(str(b) for b in banks)))

    @staticmethod
    def _is_sheet_upload(node, sheets, local_names):
        """`sprite.set_data(first, count, <sheet>)` - the ONE verb that reads
        an `[assets] sprites` array (repo-wide, 228 call sites). Shared by the
        GB far-sheet banking and the Lynx cart-streamed sheets."""
        fn = getattr(node, 'function', None)
        return (isinstance(node, FunctionCall)
                and isinstance(fn, FieldAccess)
                and isinstance(fn.object, Identifier)
                and fn.object.name == 'sprite'
                and fn.field == 'set_data'
                and len(node.arguments) == 3
                and isinstance(node.arguments[2], Identifier)
                and node.arguments[2].name in sheets
                and node.arguments[2].name not in local_names)

    def _upload_only_sheets(self, program):
        """The `[assets] sprites` sheets whose EVERY read is a
        `sprite.set_data(first, count, <sheet>)` upload (the same rule the GB
        far-sheet banking applies), each with at least one such read. A sheet
        read any other way, or never read, is not in the set."""
        sheets = {"%s_tiles" % name for name, _d, _b in (self.assets or [])}
        if not sheets:
            return set()
        uploaded, other = set(), set()

        def scan(node, local_names):
            if self._is_sheet_upload(node, sheets, local_names):
                uploaded.add(node.arguments[2].name)
                for arg in node.arguments[:2]:
                    scan(arg, local_names)
                return
            if (isinstance(node, Identifier) and node.name in sheets
                    and node.name not in local_names):
                other.add(node.name)
            if isinstance(node, ASTNode):
                for f in dataclasses.fields(node):
                    scan(getattr(node, f.name), local_names)
            elif isinstance(node, (list, tuple)):
                for x in node:
                    scan(x, local_names)

        for module in program.modules:
            self._enter_module(module)
            for decl in module.declarations:
                if isinstance(decl, FunctionDecl):
                    local_names = {p.name for p in decl.parameters}
                    self._collect_locals(decl.body, local_names)
                    scan(decl.body, local_names)
                elif isinstance(decl, VarDecl) and decl.initializer is not None:
                    scan(decl.initializer, set())
        return uploaded - other

    def _bank_sprite_art(self, syms, sizes):
        """Pack the far-read sprite sheets into DATA banks, greedily.

        `_prelude_data_bank` is the single-table door (the glyph font, the CGB
        fade engine) and it opens a FRESH bank for anything that does not fit
        the last STREAMED one - with 46 sheets that spent 14 banks on 7,840
        bytes. So the sheets are packed here instead, by the same rules:
        fill the remainder of the highest data bank already in use, then whole
        16 KB banks above everything placed. Registered in `prelude_bank_defs`
        so `_emit_data_bank_units` carries them and a later prelude table
        still sees them in `taken`.

        Declines (leaving every sheet where it was) when this build has no
        banks at all - which is what keeps an unbanked program byte-identical.
        """
        if (not syms or not self._rom_banking_capable() or not self.banking_active
                or self._overlay_banking()):
            # (Lynx overlays hold CODE: a sheet is uploaded by a far READ of
            # ROM, which the Lynx cart is not; its sheets stream instead.)
            return
        placed = [(b, n) for (b, _t, n) in self.prelude_bank_defs.values()]
        used = {}
        for bank, sym_list in self.data_bank_syms.items():
            used[bank] = sum(
                len(self._const_byte_values(self.data_bank_decls[s]) or b"")
                for s in sym_list)
        for bank, n in placed:
            used[bank] = used.get(bank, 0) + n
        taken = set(self._func_banks) | set(used)
        # Start in the highest bank that already holds data (its remainder is
        # free real estate); otherwise a fresh one above everything placed.
        bank = max(used) if used else ((max(taken) + 1) if taken else 1)
        room = self.GB_BANK_BYTES - used.get(bank, 0)
        for sym in syms:
            size = sizes[sym]
            if size > self.GB_BANK_BYTES:
                continue        # cannot fit any bank: leave it where it was
            if size > room:
                bank = max(set(used) | taken | {bank}) + 1
                used[bank] = 0
                room = self.GB_BANK_BYTES
            self.prelude_bank_defs[sym] = (bank, self._asset_bank_def(sym),
                                           size)
            self.asset_far_bank[sym] = bank
            used[bank] = used.get(bank, 0) + size
            room -= size

    def _asset_bank_def(self, sym):
        """One sprite sheet as the C definition its data-bank TU carries.
        Same text `_emit_assets` would have emitted in place."""
        data = next(d for name, d, _b in self.assets if "%s_tiles" % name == sym)
        lines = ["const uint8_t %s[%d] = {" % (sym, len(data))]
        for i in range(0, len(data), 16):
            lines.append("    " + " ".join("0x%02X," % b
                                           for b in data[i:i + 16]))
        lines.append("};")
        return "\n".join(lines)

    def _func_touches_streamed(self, decl) -> bool:
        """True when the function's body contains a lowering that will emit a
        SWITCH_ROM (a GB streamed-seam read: an assets.* verb or an array
        access on a streamed const). Mirrors the lowering conditions in
        gen_expr; the module context must be entered."""
        seam_verbs = self._STREAM_VERBS + ('code_byte',)
        found = []

        def visit(node):
            if found:
                return
            if isinstance(node, FunctionCall):
                fn = node.function
                if (isinstance(fn, FieldAccess)
                        and isinstance(fn.object, Identifier)
                        and fn.object.name == 'assets'
                        and fn.field in seam_verbs and node.arguments):
                    try:
                        sym = self.gen_expression(node.arguments[0])
                    except Exception:
                        sym = None
                    if sym in self.streamed:
                        found.append(True)
                        return
            if isinstance(node, ArrayAccess):
                try:
                    arr = self.gen_expression(node.array)
                except Exception:
                    arr = None
                if arr in self.streamed and arr not in self._range_bases:
                    found.append(True)
                    return
            if isinstance(node, ASTNode):
                for f in dataclasses.fields(node):
                    visit(getattr(node, f.name))
            elif isinstance(node, (list, tuple)):
                for x in node:
                    visit(x)

        visit(decl.body)
        return bool(found)

    def _check_streamed_args(self, program):
        """Review E-6 (2026-09-05): `assets.ptr(SYM)` on a GB-banked const
        lowers to `(SWITCH_ROM(n), SYM)` - the pointer is only meaningful
        while bank n is mapped. Two things silently break that, and until now
        only comments guarded them (gen_expr's ptr lowering, gbdk.py's
        banking note):

          * the pointer passed to a BANKED callee: sdcc's far-call trampoline
            maps the callee's bank before the body runs, so the callee reads
            SYM's address out of the wrong bank;
          * two streamed pointers of DIFFERENT banks in one call: evaluating
            the second unmaps the first.

        `_func_touches_streamed` keeps the CALLER home; this is the callee
        half. A resolved callee only - a call through a function pointer
        targets a home-bank function (`_check_fnptr_targets`), and a stdlib
        helper lives in the caller's TU. The value of a streamed ARRAY READ
        is not a pointer and is fine."""
        if self._stream_mode != 'gb' or not self.streamed:
            return
        fbank = {}
        for module in program.modules:
            for d in module.declarations:
                if isinstance(d, FunctionDecl):
                    fbank[(module.name, d.name)] = d.bank
        by_alias = {m.name.rsplit('.', 1)[-1]: m.name for m in program.modules}

        def ptr_banks(arg):
            """Banks of the streamed POINTERS evaluated inside `arg`."""
            calls = []
            self._streamed_calls(arg, calls)
            banks = set()
            for call in calls:
                if call.function.field not in ('ptr', 'ptr_range'):
                    continue
                try:
                    sym = self.gen_expression(call.arguments[0])
                except Exception:
                    sym = None
                if sym in self.streamed:
                    banks.add(self.streamed[sym])
            return banks

        def callee_of(call, module):
            fn = call.function
            if isinstance(fn, Identifier):
                return (module.name, fn.name)
            if (isinstance(fn, FieldAccess) and isinstance(fn.object, Identifier)
                    and fn.object.name in by_alias
                    and fn.object.name not in self.local_names
                    and fn.object.name not in self.current_symbols):
                return (by_alias[fn.object.name], fn.field)
            return None

        def where(decl, call):
            line = getattr(call, 'line', None) or getattr(decl, 'line', None)
            return "%s.%s%s" % (decl_module.name, decl.name,
                                (":%d" % line) if line else "")

        def visit(node, decl):
            if isinstance(node, FunctionCall):
                per_arg = [ptr_banks(a) for a in node.arguments]
                banks = set().union(*per_arg) if per_arg else set()
                if banks:
                    if len(banks) > 1:
                        raise RuntimeError(
                            "%s: a call carries streamed pointers from two ROM "
                            "banks (%s): evaluating the second unmaps the first. "
                            "Copy one through a local before the call."
                            % (where(decl, node), ", ".join(str(b) for b in sorted(banks))))
                    key = callee_of(node, decl_module)
                    cb = fbank.get(key, 0) if key else 0
                    if cb > 0:
                        raise RuntimeError(
                            "%s: a streamed pointer (assets.ptr of a bank-%d "
                            "const) is passed to '%s.%s', which lives in ROM "
                            "bank %d: the far call maps that bank first and the "
                            "callee would read the pointer out of the wrong "
                            "bank. Read the data in the caller (home bank) and "
                            "pass the values, or keep the callee home."
                            % (where(decl, node), next(iter(banks)), key[0], key[1], cb))
            if isinstance(node, ASTNode):
                for f in dataclasses.fields(node):
                    visit(getattr(node, f.name), decl)
            elif isinstance(node, (list, tuple)):
                for x in node:
                    visit(x, decl)

        for decl_module in program.modules:
            self._enter_module(decl_module)
            for decl in decl_module.declarations:
                if isinstance(decl, FunctionDecl):
                    visit(decl.body, decl)

    def _emit_bank_units(self, program, banked):
        """Generate one C translation unit per ROM bank used by `bank(N)`.

        SDCC's `#pragma bank` is file-scoped (the last pragma in a TU decides
        the code segment for *every* function in it -- verified against
        GBDK-2020), so each bank must be its own file. A bank TU repeats the
        prelude #defines and type definitions, declares the main TU's data
        and helpers `extern`, and holds the bank's function bodies. The main
        TU keeps every prototype, so home code calls banked code freely; the
        sdcc __banked trampoline does the bank switching at run time.
        """
        by_bank = {}
        for module, func in banked:
            by_bank.setdefault(func.bank, []).append((module, func))

        main_output = self.output
        main_needs = self._tu_meta_needs
        for bank in sorted(by_bank):
            self.output = []
            self.emit("/* Generated by mosaik -> GBDK C backend -- ROM bank %d */" % bank)
            self.emit("/* Target console: %s */" % self.platform)
            self.emit("#pragma bank %d" % bank)
            self.emit("")
            # This bank TU defines only the metasprite-family helpers its own
            # function bodies call (per-TU `static` copies over the extern
            # tables) - see gbdk_metasprite's residency note.
            self._tu_meta_needs = self._meta_helper_needs(
                [f for _m, f in by_bank[bank]])
            self._emit_prelude_gbdk_decls()
            self._emit_asset_decls(bank=bank)
            self._emit_fnptr_typedefs()
            self._emit_program_shared_decls(program, bank=bank)
            for module, func in by_bank[bank]:
                self._enter_module(module)
                self._emit_function(func)
            self.bank_units[bank] = "\n".join(self.output)
        self._tu_meta_needs = main_needs
        self.output = main_output

    def _emit_program_shared_decls(self, program, bank=None):
        """Declarations a bank TU shares with the main TU: every enum/struct
        type (typedefs may repeat across separate C files), #define consts,
        `extern` views of the const arrays and globals (defined once in the
        main TU; home data is always mapped), and every function prototype.
        A bank-local const array (code banking: read only by banked code) is
        DEFINED in its owning bank's TU (`bank`) instead of extern'd."""
        for module in program.modules:
            self._enter_module(module)
            for decl in module.declarations:
                if isinstance(decl, TypeDecl):
                    if isinstance(decl.type_def, EnumType):
                        self._emit_enum(decl)
                    elif isinstance(decl.type_def, StructType):
                        self._emit_struct(decl)
        for module in program.modules:
            self._enter_module(module)
            self.emit("/* Module: %s -- shared declarations */" % module.name)
            for decl in module.declarations:
                if isinstance(decl, VarDecl):
                    c_name = self._mangled(module.name, decl.name)
                    is_array = (isinstance(decl.type, ArrayType) or
                                isinstance(decl.initializer, ArrayLiteral))
                    if decl.is_const and not is_array:
                        value = (self.gen_expression(decl.initializer)
                                 if decl.initializer else "0")
                        self.emit("#define %s (%s)" % (c_name, value))
                    elif (bank is not None
                          and self._bank_local_consts.get(c_name) == bank):
                        # This bank owns the const: emit the definition here.
                        self.emit("const "
                                  + self._format_var_decl(decl, c_name) + ";")
                    else:
                        var_type = decl.type
                        if var_type is None:
                            var_type = self._infer_decl_type(decl.initializer)
                        qualifier = "extern const " if decl.is_const else "extern "
                        self.emit(qualifier
                                  + self._format_decl(var_type, c_name) + ";")
                elif isinstance(decl, FunctionDecl):
                    self.emit(self._function_signature(decl) + ";")
            self.emit("")

    def _emit_asset_decls(self, bank=None):
        """`extern` views of the asset-pipeline tile arrays for a bank TU.
        Mirrors the main TU's asset emission (same 3-tuple shape, tile size,
        named-sprite defines and palette externs) so banked code sees the
        same symbols.

        A sheet co-located INTO this bank is DEFINED here instead (its data
        moves out of the resident image); every other TU keeps the extern.
        """
        if not self.assets:
            return
        self.emit("/* --- Assets (defined in the main translation unit) --- */")
        tile_size = 32 if self.sprite_src_bpp == 4 else 16
        for name, data, _bpp in self.assets:
            self.emit("#define %s_tile_count %d" % (name, len(data) // tile_size))
            sym = "%s_tiles" % name
            if (bank is not None and sym not in self.asset_far_bank
                    and self._bank_local_consts.get(sym) == bank):
                self.emit("const uint8_t %s[%d] = {" % (sym, len(data)))
                for i in range(0, len(data), 16):
                    self.emit("    " + " ".join(
                        "0x%02X," % b for b in data[i:i + 16]))
                self.emit("};")
                continue
            self.emit("extern const uint8_t %s[%d];" % (sym, len(data)))
        if self.asset_sprites:
            for sname, offset, wt, ht in self.asset_sprites:
                self.emit("#define %s_tile %d" % (sname, offset))
                self.emit("#define %s_w %d" % (sname, wt))
                self.emit("#define %s_h %d" % (sname, ht))
        if self.asset_palettes16 and (self.sprite_src_bpp == 4
                                      or self.load_sprite16_used):
            for name, _colors in self.asset_palettes16:
                self.emit("extern const uint16_t %s_palette16[16];" % name)
        if self.asset_palettes and self.palette_imported:
            for name, _colors in self.asset_palettes:
                self.emit("extern const uint16_t %s_palette[4];" % name)
        self.emit("")

    def _native_color_expr(self, r, g, b) -> str:
        """One asset-palette entry as C: the port's compile-time RGB8() where
        the toolchain has it, otherwise the value precomputed here -- the
        same quantization the emitted gbs_rgb performs at run time (and, on
        the 4-grey consoles, the same luma thresholds as mosaik_assets'
        PNG shade mapping)."""
        if self.framework == 'gbdk':
            # SMS/GG: ROUND to the CRAM depth (matching the emitted gbs_rgb),
            # NOT the port's RGB8 macro, which truncates and shifts muted tones
            # to primaries (see gbdk._emit_palette_helpers). SMS = 2 bits/chan,
            # GG = 4 bits/chan; same bit layout as the port's RGB8.
            if self.platform == 'sms':
                q = lambda v: (v * 3 + 127) // 255  # noqa: E731
                return "0x%02X" % (q(r) | (q(g) << 2) | (q(b) << 4))
            if self.platform == 'gamegear':
                q = lambda v: (v * 15 + 127) // 255  # noqa: E731
                return "0x%03X" % (q(r) | (q(g) << 4) | (q(b) << 8))
            if self.caps['has_color']:
                return "RGB8(%d, %d, %d)" % (r, g, b)
            luma = (r * 3 + g * 6 + b) // 10
            shade = 0 if luma >= 240 else 1 if luma >= 160 else \
                2 if luma >= 80 else 3
            return str(shade)
        if canonical_platform(self.platform) == 'lynx':
            return "0x%03X" % (((g >> 4) << 8) | ((b >> 4) << 4) | (r >> 4))
        # PCE: 9-bit VCE GGGRRRBBB.
        return "0x%03X" % (((g >> 5) << 6) | ((r >> 5) << 3) | (b >> 5))

    def _emit_enum(self, decl):
        next_value = 0
        for variant in decl.type_def.variants:
            value = variant.value if variant.value is not None else next_value
            self.emit("#define %s %d" % (variant.name, value))
            next_value = value + 1

    def _emit_struct(self, decl):
        self.emit("typedef struct {")
        for field in decl.type_def.fields:
            self.emit("    %s;" % self._format_decl(field.type, field.name))
        self.emit("} %s;" % decl.name)
        self.emit("")

    # -- type formatting ---------------------------------------------------

    def c_type(self, type_obj) -> str:
        if isinstance(type_obj, PrimitiveType):
            return self.PRIMITIVE_C_TYPES.get(type_obj.name, 'uint8_t')
        if isinstance(type_obj, UserDefinedType):
            if type_obj.name in self.enum_types:
                return 'uint8_t'
            return type_obj.name
        if isinstance(type_obj, ArrayType):
            return self.c_type(type_obj.element_type)
        if isinstance(type_obj, FunctionType):
            # A callback lowers to a C function pointer via a synthesized
            # typedef (collected up front in _collect_fnptr_typedefs), so the
            # declarator stays a plain `name` -- arrays/struct fields of
            # callbacks then fall out of the ordinary _format_decl path.
            return self.fnptr_typedefs[self._fnptr_key(type_obj)]
        if type_obj is None:
            return 'uint8_t'
        return 'uint8_t'
