[[scene]]
name = "title"
map = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
collision = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
on_init = "title_init"
[[scene.object]]
kind = "player"
x = 24
y = 32
id = 3


[[scene]]
name = "field"
map = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
collision = [ [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,], [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],]
on_init = "field_init"
[[scene.object]]
kind = "player"
x = 48
y = 56
id = 0

[[scene.object]]
kind = "sign"
x = 40
y = 24
id = 1
on_interact = "sign_talk"


[[door]]
from = "title"
tx = 10
ty = 4
to = "title"
ex = 120
ey = 120
id = 0

[[trigger]]
from = "title"
tx = 5
ty = 2
tw = 4
th = 3
id = 0

[world]
module = "scenes"
map_w = 12
map_h = 9
vm = true
next_door_id = 1
next_object_id = 5
next_trigger_id = 1

[tileset]
png = "assets/tiles.png"

[kinds]
player = 0
sign = 1
