#!/usr/bin/env python3
"""Generate vm-quest -- the VM8 MIGRATION-PROOF mini-RPG. It reproduces the CORE of the composed studio-demo (a field->vault slice:
an NPC you talk to for a key, then a flag-GATED room transition) using ONLY features
the VM8 engine already supports -- heap variables, UI_TEXT dialogue, per-instance
actor slots, scriptable triggers, and CHANGE_SCENE. No combat/shop/HUD (those need
new VM kits).

Author the game as DATA: world.toml (scenes + the elder + the gate trigger) +
scripts/*.evt.toml (the elder's say-once dialogue + the gate's flag check), then the
transpilers emit src/scenes.mos + src/scripts.mos. Run:
  python projects/vm-quest/assets/gen_world.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PROJ))
sys.path.insert(0, ROOT)           # so `import mosaik_assets` resolves

W, H = 12, 9                       # tiles per room (96 x 72 px, fits every screen)


def room(floor=0):
    """A bordered room of floor (tile `floor`) + wall (tile 1) + its parallel
    collision layer (1 = SOLID walls). The vault uses a DISTINCT floor tile (2) so a
    room change is visible in the background (the on-ROM proof)."""
    tiles, coll = [], []
    for y in range(H):
        trow, crow = [], []
        for x in range(W):
            wall = x == 0 or y == 0 or x == W - 1 or y == H - 1
            trow.append(1 if wall else floor)
            crow.append(1 if wall else 0)     # walls are SOLID, floor is passable
        tiles.append(trow)
        coll.append(crow)
    return tiles, coll


def rows(grid):
    return "[" + ", ".join("[" + ",".join(str(v) for v in r) + "]" for r in grid) + "]"


def main():
    field_t, field_c = room(floor=0)
    vault_t, vault_c = room(floor=2)     # a distinct floor -> the change is visible

    # A 3-tile tileset PNG: tile 0 field floor (white), 1 wall (black), 2 vault
    # floor (light grey) -- so the field/vault rooms read differently.
    from mosaik_assets import write_png_indexed
    pal = [(255, 255, 255), (170, 170, 170), (85, 85, 85), (0, 0, 0)]
    os.makedirs(os.path.join(PROJ, "assets"), exist_ok=True)
    write_png_indexed(os.path.join(PROJ, "assets", "tiles.png"), 8, 24,
                      [0] * 64 + [3] * 64 + [1] * 64, pal)

    # ---- world.toml (scenes + placements + the gate trigger) ----
    world = []
    world.append("# vm-quest -- GENERATED by assets/gen_world.py (edit that + rerun).")
    world.append('[[scene]]')
    world.append('name = "field"')
    world.append("map = %s" % rows(field_t))
    world.append("collision = %s" % rows(field_c))
    # the player start (bottom centre) + the elder NPC (upper left)
    world.append('[[scene.object]]\nkind = "player"\nid = 0\nx = 48\ny = 56')
    world.append('[[scene.object]]\nkind = "elder"\nid = 1\nx = 24\ny = 24'
                 '\non_interact = "elder_talk"')
    world.append("")
    world.append('[[scene]]')
    world.append('name = "vault"')
    world.append("map = %s" % rows(vault_t))
    world.append("collision = %s" % rows(vault_c))
    world.append('on_init = "vault_init"')       # greet on arrival
    world.append("")
    # The GATE: a 1x2 trigger rect over the top-centre floor doorway (col 5, rows
    # 1-2). Entering it spawns `gate`, which checks the key flag (flags bit 0).
    world.append('[[trigger]]')
    world.append('id = 1\nfrom = "field"\ntx = 5\nty = 1\ntw = 1\nth = 2'
                 '\non_enter = "gate"')
    world.append("")
    world.append('[world]\nmodule = "scenes"\nmap_w = %d\nmap_h = %d\nvm = true'
                 '\nnext_object_id = 2\nnext_trigger_id = 2' % (W, H))
    world.append('[tileset]\npng = "assets/tiles.png"')
    world.append('[kinds]\nplayer = 0\nelder = 1')
    with open(os.path.join(PROJ, "world.toml"), "w", encoding="utf-8") as f:
        f.write("\n".join(world) + "\n")

    # ---- scripts/*.evt.toml (the game logic as event lists) ----
    os.makedirs(os.path.join(PROJ, "scripts"), exist_ok=True)
    events = '''# vm-quest logic -- the VM8 event lists (the reference engine's project-file analogue).
# One BIT-FLAGS variable (`flags`, VM8's bitwise RPN group) holds the whole
# quest state: bit 0 = the vault key, bit 1 = the vault was entered.
# elder_talk: a SAY-ONCE dialogue that grants the vault key (sets bit 0).
# gate:       a flag-GATED room transition (the composed toll-door, as a script).

[[script]]
name = "main"
events = [ { event = "stop" } ]

[[script]]
name = "elder_talk"
events = [
  { event = "if", cond = "(flags & 1) == 0",
    then = [
      { event = "set_var", var = "flags", expr = "flags | 1" },
      { event = "text", string = "GOT THE KEY!" },
    ],
    else = [
      { event = "text", string = "VAULT AWAITS." },
    ] },
  { event = "stop" },
]

[[script]]
name = "gate"
events = [
  { event = "if", cond = "(flags & 1) == 1",
    then = [
      { event = "change_scene", room = 1, x = 48, y = 40 },
    ],
    else = [
      { event = "text", string = "DOOR IS LOCKED." },
    ] },
  { event = "stop" },
]

[[script]]
name = "vault_init"
events = [
  { event = "set_var", var = "flags", expr = "flags | 2" },
  { event = "text", string = "THE VAULT!" },
  { event = "stop" },
]
'''
    with open(os.path.join(PROJ, "scripts", "main.evt.toml"), "w",
              encoding="utf-8") as f:
        f.write(events)

    # ---- transpile: world.toml -> src/scenes.mos ; events -> src/scripts.mos ----
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_scenes.py"),
                    os.path.join(PROJ, "world.toml"),
                    "-o", os.path.join(PROJ, "src", "scenes.mos")], check=True, cwd=ROOT)
    subprocess.run([sys.executable, os.path.join(ROOT, "mosaik_vm.py"),
                    os.path.join(PROJ, "scripts"),
                    "-o", os.path.join(PROJ, "src", "scripts.mos")], check=True, cwd=ROOT)
    print("vm-quest generated (world.toml + scripts + src/scenes.mos + src/scripts.mos)")


if __name__ == "__main__":
    main()
